import { describe, expect, it } from "vitest";
import {
  appendMarketplaceEvidenceRefsToResolution,
  sanitizeMarketplaceEvidenceRefs,
} from "../marketplace-order-evidence.ts";
import {
  buildMarketplaceOrderStatusHistory,
  describeOperatorReadiness,
  renderFederation,
  resolveMarketplaceIndexOrderReview,
  resolveMarketplaceOrderDisputeHistory,
} from "./federation.ts";

type LitTemplateLike = {
  strings?: ArrayLike<string>;
  values?: unknown[];
};

function toTemplateText(value: unknown): string {
  if (typeof value === "string" || typeof value === "number" || typeof value === "bigint") {
    return String(value);
  }
  if (value instanceof Error) {
    return value.message;
  }
  if (value && typeof value === "object") {
    try {
      return JSON.stringify(value);
    } catch {
      return "";
    }
  }
  return "";
}

function flattenTemplateText(value: unknown): string {
  if (Array.isArray(value)) {
    return value.map((entry) => flattenTemplateText(entry)).join(" ");
  }
  if (value && typeof value === "object") {
    const template = value as LitTemplateLike;
    if (template.strings && Array.isArray(template.values)) {
      return [
        ...Array.from(template.strings),
        ...template.values.map((entry) => flattenTemplateText(entry)),
      ].join(" ");
    }
    try {
      return JSON.stringify(value);
    } catch {
      return "";
    }
  }
  if (typeof value === "function" || value == null || typeof value === "boolean") {
    return "";
  }
  return toTemplateText(value);
}

const walletNamedWallets = [
  {
    id: "wallet-payment",
    name: "Agent Wallet",
    providerId: "embedded-keystore" as const,
    addresses: { solana: "AgentBuyer111111111111111111111111111111111" },
    metadata: { purpose: "agent" },
    readiness: { keystore: true, rpc: true },
  },
  {
    id: "wallet-mining",
    name: "Mining Wallet",
    providerId: "embedded-keystore" as const,
    metadata: { purpose: "mining" },
    readiness: { keystore: true, rpc: true },
  },
];

const multiAgentWallets = [
  {
    id: "agent-secondary",
    name: "Agent 2",
    providerId: "embedded-keystore" as const,
    addresses: { solana: "AgentTwo11111111111111111111111111111111111" },
    metadata: { purpose: "agent" },
    readiness: { keystore: true, rpc: true },
  },
  {
    id: "wallet-mining",
    name: "Mining Wallet",
    providerId: "embedded-keystore" as const,
    metadata: { purpose: "mining" },
    readiness: { keystore: true, rpc: true },
  },
  {
    id: "agent-primary",
    name: "Primary Agent",
    providerId: "embedded-keystore" as const,
    addresses: { solana: "PrimaryAgent1111111111111111111111111111111" },
    metadata: { purpose: "agent" },
    readiness: { keystore: true, rpc: true },
  },
];

const marketplaceOffers = [
  {
    handle: "@mock-summarizer@fased.test",
    nodeId: "node-mock-summarizer",
    status: "verified",
    endpoint: "https://mock-summarizer.example",
    offer: {
      id: "https://mock-summarizer.example/offers/content-summarize-v0",
      actor: "@mock-summarizer@fased.test",
      title: "Content summarize v0",
      summary: "Summarize source text into a short result.",
      serviceKind: "content.summarize",
      deliveryShape: "summary-v0",
      paymentDefaults: {
        currency: "SOL",
        chain: "solana",
        assetDecimals: 9,
        asset: { kind: "native" },
        payee: {
          chain: "solana",
          address: "MockSellerSolana11111111111111111111111111111",
        },
      },
      requiredTrustOrBondTier: "verified",
    },
    reviewSummary: {
      count: 2,
      averageRating: 4.5,
      verifiedPaymentCount: 1,
    },
    disputeSummary: {
      count: 1,
      underReviewCount: 1,
      openCount: 0,
      resolvedCount: 0,
      dismissedCount: 0,
    },
    sellerLane: {
      status: "bonded-public",
      eligible: true,
      visibility: "public",
      reasons: [],
      paymentRailsReady: true,
      endpointHealthy: true,
    },
  },
];

describe("marketplace dispute evidence helpers", () => {
  it("keeps safe refs and drops raw URLs, paths, and secrets", () => {
    const refs = sanitizeMarketplaceEvidenceRefs([
      "invoice:invoice-1",
      "receipt:receipt-1",
      "artifact:fased://marketplace/orders/order-1/result",
      "artifact:https://buyer.example/secret-token",
      "path:/home/fc/private.txt",
      "bearer token",
    ]);

    expect(refs).toEqual([
      "invoice:invoice-1",
      "receipt:receipt-1",
      "artifact:fased://marketplace/orders/order-1/result",
    ]);
  });

  it("appends sanitized refs once to an operator resolution draft", () => {
    const draft = appendMarketplaceEvidenceRefsToResolution("Checked delivery trail.", [
      "invoice:invoice-1",
      "artifact:https://buyer.example/secret-token",
      "result:task-1",
    ]);

    expect(draft).toBe(
      "Checked delivery trail.\nEvidence reviewed: invoice:invoice-1, result:task-1",
    );
    expect(appendMarketplaceEvidenceRefsToResolution(draft, ["invoice:invoice-1"])).toBe(draft);
  });
});

describe("buildMarketplaceOrderStatusHistory", () => {
  it("shows payment, run, delivery, receipt, and dispute availability for federation orders", () => {
    const history = buildMarketplaceOrderStatusHistory({
      source: "federation",
      status: "delivered",
      configId: "index-order-1",
      order: {
        id: "index-order-1",
        source: "federation",
        status: "delivered",
        offerId: "https://mock-summarizer.example/offers/content-summarize-v0",
        sellerHandle: "@mock-summarizer@fased.test",
        serviceKind: "content.summarize",
        title: "Content summarize v0",
        pricing: { amount: 0.02, currency: "SOL", model: "fixed", unit: "per-job" },
        paymentIntent: {
          status: "verified",
          amount: 0.02,
          currency: "SOL",
          method: "agent-wallet",
          txRef: "tx-paid-1",
          updatedAt: "2026-05-03T10:01:00.000Z",
        },
        delivery: {
          status: "delivered",
          targetKind: "channel",
          targetLabel: "Telegram",
          targetMasked: "@buyer",
          resultRef: "task-result-1",
          artifactRef: "fased://marketplace/orders/index-order-1/content-summarize/task-result-1",
          deliveredAt: "2026-05-03T10:02:00.000Z",
        },
        receipt: {
          status: "issued",
          invoiceId: "invoice-1",
          receiptId: "receipt-1",
          txRef: "tx-paid-1",
          resultRef: "task-result-1",
          updatedAt: "2026-05-03T10:02:00.000Z",
        },
        createdAt: "2026-05-03T10:00:00.000Z",
        updatedAt: "2026-05-03T10:02:00.000Z",
      },
    });

    expect(history.map((item) => item.label)).toEqual([
      "Checkout",
      "Payment",
      "Settlement",
      "Run",
      "Delivery",
      "Receipt",
      "Dispute",
    ]);
    expect(history.find((item) => item.label === "Payment")).toMatchObject({
      status: "verified",
      tone: "ok",
    });
    expect(history.find((item) => item.label === "Delivery")).toMatchObject({
      status: "delivered",
      tone: "ok",
    });
    expect(history.find((item) => item.label === "Receipt")?.refs).toEqual(
      expect.arrayContaining([
        { label: "invoice", value: "invoice-1" },
        { label: "receipt", value: "receipt-1" },
        { label: "tx", value: "tx-paid-1" },
      ]),
    );
    expect(history.find((item) => item.label === "Dispute")).toMatchObject({
      status: "available",
      tone: "ok",
    });
  });

  it("includes escrow funding and release refs in settlement history", () => {
    const history = buildMarketplaceOrderStatusHistory({
      source: "federation",
      status: "delivered",
      configId: "index-order-escrow",
      order: {
        id: "index-order-escrow",
        source: "federation",
        status: "delivered",
        offerId: "https://mock-summarizer.example/offers/content-summarize-v0",
        sellerHandle: "@mock-summarizer@fased.test",
        serviceKind: "content.summarize",
        pricing: { amount: 0.02, currency: "SOL", model: "fixed", unit: "per-job" },
        paymentIntent: {
          status: "verified",
          amount: 0.02,
          currency: "SOL",
          method: "agent-wallet",
        },
        settlement: {
          mode: "escrow",
          status: "held",
          currency: "SOL",
          chain: "solana",
          assetKind: "native",
          escrow: {
            status: "held",
            fundingRequestId: "fund-request-1",
            fundingTxRef: "fund-tx-1",
            releaseRequestId: "release-request-1",
            refundRequestId: "refund-request-1",
            refundTxRef: "refund-tx-1",
          },
        },
        delivery: {
          status: "delivered",
        },
        createdAt: "2026-05-03T10:00:00.000Z",
        updatedAt: "2026-05-03T10:02:00.000Z",
      },
    });

    expect(history.find((item) => item.label === "Settlement")?.refs).toEqual(
      expect.arrayContaining([
        { label: "funding", value: "fund-request-1" },
        { label: "funding tx", value: "fund-tx-1" },
        { label: "release", value: "release-request-1" },
        { label: "refund", value: "refund-request-1" },
        { label: "refund tx", value: "refund-tx-1" },
      ]),
    );
  });
});

describe("resolveMarketplaceOrderDisputeHistory", () => {
  it("links matching disputes and notary opinions to an order with sanitized evidence", () => {
    const history = resolveMarketplaceOrderDisputeHistory(
      {
        source: "federation",
        status: "delivered",
        configId: "index-order-1",
        order: {
          id: "index-order-1",
          source: "federation",
          status: "delivered",
          offerId: "https://mock-summarizer.example/offers/content-summarize-v0",
          sellerHandle: "@mock-summarizer@fased.test",
          serviceKind: "content.summarize",
          title: "Content summarize v0",
          pricing: { amount: 0.02, currency: "SOL", model: "fixed", unit: "per-job" },
          paymentIntent: {
            status: "verified",
            amount: 0.02,
            currency: "SOL",
            method: "agent-wallet",
            txRef: "tx-paid-1",
          },
          delivery: {
            status: "delivered",
            resultRef: "task-result-1",
            artifactRef: "fased://marketplace/orders/index-order-1/content-summarize/task-result-1",
          },
          receipt: {
            status: "issued",
            invoiceId: "invoice-1",
            receiptId: "receipt-1",
            txRef: "tx-paid-1",
            resultRef: "task-result-1",
          },
          createdAt: "2026-05-03T10:00:00.000Z",
          updatedAt: "2026-05-03T10:02:00.000Z",
        },
      } as never,
      [
        {
          schema: "https://domain.com/schemas/fased-dispute-v0.json",
          caseId: "case-1",
          taskId: "task-result-1",
          offerId: "https://mock-summarizer.example/offers/content-summarize-v0",
          reporterHandle: "@buyer@fased.test",
          providerHandle: "@mock-summarizer@fased.test",
          paymentStatus: "verified",
          reasonCode: "delivery_mismatch",
          invoiceId: "invoice-1",
          receiptId: "receipt-1",
          summary: "Formatting mismatch",
          evidenceRefs: [
            "invoice:invoice-1",
            "receipt:receipt-1",
            "artifact:fased://marketplace/orders/index-order-1/content-summarize/task-result-1",
            "artifact:https://buyer.example/secret-token",
          ],
          status: "resolved",
          resolution: "Provider issued corrected delivery.",
          createdAt: "2026-05-03T10:03:00.000Z",
          updatedAt: "2026-05-03T10:04:00.000Z",
          reviewedAt: "2026-05-03T10:04:00.000Z",
        },
      ] as never,
      [
        {
          schema: "https://domain.com/schemas/fased-dispute-notary-v0.json",
          caseId: "case-1",
          notaryHandle: "@operator-notary@fased.test",
          bondTier: "operator-bond",
          opinion: "supports-claim",
          summary: "Evidence supports the claim.",
          evidenceRefs: ["invoice:invoice-1", "artifact:https://buyer.example/secret-token"],
          decisionConfidence: "high",
          recommendedResolution: "resolved",
          createdAt: "2026-05-03T10:05:00.000Z",
        },
      ],
    );

    expect(history).toHaveLength(1);
    expect(history[0]?.dispute.caseId).toBe("case-1");
    expect(history[0]?.evidenceRefs).toEqual([
      "invoice:invoice-1",
      "receipt:receipt-1",
      "artifact:fased://marketplace/orders/index-order-1/content-summarize/task-result-1",
    ]);
    expect(history[0]?.notaryRecords).toHaveLength(1);
    expect(history[0]?.notaryRecords[0]?.notaryHandle).toBe("@operator-notary@fased.test");
  });
});

describe("describeOperatorReadiness", () => {
  it("summarizes a fully ready operator path", () => {
    const items = describeOperatorReadiness({
      status: {
        joined: true,
        token: {
          handle: "@fased@example.com",
          trustState: "verified",
          hostedState: "ready",
          publicUrl: "https://node.example.com",
        },
      } as never,
      token: {
        handle: "@fased@example.com",
        trustState: "verified",
        hostedState: "ready",
        publicUrl: "https://node.example.com",
      } as never,
      managedMode: false,
      walletStatus: {
        approvalAuth: {
          mode: "webauthn",
          ready: true,
          passkeyCount: 1,
          notes: [],
          passkeys: [],
          statePath: "/tmp/passkeys.json",
        },
      } as never,
      walletNamedWallets,
      defaultWalletId: "wallet-payment",
      miningAttachedWalletId: "wallet-mining",
      miningProfile: { walletId: "wallet-mining" } as never,
      miningReadiness: null,
      miningStatus: null,
    });

    expect(items.map((item) => item.title)).toEqual([
      "Wallet Control Passkey ready",
      "Agent wallet set",
      "Mining wallet separate",
      "Vault wallet present",
      "Fased Network joined / trusted",
      "Fased Network reachability state",
    ]);
    expect(items[0]).toMatchObject({ tone: "success" });
    expect(items[1]).toMatchObject({ summary: "Agent Wallet", tone: "success" });
    expect(items[2]).toMatchObject({ summary: "Mining Wallet", tone: "success" });
    expect(items[3]).toMatchObject({ summary: "Not set", tone: "neutral" });
    expect(items[4]).toMatchObject({ summary: "Verified", tone: "success" });
    expect(items[5]).toMatchObject({ summary: "Ready", tone: "success" });
    expect(items.slice(0, 4).map((item) => item.actionLabel)).toEqual([
      "Open Wallet Access",
      "Set Agent",
      "Open Mining",
      undefined,
    ]);
  });

  it("marks optional mining and unjoined federation clearly", () => {
    const items = describeOperatorReadiness({
      status: null,
      token: null,
      managedMode: false,
      walletStatus: {
        approvalAuth: {
          mode: "none",
          ready: false,
          passkeyCount: 0,
          notes: [],
          passkeys: [],
          statePath: "/tmp/passkeys.json",
        },
      } as never,
      walletNamedWallets,
      defaultWalletId: "wallet-payment",
      miningAttachedWalletId: null,
      miningProfile: null,
      miningReadiness: null,
      miningStatus: null,
    });

    const miningItem = items.find((item) => item.title === "Mining wallet separate");
    const vaultItem = items.find((item) => item.title === "Vault wallet present");
    const networkItem = items.find((item) => item.title === "Fased Network joined / trusted");
    const reachabilityItem = items.find(
      (item) => item.title === "Fased Network reachability state",
    );

    expect(miningItem).toMatchObject({
      summary: "Optional and not configured",
      tone: "neutral",
    });
    expect(vaultItem).toMatchObject({
      summary: "Not set",
      tone: "neutral",
    });
    expect(networkItem).toMatchObject({
      summary: "Not joined",
      tone: "warn",
    });
    expect(reachabilityItem).toMatchObject({
      summary: "Disabled",
      tone: "neutral",
    });
  });

  it("flags when SAT mining and payment share one wallet", () => {
    const items = describeOperatorReadiness({
      status: {
        joined: true,
        token: {
          handle: "@fased@example.com",
          trustState: "pending",
          hostedState: "pending",
        },
      } as never,
      token: {
        handle: "@fased@example.com",
        trustState: "pending",
        hostedState: "pending",
      } as never,
      managedMode: false,
      walletStatus: {
        approvalAuth: {
          mode: "webauthn",
          ready: true,
          passkeyCount: 1,
          notes: [],
          passkeys: [],
          statePath: "/tmp/passkeys.json",
        },
      } as never,
      walletNamedWallets,
      defaultWalletId: "wallet-payment",
      miningAttachedWalletId: "wallet-payment",
      miningProfile: { walletId: "wallet-payment" } as never,
      miningReadiness: null,
      miningStatus: null,
    });

    expect(items[2].tone).toBe("warn");
    expect(items[2].detail).toContain("must stay separate");
  });
});

describe("renderFederation", () => {
  it("surfaces live bond state without noisy access copy", () => {
    const text = flattenTemplateText(
      renderFederation({
        loading: false,
        error: null,
        message: null,
        directory: [],
        handle: "@bonded@ff1.fased.app",
        nodeEndpoint: "http://127.0.0.1:18789",
        token: {
          handle: "@bonded@ff1.fased.app",
          scopes: ["federation.read", "federation.write"],
          trustState: "verified",
          hostedState: "ready",
          expiresAt: "2026-05-01T00:00:00.000Z",
          paidFlowEligible: true,
          bondTier: "operator-bond",
          bondQuotaBand: "operator",
          bondDerivedScopes: [
            "offers.publish",
            "payments.receive.boost",
            "directory.priority.basic",
            "routing.capacity.basic",
          ],
        } as never,
        status: {
          managed: false,
          sourcePath: "/tmp/federation/access-token.json",
          joined: true,
          lifecycle: "active",
          checkedAt: "2026-04-19T00:00:00.000Z",
          token: {
            handle: "@bonded@ff1.fased.app",
            trustState: "verified",
            hostedState: "ready",
            expiresAt: "2026-05-01T00:00:00.000Z",
            paidFlowEligible: true,
            bondTier: "operator-bond",
            bondQuotaBand: "operator",
          } as never,
          bond: {
            exists: true,
            source: "token",
            walletId: "wallet-bond",
            walletAddress: "BondWallet111111111111111111111111111111111",
            bondId: "BondPosition1111111111111111111111111111111",
            status: "active",
            tier: "operator-bond",
            amountRaw: "10000000000000",
            unlockAvailableAt: "slot:999",
            quotaBand: "operator",
            derivedScopes: [
              "offers.publish",
              "payments.receive.boost",
              "directory.priority.basic",
              "routing.capacity.basic",
            ],
            staking: {
              distributor: {
                exists: true,
                status: "active",
                totalActiveStakeRaw: "250000000000000",
                rewardIndexFp: "63200000000000000",
                observedRewardVaultRaw: "0",
                rewardVaultBalanceRaw: "15800000000000",
              },
              position: {
                exists: true,
                status: "active",
                activeStakeRaw: "250000000000000",
                claimableRewardRaw: "0",
                rewardDebtFp: "0",
                estimatedClaimableRewardRaw: "15800000000000",
              },
            },
            warnings: [],
          },
          sellerLane: {
            status: "bonded-public",
            eligible: true,
            visibility: "public",
            reasons: [],
            endpointHealthy: true,
          },
          routingCapacity: {
            status: "routing-basic",
            eligible: true,
            intake: "priority",
            reasons: [],
            endpointHealthy: true,
            measurements: {
              trustState: "verified",
              bondStatus: "active",
              quotaBand: "operator",
              hasRoutingScope: true,
              activeBond: true,
            },
          },
          hostedEdge: {
            status: "managed-edge",
            eligible: true,
            exposure: "managed-public",
            reasons: [],
            managedPublicUrl: "https://bonded.agents.fased.app",
            routeHealthy: true,
            measurements: {
              trustState: "verified",
              bondStatus: "active",
              quotaBand: "operator",
              hostedState: "ready",
              hasManagedUrl: true,
              hasManagedAttachment: true,
              activeBond: true,
            },
          },
          directoryIndexer: {
            status: "index-basic",
            eligible: true,
            surface: "mirrored-public",
            reasons: [],
            lastSeenAt: "2026-04-19T00:00:00.000Z",
            measurements: {
              trustState: "verified",
              bondStatus: "active",
              quotaBand: "operator",
              hasDirectoryScope: true,
              activeBond: true,
              freshness: "fresh",
              lastSeenAgeSeconds: 30,
            },
          },
          artifactAvailability: {
            status: "availability-basic",
            eligible: true,
            retrieval: "shareable-public",
            reasons: [],
            measurements: {
              trustState: "verified",
              bondStatus: "active",
              quotaBand: "operator",
              activeBond: true,
              endpointHealthy: true,
              shareableSurface: true,
              integrityMode: "declared",
              replicationClass: "multi-surface",
            },
          },
        } as never,
        managedMode: false,
        adminToken: "",
        reviewReason: "",
        reviewBusyHandle: null,
        feeOpsLoading: false,
        feeOpsError: null,
        feeCollectionStatus: [
          {
            lane: "marketplace",
            enabled: false,
            reason: "collection disabled until retained history threshold is met",
            thresholds: {
              historyDays: 14,
              marketplaceRuns: 30,
              disputeNotaryCases: 10,
              settlementVerifierCases: 10,
              routingRuns: 30,
            },
            observed: {
              historyDaysObserved: 3,
              marketplaceRunsObserved: 3,
              disputeNotaryCasesObserved: 1,
              settlementVerifierCasesObserved: 1,
              routingRunsObserved: 0,
            },
          },
        ],
        feeObjects: [
          {
            feeId: "mock-fee-view-1",
            schema: "https://fased.ai/schemas/operator-economy/fee-object-v0.json",
            lane: "marketplace",
            status: "collected",
            policyVersion: "oe-fees-v0",
            amount: "1.5",
            asset: {
              chain: "solana",
              symbol: "USDC",
              kind: "spl-token",
            },
            allocationPlan: [{ bucket: "federation_ops_reserve", amount: "1.5" }],
            reviewState: "approved",
            body: {},
            createdAt: "2026-04-20T00:00:00.000Z",
            updatedAt: "2026-04-20T00:05:00.000Z",
          },
        ],
        feeBucketJournal: [
          {
            journalId: "mock-fee-view-1::allocation::0",
            feeId: "mock-fee-view-1",
            bucket: "federation_ops_reserve",
            asset: {
              chain: "solana",
              symbol: "USDC",
              kind: "spl-token",
            },
            amount: "1.5",
            direction: "credit",
            entryType: "allocation",
            policyVersion: "oe-fees-v0",
            createdAt: "2026-04-20T00:05:00.000Z",
          },
        ],
        feeBucketBalances: [
          {
            bucket: "federation_ops_reserve",
            asset: {
              chain: "solana",
              symbol: "USDC",
              kind: "spl-token",
            },
            credited: "1.5",
            debited: "0",
            heldBalance: "1.5",
          },
        ],
        feeReconciliationReports: [
          {
            reportId: "mock-reconcile-view-1",
            periodStart: "2026-04-19T00:00:00.000Z",
            periodEnd: "2026-04-20T00:00:00.000Z",
            bucket: "federation_ops_reserve",
            asset: {
              chain: "solana",
              symbol: "USDC",
              kind: "spl-token",
            },
            expectedBalance: "1.5",
            observedBalance: "1.5",
            variance: "0",
            reviewState: "clean",
            reviewedBy: ["fc"],
          },
        ],
        feeShowcase: {
          available: true,
          source: "local-fallback",
          simulated: true,
          nonEvidence: true,
          hasThresholdStatus: true,
          hasCollectionEvidence: true,
          collectionActivationMode: "real-domain-events",
          reconciliationMode: "auto-generated",
          routingCollectionDeferred: true,
          payoutEnabled: false,
          notes: [
            "showcase mode is using simulated operator-economy evidence for demo purposes only",
          ],
        },
        localOffers: [],
        localOffersLoading: false,
        localOffersError: null,
        localOffersMessage: null,
        localOfferBusy: false,
        localOfferDraftOpen: false,
        localOfferEditingId: null,
        localOfferEnabledDraft: true,
        localOfferTitleDraft: "",
        localOfferSummaryDraft: "",
        localOfferServiceKindDraft: "",
        localOfferInputShapeDraft: "",
        localOfferDeliveryShapeDraft: "",
        localOfferCapabilitiesDraft: "",
        offersLoading: false,
        offersError: null,
        offers: marketplaceOffers as never,
        offersQuery: "",
        offersServiceKindFilter: "content.summarize",
        selectedOfferId: "https://mock-summarizer.example/offers/content-summarize-v0",
        offerReviewsLoading: false,
        offerReviewsError: null,
        offerReviews: [],
        offerDisputesLoading: false,
        offerDisputesError: null,
        offerDisputes: [],
        offerFeedbackBusy: false,
        offerFeedbackError: null,
        offerFeedbackMessage: null,
        offerFeedbackTab: "review",
        summarizeSourceText: "",
        summarizeStyle: "bullets",
        summarizeMaxSentences: "2",
        summarizeBusy: false,
        summarizeError: null,
        paidSummarizeBusy: false,
        paidSummarizeError: null,
        summarizeResult: null,
        paidQuoteAmountDraft: "0.01",
        paidQuoteAssetDecimalsDraft: "9",
        paidQuoteCurrencyDraft: "SOL",
        paidQuoteChainDraft: "solana",
        paidQuoteAssetKindDraft: "native",
        paidQuoteAssetAddressDraft: "",
        paidQuotePayeeAddressDraft: "",
        paidQuoteExpiresMinutesDraft: "5",
        reviewRatingDraft: "5",
        reviewOutcomeDraft: "satisfied",
        reviewPaymentStatusDraft: "verified",
        reviewInvoiceIdDraft: "",
        reviewReceiptIdDraft: "",
        reviewSummaryDraft: "",
        disputeReasonCodeDraft: "delivery_mismatch",
        disputePaymentStatusDraft: "verified",
        disputeInvoiceIdDraft: "",
        disputeReceiptIdDraft: "",
        disputeSummaryDraft: "",
        operatorDisputesLoading: false,
        operatorDisputesError: null,
        operatorDisputes: [],
        operatorDisputeProviderFilter: "",
        operatorDisputeOfferIdFilter: "",
        operatorDisputeStatusFilter: "all",
        operatorDisputePaymentStatusFilter: "all",
        operatorSelectedCaseId: "",
        operatorDisputeReviewStatusDraft: "under_review",
        operatorDisputeResolutionDraft: "",
        operatorDisputeReviewBusy: false,
        operatorDisputeReviewError: null,
        operatorDisputeReviewMessage: null,
        walletStatus: null,
        walletNamedWallets,
        defaultWalletId: "wallet-payment",
        miningAttachedWalletId: "wallet-mining",
        miningProfile: { walletId: "wallet-mining" } as never,
        miningReadiness: null,
        miningStatus: null,
        onOpenAdminControl: () => undefined,
        onOpenTaskPayment: () => undefined,
        onOpenMining: () => undefined,
        onOpenFederationReview: () => undefined,
        onHandleChange: () => undefined,
        onNodeEndpointChange: () => undefined,
        onAdminTokenChange: () => undefined,
        onReviewReasonChange: () => undefined,
        onRefreshLocalOffers: () => undefined,
        onStartLocalOfferDraft: () => undefined,
        onCancelLocalOfferDraft: () => undefined,
        onLocalOfferEnabledDraftChange: () => undefined,
        onLocalOfferTitleDraftChange: () => undefined,
        onLocalOfferSummaryDraftChange: () => undefined,
        onLocalOfferServiceKindDraftChange: () => undefined,
        onLocalOfferInputShapeDraftChange: () => undefined,
        onLocalOfferDeliveryShapeDraftChange: () => undefined,
        onLocalOfferCapabilitiesDraftChange: () => undefined,
        onSaveLocalOffer: () => undefined,
        onToggleLocalOffer: () => undefined,
        onDeleteLocalOffer: () => undefined,
        onOffersQueryChange: () => undefined,
        onOffersServiceKindFilterChange: () => undefined,
        onSelectOffer: () => undefined,
        onLoadOfferReputation: () => undefined,
        onSummarizeSourceTextChange: () => undefined,
        onSummarizeStyleChange: () => undefined,
        onSummarizeMaxSentencesChange: () => undefined,
        onPaidQuoteAmountDraftChange: () => undefined,
        onPaidQuoteAssetDecimalsDraftChange: () => undefined,
        onPaidQuoteCurrencyDraftChange: () => undefined,
        onPaidQuoteChainDraftChange: () => undefined,
        onPaidQuoteAssetKindDraftChange: () => undefined,
        onPaidQuoteAssetAddressDraftChange: () => undefined,
        onPaidQuotePayeeAddressDraftChange: () => undefined,
        onPaidQuoteExpiresMinutesDraftChange: () => undefined,
        onReviewRatingDraftChange: () => undefined,
        onReviewOutcomeDraftChange: () => undefined,
        onReviewPaymentStatusDraftChange: () => undefined,
        onReviewInvoiceIdDraftChange: () => undefined,
        onReviewReceiptIdDraftChange: () => undefined,
        onReviewSummaryDraftChange: () => undefined,
        onDisputeReasonCodeDraftChange: () => undefined,
        onDisputePaymentStatusDraftChange: () => undefined,
        onDisputeInvoiceIdDraftChange: () => undefined,
        onDisputeReceiptIdDraftChange: () => undefined,
        onDisputeSummaryDraftChange: () => undefined,
        onOperatorDisputeProviderFilterChange: () => undefined,
        onOperatorDisputeOfferIdFilterChange: () => undefined,
        onOperatorDisputeStatusFilterChange: () => undefined,
        onOperatorDisputePaymentStatusFilterChange: () => undefined,
        onOperatorSelectedCaseIdChange: () => undefined,
        onOperatorDisputeReviewStatusDraftChange: () => undefined,
        onOperatorDisputeResolutionDraftChange: () => undefined,
        onRegister: () => undefined,
        onAttest: () => undefined,
        onRenew: () => undefined,
        onRevoke: () => undefined,
        onReview: () => undefined,
        onRefresh: () => undefined,
        onRefreshOperatorEconomy: () => undefined,
        onRefreshOffers: () => undefined,
        onRunContentSummarize: () => undefined,
        onRunPaidContentSummarize: () => undefined,
        onPublishReview: () => undefined,
        onPublishDispute: () => undefined,
        onOfferFeedbackTabChange: () => undefined,
        onLoadOperatorDisputes: () => undefined,
        onReviewDispute: () => undefined,
      }),
    );

    expect(text).toContain("Fased Network trust state: verified");
    expect(text).toContain("Live");
    expect(text).not.toContain("Access");
    expect(text).not.toContain("Read, Write");
    expect(text).not.toContain("Payments");
    expect(text).not.toContain("proof-derived");
    expect(text).toContain("Bond state:");
    expect(text).toContain("Market");
    expect(text).toContain("Vault");
    expect(text).toContain("Bond...1111");
    expect(text).toContain("500 SAT");
    expect(text).toContain("Bond position");
    expect(text).toContain("Top up");
    expect(text).toContain("Unlock all");
    expect(text).toContain("Claimable");
    expect(text).toContain("158 SAT");
    expect(text).toContain("Pool");
    expect(text).not.toContain("Staking weight");
    expect(text).toContain("Renew token");
    expect(text).toContain("Revoke token");
    expect(text).not.toContain("Registry");
    expect(text).not.toContain("Marketplace fees");
  });

  it("shows the overview as degraded when the remote origin is unavailable", () => {
    const text = flattenTemplateText(
      renderFederation({
        loading: false,
        error:
          "Fased Network directory refresh unavailable. HTTP 502 Bad Gateway from ff1.fased.app",
        message: null,
        directory: [],
        handle: "@bonded@ff1.fased.app",
        nodeEndpoint: "http://127.0.0.1:18789",
        token: {
          handle: "@bonded@ff1.fased.app",
          trustState: "verified",
          hostedState: "ready",
          expiresAt: "2026-05-01T00:00:00.000Z",
          paidFlowEligible: true,
          bondTier: "operator-bond",
          bondQuotaBand: "operator",
        } as never,
        status: {
          managed: false,
          sourcePath: "/tmp/federation/access-token.json",
          joined: true,
          lifecycle: "active",
          checkedAt: "2026-04-19T00:00:00.000Z",
          token: {
            handle: "@bonded@ff1.fased.app",
            trustState: "verified",
            hostedState: "ready",
            expiresAt: "2026-05-01T00:00:00.000Z",
            paidFlowEligible: true,
            bondTier: "operator-bond",
            bondQuotaBand: "operator",
          } as never,
          bond: {
            exists: true,
            source: "token",
            walletId: "wallet-bond",
            walletAddress: "BondWallet111111111111111111111111111111111",
            bondId: "BondPosition1111111111111111111111111111111",
            status: "active",
            tier: "operator-bond",
            amountRaw: "10000000000000",
            quotaBand: "operator",
            derivedScopes: ["offers.publish"],
            warnings: [],
          },
        } as never,
        managedMode: false,
        adminToken: "",
        reviewReason: "",
        reviewBusyHandle: null,
        localOffers: [],
        localOffersLoading: false,
        localOffersError: null,
        localOffersMessage: null,
        localOfferBusy: false,
        localOfferDraftOpen: false,
        localOfferEditingId: null,
        localOfferEnabledDraft: true,
        localOfferTitleDraft: "",
        localOfferSummaryDraft: "",
        localOfferServiceKindDraft: "",
        localOfferInputShapeDraft: "",
        localOfferDeliveryShapeDraft: "",
        localOfferCapabilitiesDraft: "",
        offersLoading: false,
        offersError: null,
        offers: marketplaceOffers as never,
        offersQuery: "",
        offersServiceKindFilter: "content.summarize",
        selectedOfferId: "https://mock-summarizer.example/offers/content-summarize-v0",
        offerReviewsLoading: false,
        offerReviewsError: null,
        offerReviews: [],
        offerDisputesLoading: false,
        offerDisputesError: null,
        offerDisputes: [],
        offerFeedbackBusy: false,
        offerFeedbackError: null,
        offerFeedbackMessage: null,
        offerFeedbackTab: "review",
        summarizeSourceText: "",
        summarizeStyle: "bullets",
        summarizeMaxSentences: "2",
        summarizeBusy: false,
        summarizeError: null,
        paidSummarizeBusy: false,
        paidSummarizeError: null,
        summarizeResult: null,
        paidQuoteAmountDraft: "0.01",
        paidQuoteAssetDecimalsDraft: "9",
        paidQuoteCurrencyDraft: "SOL",
        paidQuoteChainDraft: "solana",
        paidQuoteAssetKindDraft: "native",
        paidQuoteAssetAddressDraft: "",
        paidQuotePayeeAddressDraft: "",
        paidQuoteExpiresMinutesDraft: "5",
        reviewRatingDraft: "5",
        reviewOutcomeDraft: "satisfied",
        reviewPaymentStatusDraft: "verified",
        reviewInvoiceIdDraft: "",
        reviewReceiptIdDraft: "",
        reviewSummaryDraft: "",
        disputeReasonCodeDraft: "delivery_mismatch",
        disputePaymentStatusDraft: "verified",
        disputeInvoiceIdDraft: "",
        disputeReceiptIdDraft: "",
        disputeSummaryDraft: "",
        operatorDisputesLoading: false,
        operatorDisputesError: null,
        operatorDisputes: [],
        operatorDisputeProviderFilter: "",
        operatorDisputeOfferIdFilter: "",
        operatorDisputeStatusFilter: "all",
        operatorDisputePaymentStatusFilter: "all",
        operatorSelectedCaseId: "",
        operatorDisputeReviewStatusDraft: "under_review",
        operatorDisputeResolutionDraft: "",
        operatorDisputeReviewBusy: false,
        operatorDisputeReviewError: null,
        operatorDisputeReviewMessage: null,
        walletStatus: null,
        walletNamedWallets,
        defaultWalletId: "wallet-payment",
        miningAttachedWalletId: "wallet-mining",
        miningProfile: { walletId: "wallet-mining" } as never,
        miningReadiness: null,
        miningStatus: null,
        onOpenAdminControl: () => undefined,
        onOpenTaskPayment: () => undefined,
        onOpenMining: () => undefined,
        onOpenFederationReview: () => undefined,
        onHandleChange: () => undefined,
        onNodeEndpointChange: () => undefined,
        onAdminTokenChange: () => undefined,
        onReviewReasonChange: () => undefined,
        onRefreshLocalOffers: () => undefined,
        onStartLocalOfferDraft: () => undefined,
        onCancelLocalOfferDraft: () => undefined,
        onLocalOfferEnabledDraftChange: () => undefined,
        onLocalOfferTitleDraftChange: () => undefined,
        onLocalOfferSummaryDraftChange: () => undefined,
        onLocalOfferServiceKindDraftChange: () => undefined,
        onLocalOfferInputShapeDraftChange: () => undefined,
        onLocalOfferDeliveryShapeDraftChange: () => undefined,
        onLocalOfferCapabilitiesDraftChange: () => undefined,
        onSaveLocalOffer: () => undefined,
        onToggleLocalOffer: () => undefined,
        onDeleteLocalOffer: () => undefined,
        onOffersQueryChange: () => undefined,
        onOffersServiceKindFilterChange: () => undefined,
        onSelectOffer: () => undefined,
        onLoadOfferReputation: () => undefined,
        onSummarizeSourceTextChange: () => undefined,
        onSummarizeStyleChange: () => undefined,
        onSummarizeMaxSentencesChange: () => undefined,
        onPaidQuoteAmountDraftChange: () => undefined,
        onPaidQuoteAssetDecimalsDraftChange: () => undefined,
        onPaidQuoteCurrencyDraftChange: () => undefined,
        onPaidQuoteChainDraftChange: () => undefined,
        onPaidQuoteAssetKindDraftChange: () => undefined,
        onPaidQuoteAssetAddressDraftChange: () => undefined,
        onPaidQuotePayeeAddressDraftChange: () => undefined,
        onPaidQuoteExpiresMinutesDraftChange: () => undefined,
        onReviewRatingDraftChange: () => undefined,
        onReviewOutcomeDraftChange: () => undefined,
        onReviewPaymentStatusDraftChange: () => undefined,
        onReviewInvoiceIdDraftChange: () => undefined,
        onReviewReceiptIdDraftChange: () => undefined,
        onReviewSummaryDraftChange: () => undefined,
        onDisputeReasonCodeDraftChange: () => undefined,
        onDisputePaymentStatusDraftChange: () => undefined,
        onDisputeInvoiceIdDraftChange: () => undefined,
        onDisputeReceiptIdDraftChange: () => undefined,
        onDisputeSummaryDraftChange: () => undefined,
        onOperatorDisputeProviderFilterChange: () => undefined,
        onOperatorDisputeOfferIdFilterChange: () => undefined,
        onOperatorDisputeStatusFilterChange: () => undefined,
        onOperatorDisputePaymentStatusFilterChange: () => undefined,
        onOperatorSelectedCaseIdChange: () => undefined,
        onOperatorDisputeReviewStatusDraftChange: () => undefined,
        onOperatorDisputeResolutionDraftChange: () => undefined,
        onRegister: () => undefined,
        onAttest: () => undefined,
        onRenew: () => undefined,
        onRevoke: () => undefined,
        onReview: () => undefined,
        onRefresh: () => undefined,
        onRefreshOperatorEconomy: () => undefined,
        onRefreshOffers: () => undefined,
        onRunContentSummarize: () => undefined,
        onRunPaidContentSummarize: () => undefined,
        onPublishReview: () => undefined,
        onPublishDispute: () => undefined,
        onOfferFeedbackTabChange: () => undefined,
        onLoadOperatorDisputes: () => undefined,
        onReviewDispute: () => undefined,
      }),
    );

    expect(text).toContain("Remote Fased Network origin is unavailable right now.");
    expect(text).toContain("do not treat remote directory or public reachability as healthy");
  });
});

describe("resolveMarketplaceIndexOrderReview", () => {
  it("selects the latest federation order for an indexed offer", () => {
    const entry = {
      kind: "offer",
      handle: "@seller@ff1.fased.app",
      nodeId: "node-seller",
      status: "verified",
      endpoint: "https://seller.example",
      item: {
        id: "content-summarize-v0",
        title: "Content summarize",
        serviceKind: "content.summarize",
      },
      indexedAt: "2026-05-01T00:00:00.000Z",
    } as never;
    const match = resolveMarketplaceIndexOrderReview(entry, [
      {
        source: "local",
        status: "accepted",
        configId: "local-order",
        order: {
          source: "local",
          offerId: "content-summarize-v0",
          updatedAt: "2026-05-01T00:00:00.000Z",
        },
      },
      {
        source: "federation",
        status: "accepted",
        configId: "older-order",
        order: {
          source: "federation",
          offerId: "content-summarize-v0",
          updatedAt: "2026-05-01T00:00:00.000Z",
        },
      },
      {
        source: "federation",
        status: "accepted",
        configId: "newer-order",
        order: {
          source: "federation",
          offerId: "content-summarize-v0",
          updatedAt: "2026-05-02T00:00:00.000Z",
        },
      },
    ] as never);

    expect(match?.configId).toBe("newer-order");
  });

  it("matches indexed requests by request id only", () => {
    const entry = {
      kind: "request",
      handle: "@buyer@ff1.fased.app",
      nodeId: "node-buyer",
      status: "verified",
      endpoint: "https://buyer.example",
      item: {
        id: "data-feed-request-v0",
        title: "Need data feed",
        serviceKind: "data.feed",
      },
      indexedAt: "2026-05-01T00:00:00.000Z",
    } as never;
    const match = resolveMarketplaceIndexOrderReview(entry, [
      {
        source: "federation",
        status: "accepted",
        configId: "wrong-offer-order",
        order: {
          source: "federation",
          offerId: "data-feed-request-v0",
          updatedAt: "2026-05-03T00:00:00.000Z",
        },
      },
      {
        source: "federation",
        status: "draft",
        configId: "request-order",
        order: {
          source: "federation",
          requestId: "data-feed-request-v0",
          updatedAt: "2026-05-02T00:00:00.000Z",
        },
      },
    ] as never);

    expect(match?.configId).toBe("request-order");
  });
});

describe("renderFederation", () => {
  it("uses the primary Agent wallet for Marketplace payment when multiple Agent wallets exist", () => {
    const text = flattenTemplateText(
      renderFederation({
        loading: false,
        error: null,
        message: null,
        directory: [],
        handle: "@fased@example.com",
        nodeEndpoint: "http://127.0.0.1:18789",
        token: null,
        status: null,
        managedMode: false,
        adminToken: "",
        reviewReason: "",
        reviewBusyHandle: null,
        localOffers: [],
        localRequests: [],
        localOrders: [
          {
            configId: "order-primary-wallet",
            source: "federation",
            kind: "offer",
            handle: "@mock-summarizer@fased.test",
            status: "draft",
            updatedAt: "2026-04-09T00:00:00.000Z",
            order: {
              id: "order-primary-wallet",
              source: "federation",
              kind: "offer",
              offerId: "https://mock-summarizer.example/offers/content-summarize-v0",
              sellerHandle: "@mock-summarizer@fased.test",
              serviceKind: "content.summarize",
              status: "draft",
              pricing: { amount: 0.1, currency: "SOL", unit: "per-job" },
              paymentIntent: {
                status: "requires_payment",
                method: "agent-wallet",
                amount: 0.1,
                currency: "SOL",
                chain: "solana",
                assetKind: "native",
                assetDecimals: 9,
                acceptedAssets: ["SOL"],
                payeeAddress: "SellerSolana1111111111111111111111111111111",
              },
              delivery: { status: "pending", targetKind: "app-inbox" },
              createdAt: "2026-04-09T00:00:00.000Z",
              updatedAt: "2026-04-09T00:00:00.000Z",
            },
          },
        ] as never,
        localOffersLoading: false,
        localRequestsLoading: false,
        localOrdersLoading: false,
        localOffersError: null,
        localRequestsError: null,
        localOrdersError: null,
        localOffersMessage: null,
        localOfferBusy: false,
        localOrderBusy: false,
        localOfferDraftOpen: false,
        localOfferEditingId: null,
        localOfferEnabledDraft: true,
        localOfferTitleDraft: "",
        localOfferSummaryDraft: "",
        localOfferServiceKindDraft: "",
        localOfferInputShapeDraft: "",
        localOfferDeliveryShapeDraft: "",
        localOfferCapabilitiesDraft: "",
        offersLoading: false,
        offersError: null,
        offers: [],
        offersQuery: "",
        offersServiceKindFilter: "",
        marketplaceSection: "purchases",
        marketplaceIndexEntries: [
          {
            id: "index-content-summary",
            kind: "offer",
            handle: "@mock-summarizer@fased.test",
            endpoint: "https://mock-summarizer.example",
            item: {
              id: "https://mock-summarizer.example/offers/content-summarize-v0",
              title: "Content summary",
              serviceKind: "content.summarize",
              pricing: { amount: 0.1, currency: "SOL", unit: "per-job" },
            },
          },
        ] as never,
        marketplaceIndexSelectedEntryId:
          "offer:@mock-summarizer@fased.test:https://mock-summarizer.example/offers/content-summarize-v0",
        marketplaceIndexDetailTab: "overview",
        selectedOfferId: "",
        offerReviewsLoading: false,
        offerReviewsError: null,
        offerReviews: [],
        offerDisputesLoading: false,
        offerDisputesError: null,
        offerDisputes: [],
        offerFeedbackBusy: false,
        offerFeedbackError: null,
        offerFeedbackMessage: null,
        offerFeedbackTab: "review",
        summarizeSourceText: "Summarize this Marketplace order.",
        summarizeStyle: "bullets",
        summarizeMaxSentences: "2",
        summarizeBusy: false,
        summarizeError: null,
        paidSummarizeBusy: false,
        paidSummarizeError: null,
        summarizeResult: null,
        paidQuoteAmountDraft: "0.1",
        paidQuoteAssetDecimalsDraft: "9",
        paidQuoteCurrencyDraft: "SOL",
        paidQuoteChainDraft: "solana",
        paidQuoteAssetKindDraft: "native",
        paidQuoteAssetAddressDraft: "",
        paidQuotePayeeAddressDraft: "",
        paidQuoteExpiresMinutesDraft: "5",
        reviewRatingDraft: "5",
        reviewOutcomeDraft: "satisfied",
        reviewPaymentStatusDraft: "unpaid",
        reviewInvoiceIdDraft: "",
        reviewReceiptIdDraft: "",
        reviewSummaryDraft: "",
        disputeReasonCodeDraft: "delivery_mismatch",
        disputePaymentStatusDraft: "unpaid",
        disputeInvoiceIdDraft: "",
        disputeReceiptIdDraft: "",
        disputeSummaryDraft: "",
        operatorDisputesLoading: false,
        operatorDisputesError: null,
        operatorDisputes: [],
        operatorDisputeProviderFilter: "",
        operatorDisputeOfferIdFilter: "",
        operatorDisputeStatusFilter: "all",
        operatorDisputePaymentStatusFilter: "all",
        operatorSelectedCaseId: "",
        operatorDisputeReviewStatusDraft: "under_review",
        operatorDisputeResolutionDraft: "",
        operatorDisputeReviewBusy: false,
        operatorDisputeReviewError: null,
        operatorDisputeReviewMessage: null,
        walletStatus: null,
        walletNamedWallets: multiAgentWallets as never,
        defaultWalletId: "agent-primary",
        miningAttachedWalletId: "wallet-mining",
        miningProfile: { walletId: "wallet-mining" } as never,
        miningReadiness: null,
        miningStatus: null,
        onOpenAdminControl: () => undefined,
        onOpenTaskPayment: () => undefined,
        onOpenMining: () => undefined,
        onOpenFederationReview: () => undefined,
        onHandleChange: () => undefined,
        onNodeEndpointChange: () => undefined,
        onAdminTokenChange: () => undefined,
        onReviewReasonChange: () => undefined,
        onRefreshLocalOffers: () => undefined,
        onStartLocalOfferDraft: () => undefined,
        onCancelLocalOfferDraft: () => undefined,
        onLocalOfferEnabledDraftChange: () => undefined,
        onLocalOfferTitleDraftChange: () => undefined,
        onLocalOfferSummaryDraftChange: () => undefined,
        onLocalOfferServiceKindDraftChange: () => undefined,
        onLocalOfferInputShapeDraftChange: () => undefined,
        onLocalOfferDeliveryShapeDraftChange: () => undefined,
        onLocalOfferCapabilitiesDraftChange: () => undefined,
        onSaveLocalOffer: () => undefined,
        onToggleLocalOffer: () => undefined,
        onDeleteLocalOffer: () => undefined,
        onOffersQueryChange: () => undefined,
        onOffersServiceKindFilterChange: () => undefined,
        onSelectOffer: () => undefined,
        onLoadOfferReputation: () => undefined,
        onSummarizeSourceTextChange: () => undefined,
        onSummarizeStyleChange: () => undefined,
        onSummarizeMaxSentencesChange: () => undefined,
        onPaidQuoteAmountDraftChange: () => undefined,
        onPaidQuoteAssetDecimalsDraftChange: () => undefined,
        onPaidQuoteCurrencyDraftChange: () => undefined,
        onPaidQuoteChainDraftChange: () => undefined,
        onPaidQuoteAssetKindDraftChange: () => undefined,
        onPaidQuoteAssetAddressDraftChange: () => undefined,
        onPaidQuotePayeeAddressDraftChange: () => undefined,
        onPaidQuoteExpiresMinutesDraftChange: () => undefined,
        onReviewRatingDraftChange: () => undefined,
        onReviewOutcomeDraftChange: () => undefined,
        onReviewPaymentStatusDraftChange: () => undefined,
        onReviewInvoiceIdDraftChange: () => undefined,
        onReviewReceiptIdDraftChange: () => undefined,
        onReviewSummaryDraftChange: () => undefined,
        onDisputeReasonCodeDraftChange: () => undefined,
        onDisputePaymentStatusDraftChange: () => undefined,
        onDisputeInvoiceIdDraftChange: () => undefined,
        onDisputeReceiptIdDraftChange: () => undefined,
        onDisputeSummaryDraftChange: () => undefined,
        onOperatorDisputeProviderFilterChange: () => undefined,
        onOperatorDisputeOfferIdFilterChange: () => undefined,
        onOperatorDisputeStatusFilterChange: () => undefined,
        onOperatorDisputePaymentStatusFilterChange: () => undefined,
        onOperatorSelectedCaseIdChange: () => undefined,
        onOperatorDisputeReviewStatusDraftChange: () => undefined,
        onOperatorDisputeResolutionDraftChange: () => undefined,
        onRegister: () => undefined,
        onAttest: () => undefined,
        onRenew: () => undefined,
        onRevoke: () => undefined,
        onReview: () => undefined,
        onRefresh: () => undefined,
        onRefreshOffers: () => undefined,
        onRunContentSummarize: () => undefined,
        onRunPaidContentSummarize: () => undefined,
        onRunPaidContentSummarizeOrder: () => undefined,
        onPublishReview: () => undefined,
        onPublishDispute: () => undefined,
        onOfferFeedbackTabChange: () => undefined,
        onLoadOperatorDisputes: () => undefined,
        onReviewDispute: () => undefined,
      }),
    );

    expect(text).toContain("Primary Agent");
    expect(text).not.toContain("Agent 2");
    expect(text).not.toContain("Mining Wallet buyer wallet");
  });

  it("renders the federation screen without blanking when optional branches use nothing", () => {
    const text = flattenTemplateText(
      renderFederation({
        loading: false,
        error: null,
        message: null,
        directory: [],
        handle: "@fased@example.com",
        nodeEndpoint: "http://127.0.0.1:18789",
        token: {
          handle: "@fased@example.com",
          trustState: "pending",
          hostedState: "disabled",
          expiresAt: "2026-05-01T00:00:00.000Z",
          paidFlowEligible: false,
        } as never,
        status: null,
        managedMode: false,
        adminToken: "",
        reviewReason: "",
        reviewBusyHandle: null,
        localOffers: [],
        localOffersLoading: false,
        localOffersError: null,
        localOffersMessage: null,
        localOfferBusy: false,
        localOfferDraftOpen: false,
        localOfferEditingId: null,
        localOfferEnabledDraft: true,
        localOfferTitleDraft: "",
        localOfferSummaryDraft: "",
        localOfferServiceKindDraft: "",
        localOfferInputShapeDraft: "",
        localOfferDeliveryShapeDraft: "",
        localOfferCapabilitiesDraft: "",
        offersLoading: false,
        offersError: null,
        offers: marketplaceOffers as never,
        offersQuery: "",
        offersServiceKindFilter: "content.summarize",
        selectedOfferId: "https://mock-summarizer.example/offers/content-summarize-v0",
        offerReviewsLoading: false,
        offerReviewsError: null,
        offerReviews: [],
        offerDisputesLoading: false,
        offerDisputesError: null,
        offerDisputes: [],
        offerFeedbackBusy: false,
        offerFeedbackError: null,
        offerFeedbackMessage: null,
        offerFeedbackTab: "review",
        summarizeSourceText: "Summarize this marketplace result.",
        summarizeStyle: "bullets",
        summarizeMaxSentences: "2",
        summarizeBusy: false,
        summarizeError: null,
        paidSummarizeBusy: false,
        paidSummarizeError: null,
        summarizeResult: null,
        paidQuoteAmountDraft: "1.25",
        paidQuoteAssetDecimalsDraft: "6",
        paidQuoteCurrencyDraft: "USDC",
        paidQuoteChainDraft: "solana",
        paidQuoteAssetKindDraft: "spl-token",
        paidQuoteAssetAddressDraft: "So11111111111111111111111111111111111111112",
        paidQuotePayeeAddressDraft: "So11111111111111111111111111111111111111112",
        paidQuoteExpiresMinutesDraft: "5",
        reviewRatingDraft: "5",
        reviewOutcomeDraft: "satisfied",
        reviewPaymentStatusDraft: "unpaid",
        reviewInvoiceIdDraft: "",
        reviewReceiptIdDraft: "",
        reviewSummaryDraft: "",
        disputeReasonCodeDraft: "delivery_mismatch",
        disputePaymentStatusDraft: "unpaid",
        disputeInvoiceIdDraft: "",
        disputeReceiptIdDraft: "",
        disputeSummaryDraft: "",
        operatorDisputesLoading: false,
        operatorDisputesError: null,
        operatorDisputes: [
          {
            schema: "https://domain.com/schemas/fased-dispute-v0.json",
            caseId: "case-1",
            taskId: "task-1",
            offerId: "https://mock-summarizer.example/offers/content-summarize-v0",
            reporterHandle: "@buyer@fased.test",
            providerHandle: "@mock-summarizer@fased.test",
            paymentStatus: "pending",
            reasonCode: "delivery_mismatch",
            summary: "Formatting mismatch",
            evidenceRefs: [
              "invoice:invoice-queue-1",
              "receipt:receipt-queue-1",
              "result:task-1",
              "artifact:fased://marketplace/orders/order-1/content-summarize/task-1",
              "artifact:https://buyer.example/secret-token",
            ],
            status: "open",
            createdAt: "2026-04-09T12:00:00.000Z",
            updatedAt: "2026-04-09T12:00:00.000Z",
          },
        ] as never,
        operatorDisputeProviderFilter: "",
        operatorDisputeOfferIdFilter: "",
        operatorDisputeStatusFilter: "open",
        operatorDisputePaymentStatusFilter: "all",
        operatorSelectedCaseId: "case-1",
        operatorDisputeReviewStatusDraft: "under_review",
        operatorDisputeResolutionDraft: "",
        operatorDisputeReviewBusy: false,
        operatorDisputeReviewError: null,
        operatorDisputeReviewMessage: null,
        disputeNotaryRecordsLoading: false,
        disputeNotaryRecordsError: null,
        disputeNotaryRecords: [
          {
            schema: "https://domain.com/schemas/fased-dispute-notary-v0.json",
            caseId: "case-1",
            notaryHandle: "@operator-notary@fased.test",
            bondTier: "operator-bond",
            opinion: "supports-claim",
            summary: "Evidence supports the claim.",
            evidenceRefs: ["invoice:invoice-queue-1", "result:task-1"],
            decisionConfidence: "high",
            recommendedResolution: "resolved",
            createdAt: "2026-04-09T12:05:00.000Z",
          },
        ],
        disputeNotaryOpinionDraft: "supports-claim",
        disputeNotaryConfidenceDraft: "high",
        disputeNotaryRecommendedResolutionDraft: "resolved",
        disputeNotarySummaryDraft: "Evidence supports the claim.",
        disputeNotaryBusy: false,
        disputeNotaryError: null,
        disputeNotaryMessage: null,
        walletStatus: {
          approvalAuth: {
            mode: "none",
            ready: false,
            passkeyCount: 0,
            notes: [],
            passkeys: [],
            statePath: "/tmp/passkeys.json",
          },
        } as never,
        walletNamedWallets,
        defaultWalletId: "wallet-payment",
        miningAttachedWalletId: "wallet-mining",
        miningProfile: { walletId: "wallet-mining" } as never,
        miningReadiness: null,
        miningStatus: null,
        onOpenAdminControl: () => undefined,
        onOpenTaskPayment: () => undefined,
        onOpenMining: () => undefined,
        onOpenFederationReview: () => undefined,
        onHandleChange: () => undefined,
        onNodeEndpointChange: () => undefined,
        onAdminTokenChange: () => undefined,
        onReviewReasonChange: () => undefined,
        onRefreshLocalOffers: () => undefined,
        onStartLocalOfferDraft: () => undefined,
        onCancelLocalOfferDraft: () => undefined,
        onLocalOfferEnabledDraftChange: () => undefined,
        onLocalOfferTitleDraftChange: () => undefined,
        onLocalOfferSummaryDraftChange: () => undefined,
        onLocalOfferServiceKindDraftChange: () => undefined,
        onLocalOfferInputShapeDraftChange: () => undefined,
        onLocalOfferDeliveryShapeDraftChange: () => undefined,
        onLocalOfferCapabilitiesDraftChange: () => undefined,
        onSaveLocalOffer: () => undefined,
        onToggleLocalOffer: () => undefined,
        onDeleteLocalOffer: () => undefined,
        onOffersQueryChange: () => undefined,
        onOffersServiceKindFilterChange: () => undefined,
        onSelectOffer: () => undefined,
        onLoadOfferReputation: () => undefined,
        onSummarizeSourceTextChange: () => undefined,
        onSummarizeStyleChange: () => undefined,
        onSummarizeMaxSentencesChange: () => undefined,
        onPaidQuoteAmountDraftChange: () => undefined,
        onPaidQuoteAssetDecimalsDraftChange: () => undefined,
        onPaidQuoteCurrencyDraftChange: () => undefined,
        onPaidQuoteChainDraftChange: () => undefined,
        onPaidQuoteAssetKindDraftChange: () => undefined,
        onPaidQuoteAssetAddressDraftChange: () => undefined,
        onPaidQuotePayeeAddressDraftChange: () => undefined,
        onPaidQuoteExpiresMinutesDraftChange: () => undefined,
        onReviewRatingDraftChange: () => undefined,
        onReviewOutcomeDraftChange: () => undefined,
        onReviewPaymentStatusDraftChange: () => undefined,
        onReviewInvoiceIdDraftChange: () => undefined,
        onReviewReceiptIdDraftChange: () => undefined,
        onReviewSummaryDraftChange: () => undefined,
        onDisputeReasonCodeDraftChange: () => undefined,
        onDisputePaymentStatusDraftChange: () => undefined,
        onDisputeInvoiceIdDraftChange: () => undefined,
        onDisputeReceiptIdDraftChange: () => undefined,
        onDisputeSummaryDraftChange: () => undefined,
        onOperatorDisputeProviderFilterChange: () => undefined,
        onOperatorDisputeOfferIdFilterChange: () => undefined,
        onOperatorDisputeStatusFilterChange: () => undefined,
        onOperatorDisputePaymentStatusFilterChange: () => undefined,
        onOperatorSelectedCaseIdChange: () => undefined,
        onOperatorDisputeReviewStatusDraftChange: () => undefined,
        onOperatorDisputeResolutionDraftChange: () => undefined,
        onDisputeNotaryOpinionDraftChange: () => undefined,
        onDisputeNotaryConfidenceDraftChange: () => undefined,
        onDisputeNotaryRecommendedResolutionDraftChange: () => undefined,
        onDisputeNotarySummaryDraftChange: () => undefined,
        onRegister: () => undefined,
        onAttest: () => undefined,
        onRenew: () => undefined,
        onRevoke: () => undefined,
        onReview: () => undefined,
        onRefresh: () => undefined,
        onRefreshOffers: () => undefined,
        onRunContentSummarize: () => undefined,
        onRunPaidContentSummarize: () => undefined,
        onPublishReview: () => undefined,
        onPublishDispute: () => undefined,
        onOfferFeedbackTabChange: () => undefined,
        onLoadOperatorDisputes: () => undefined,
        onReviewDispute: () => undefined,
        onLoadDisputeNotaryAttestations: () => undefined,
        onPublishDisputeNotaryAttestation: () => undefined,
      }),
    );

    expect(text).toContain("Fased Network");
    expect(text).toContain("Marketplace");
    expect(text).toContain("Debug: unpaid raw run");
    expect(text).toContain("Pay content summary");
    expect(text).toContain("Seller settlement");
    expect(text).toContain("API access");
    expect(text).toContain("Invoice handling");
    expect(text).toContain("Market research");
    expect(text).toContain("Recent Reviews");
    expect(text).toContain("Recent Disputes");
    expect(text).toContain("Operator Dispute Review");
    expect(text).toContain("Evidence refs");
    expect(text).toContain("invoice:invoice-queue-1");
    expect(text).toContain("artifact:fased://marketplace/orders/order-1/content-summarize/task-1");
    expect(text).toContain("Use refs in resolution");
    expect(text).toContain("Notary opinion");
    expect(text).toContain("@operator-notary@fased.test");
    expect(text).toContain("supports-claim");
    expect(text).toContain("Publish notary opinion");
    expect(text).not.toContain("secret-token");
    expect(text).not.toContain("Operator Readiness");
    expect(text).not.toContain("Register handle");
    expect(text).not.toContain("Attest + join");
  });

  it("shows broken hosted reachability and unreachable marketplace hints", () => {
    const text = flattenTemplateText(
      renderFederation({
        loading: false,
        error: null,
        message: null,
        directory: [
          {
            handle: "@seller@ff1.fased.app",
            status: "verified",
            version: "0.1.0",
            endpoint: "https://seller.agents.fased.app",
            lastSeenAt: "2026-04-10T15:00:00.000Z",
          },
        ] as never,
        handle: "@seller@ff1.fased.app",
        nodeEndpoint: "http://127.0.0.1:18789",
        token: {
          handle: "@seller@ff1.fased.app",
          trustState: "verified",
          hostedState: "ready",
          publicUrl: "https://seller.agents.fased.app",
          expiresAt: "2026-05-01T00:00:00.000Z",
          paidFlowEligible: true,
        } as never,
        status: {
          managed: true,
          sourcePath: "/tmp/access-token.json",
          joined: true,
          lifecycle: "active",
          checkedAt: "2026-04-10T15:00:00.000Z",
          token: {
            handle: "@seller@ff1.fased.app",
            trustState: "verified",
            hostedState: "ready",
            publicUrl: "https://seller.agents.fased.app",
            expiresAt: "2026-05-01T00:00:00.000Z",
            paidFlowEligible: true,
          },
          hostedProbe: {
            state: "broken",
            checkedAt: "2026-04-10T15:00:01.000Z",
            publicUrl: "https://seller.agents.fased.app",
            agentCardUrl: "https://seller.agents.fased.app/.well-known/agent.json",
            statusCode: 404,
            reason: "public share not found",
          },
        } as never,
        managedMode: true,
        adminToken: "",
        reviewReason: "",
        reviewBusyHandle: null,
        localOffers: [],
        localOffersLoading: false,
        localOffersError: null,
        localOffersMessage: null,
        localOfferBusy: false,
        localOfferDraftOpen: false,
        localOfferEditingId: null,
        localOfferEnabledDraft: true,
        localOfferTitleDraft: "",
        localOfferSummaryDraft: "",
        localOfferServiceKindDraft: "",
        localOfferInputShapeDraft: "",
        localOfferDeliveryShapeDraft: "",
        localOfferCapabilitiesDraft: "",
        offersLoading: false,
        offersError: null,
        offersHint:
          "Public offer endpoint unreachable for @seller@ff1.fased.app. public share not found",
        offers: [],
        offersQuery: "",
        offersServiceKindFilter: "content.summarize",
        selectedOfferId: "",
        offerReviewsLoading: false,
        offerReviewsError: null,
        offerReviews: [],
        offerDisputesLoading: false,
        offerDisputesError: null,
        offerDisputes: [],
        offerFeedbackBusy: false,
        offerFeedbackError: null,
        offerFeedbackMessage: null,
        offerFeedbackTab: "review",
        summarizeSourceText: "",
        summarizeStyle: "bullets",
        summarizeMaxSentences: "2",
        summarizeBusy: false,
        summarizeError: null,
        paidSummarizeBusy: false,
        paidSummarizeError: null,
        summarizeResult: null,
        paidQuoteAmountDraft: "1",
        paidQuoteAssetDecimalsDraft: "6",
        paidQuoteCurrencyDraft: "USDC",
        paidQuoteChainDraft: "solana",
        paidQuoteAssetKindDraft: "spl-token",
        paidQuoteAssetAddressDraft: "",
        paidQuotePayeeAddressDraft: "",
        paidQuoteExpiresMinutesDraft: "5",
        reviewRatingDraft: "5",
        reviewOutcomeDraft: "satisfied",
        reviewPaymentStatusDraft: "unpaid",
        reviewInvoiceIdDraft: "",
        reviewReceiptIdDraft: "",
        reviewSummaryDraft: "",
        disputeReasonCodeDraft: "other",
        disputePaymentStatusDraft: "unpaid",
        disputeInvoiceIdDraft: "",
        disputeReceiptIdDraft: "",
        disputeSummaryDraft: "",
        operatorDisputesLoading: false,
        operatorDisputesError: null,
        operatorDisputes: [],
        operatorDisputeProviderFilter: "",
        operatorDisputeOfferIdFilter: "",
        operatorDisputeStatusFilter: "all",
        operatorDisputePaymentStatusFilter: "all",
        operatorSelectedCaseId: "",
        operatorDisputeReviewStatusDraft: "under_review",
        operatorDisputeResolutionDraft: "",
        operatorDisputeReviewBusy: false,
        operatorDisputeReviewError: null,
        operatorDisputeReviewMessage: null,
        walletStatus: null,
        walletNamedWallets,
        defaultWalletId: null,
        miningAttachedWalletId: null,
        miningProfile: null,
        miningReadiness: null,
        miningStatus: null,
        onOpenAdminControl: () => undefined,
        onOpenTaskPayment: () => undefined,
        onOpenMining: () => undefined,
        onOpenFederationReview: () => undefined,
        onHandleChange: () => undefined,
        onNodeEndpointChange: () => undefined,
        onAdminTokenChange: () => undefined,
        onReviewReasonChange: () => undefined,
        onRefreshLocalOffers: () => undefined,
        onStartLocalOfferDraft: () => undefined,
        onCancelLocalOfferDraft: () => undefined,
        onLocalOfferEnabledDraftChange: () => undefined,
        onLocalOfferTitleDraftChange: () => undefined,
        onLocalOfferSummaryDraftChange: () => undefined,
        onLocalOfferServiceKindDraftChange: () => undefined,
        onLocalOfferInputShapeDraftChange: () => undefined,
        onLocalOfferDeliveryShapeDraftChange: () => undefined,
        onLocalOfferCapabilitiesDraftChange: () => undefined,
        onSaveLocalOffer: () => undefined,
        onToggleLocalOffer: () => undefined,
        onDeleteLocalOffer: () => undefined,
        onOffersQueryChange: () => undefined,
        onOffersServiceKindFilterChange: () => undefined,
        onSelectOffer: () => undefined,
        onLoadOfferReputation: () => undefined,
        onSummarizeSourceTextChange: () => undefined,
        onSummarizeStyleChange: () => undefined,
        onSummarizeMaxSentencesChange: () => undefined,
        onPaidQuoteAmountDraftChange: () => undefined,
        onPaidQuoteAssetDecimalsDraftChange: () => undefined,
        onPaidQuoteCurrencyDraftChange: () => undefined,
        onPaidQuoteChainDraftChange: () => undefined,
        onPaidQuoteAssetKindDraftChange: () => undefined,
        onPaidQuoteAssetAddressDraftChange: () => undefined,
        onPaidQuotePayeeAddressDraftChange: () => undefined,
        onPaidQuoteExpiresMinutesDraftChange: () => undefined,
        onReviewRatingDraftChange: () => undefined,
        onReviewOutcomeDraftChange: () => undefined,
        onReviewPaymentStatusDraftChange: () => undefined,
        onReviewInvoiceIdDraftChange: () => undefined,
        onReviewReceiptIdDraftChange: () => undefined,
        onReviewSummaryDraftChange: () => undefined,
        onDisputeReasonCodeDraftChange: () => undefined,
        onDisputePaymentStatusDraftChange: () => undefined,
        onDisputeInvoiceIdDraftChange: () => undefined,
        onDisputeReceiptIdDraftChange: () => undefined,
        onDisputeSummaryDraftChange: () => undefined,
        onOperatorDisputeProviderFilterChange: () => undefined,
        onOperatorDisputeOfferIdFilterChange: () => undefined,
        onOperatorDisputeStatusFilterChange: () => undefined,
        onOperatorDisputePaymentStatusFilterChange: () => undefined,
        onOperatorSelectedCaseIdChange: () => undefined,
        onOperatorDisputeReviewStatusDraftChange: () => undefined,
        onOperatorDisputeResolutionDraftChange: () => undefined,
        onRegister: () => undefined,
        onAttest: () => undefined,
        onRenew: () => undefined,
        onRevoke: () => undefined,
        onReview: () => undefined,
        onRefresh: () => undefined,
        onRefreshOffers: () => undefined,
        onRunContentSummarize: () => undefined,
        onRunPaidContentSummarize: () => undefined,
        onPublishReview: () => undefined,
        onPublishDispute: () => undefined,
        onOfferFeedbackTabChange: () => undefined,
        onLoadOperatorDisputes: () => undefined,
        onReviewDispute: () => undefined,
      }),
    );

    expect(text).toContain("Public reachability has a problem right now.");
    expect(text).toContain("Public offer endpoint unreachable");
    expect(text).not.toContain("Hosted public URL is broken right now: public share not found");
  });

  it("suppresses stale summarize errors once a successful result is available and promotes feedback next steps", () => {
    const text = flattenTemplateText(
      renderFederation({
        loading: false,
        error: null,
        message: null,
        directory: [],
        handle: "@buyer@ff1.fased.app",
        nodeEndpoint: "http://127.0.0.1:18789",
        token: {
          handle: "@buyer@ff1.fased.app",
          trustState: "verified",
          hostedState: "ready",
          expiresAt: "2026-05-01T00:00:00.000Z",
          paidFlowEligible: true,
        } as never,
        status: null,
        managedMode: false,
        adminToken: "",
        reviewReason: "",
        reviewBusyHandle: null,
        localOffers: [],
        localOffersLoading: false,
        localOffersError: null,
        localOffersMessage: null,
        localOfferBusy: false,
        localOfferDraftOpen: false,
        localOfferEditingId: null,
        localOfferEnabledDraft: true,
        localOfferTitleDraft: "",
        localOfferSummaryDraft: "",
        localOfferServiceKindDraft: "",
        localOfferInputShapeDraft: "",
        localOfferDeliveryShapeDraft: "",
        localOfferCapabilitiesDraft: "",
        offersLoading: false,
        offersError: null,
        offers: marketplaceOffers as never,
        offersQuery: "",
        offersServiceKindFilter: "content.summarize",
        selectedOfferId: "https://mock-summarizer.example/offers/content-summarize-v0",
        offerReviewsLoading: false,
        offerReviewsError: null,
        offerReviews: [],
        offerDisputesLoading: false,
        offerDisputesError: null,
        offerDisputes: [],
        offerFeedbackBusy: false,
        offerFeedbackError: null,
        offerFeedbackMessage: null,
        offerFeedbackTab: "review",
        summarizeSourceText:
          "Fased federation marketplace can complete a paid summarize run across two verified agents.",
        summarizeStyle: "bullets",
        summarizeMaxSentences: "2",
        summarizeBusy: false,
        summarizeError: "stale unpaid error",
        paidSummarizeBusy: false,
        paidSummarizeError: "stale paid error",
        summarizeResult: {
          status: "accepted",
          taskId: "task-success-1",
          handle: "@mock-summarizer@fased.test",
          offerId: "https://mock-summarizer.example/offers/content-summarize-v0",
          snapshot: {
            taskId: "task-success-1",
            status: "succeeded",
            output: {
              result: {
                kind: "content.summarize.v0",
                summaryText: "- one\n- two",
              },
              payment: {
                status: "verified",
                invoiceId: "invoice-1",
                receiptId: "receipt-1",
                txRef: "tx-1",
              },
            },
          },
        } as never,
        paidQuoteAmountDraft: "0.01",
        paidQuoteAssetDecimalsDraft: "9",
        paidQuoteCurrencyDraft: "SOL",
        paidQuoteChainDraft: "solana",
        paidQuoteAssetKindDraft: "native",
        paidQuoteAssetAddressDraft: "",
        paidQuotePayeeAddressDraft: "3XPiZeWcRTxnBV8EwxFRhHwVbextPayEtRFbfyUtmVMU",
        paidQuoteExpiresMinutesDraft: "5",
        reviewRatingDraft: "5",
        reviewOutcomeDraft: "satisfied",
        reviewPaymentStatusDraft: "verified",
        reviewInvoiceIdDraft: "invoice-1",
        reviewReceiptIdDraft: "receipt-1",
        reviewSummaryDraft: "",
        disputeReasonCodeDraft: "delivery_mismatch",
        disputePaymentStatusDraft: "verified",
        disputeInvoiceIdDraft: "invoice-1",
        disputeReceiptIdDraft: "receipt-1",
        disputeSummaryDraft: "",
        operatorDisputesLoading: false,
        operatorDisputesError: null,
        operatorDisputes: [],
        operatorDisputeProviderFilter: "",
        operatorDisputeOfferIdFilter: "",
        operatorDisputeStatusFilter: "all",
        operatorDisputePaymentStatusFilter: "all",
        operatorSelectedCaseId: "",
        operatorDisputeReviewStatusDraft: "under_review",
        operatorDisputeResolutionDraft: "",
        operatorDisputeReviewBusy: false,
        operatorDisputeReviewError: null,
        operatorDisputeReviewMessage: null,
        walletStatus: {
          approvalAuth: {
            mode: "none",
            ready: false,
            passkeyCount: 0,
            notes: [],
            passkeys: [],
            statePath: "/tmp/passkeys.json",
          },
        } as never,
        walletNamedWallets,
        defaultWalletId: "wallet-payment",
        miningAttachedWalletId: "wallet-mining",
        miningProfile: { walletId: "wallet-mining" } as never,
        miningReadiness: null,
        miningStatus: null,
        onOpenAdminControl: () => undefined,
        onOpenTaskPayment: () => undefined,
        onOpenMining: () => undefined,
        onOpenFederationReview: () => undefined,
        onHandleChange: () => undefined,
        onNodeEndpointChange: () => undefined,
        onAdminTokenChange: () => undefined,
        onReviewReasonChange: () => undefined,
        onRefreshLocalOffers: () => undefined,
        onStartLocalOfferDraft: () => undefined,
        onCancelLocalOfferDraft: () => undefined,
        onLocalOfferEnabledDraftChange: () => undefined,
        onLocalOfferTitleDraftChange: () => undefined,
        onLocalOfferSummaryDraftChange: () => undefined,
        onLocalOfferServiceKindDraftChange: () => undefined,
        onLocalOfferInputShapeDraftChange: () => undefined,
        onLocalOfferDeliveryShapeDraftChange: () => undefined,
        onLocalOfferCapabilitiesDraftChange: () => undefined,
        onSaveLocalOffer: () => undefined,
        onToggleLocalOffer: () => undefined,
        onDeleteLocalOffer: () => undefined,
        onOffersQueryChange: () => undefined,
        onOffersServiceKindFilterChange: () => undefined,
        onSelectOffer: () => undefined,
        onLoadOfferReputation: () => undefined,
        onSummarizeSourceTextChange: () => undefined,
        onSummarizeStyleChange: () => undefined,
        onSummarizeMaxSentencesChange: () => undefined,
        onPaidQuoteAmountDraftChange: () => undefined,
        onPaidQuoteAssetDecimalsDraftChange: () => undefined,
        onPaidQuoteCurrencyDraftChange: () => undefined,
        onPaidQuoteChainDraftChange: () => undefined,
        onPaidQuoteAssetKindDraftChange: () => undefined,
        onPaidQuoteAssetAddressDraftChange: () => undefined,
        onPaidQuotePayeeAddressDraftChange: () => undefined,
        onPaidQuoteExpiresMinutesDraftChange: () => undefined,
        onReviewRatingDraftChange: () => undefined,
        onReviewOutcomeDraftChange: () => undefined,
        onReviewPaymentStatusDraftChange: () => undefined,
        onReviewInvoiceIdDraftChange: () => undefined,
        onReviewReceiptIdDraftChange: () => undefined,
        onReviewSummaryDraftChange: () => undefined,
        onDisputeReasonCodeDraftChange: () => undefined,
        onDisputePaymentStatusDraftChange: () => undefined,
        onDisputeInvoiceIdDraftChange: () => undefined,
        onDisputeReceiptIdDraftChange: () => undefined,
        onDisputeSummaryDraftChange: () => undefined,
        onOperatorDisputeProviderFilterChange: () => undefined,
        onOperatorDisputeOfferIdFilterChange: () => undefined,
        onOperatorDisputeStatusFilterChange: () => undefined,
        onOperatorDisputePaymentStatusFilterChange: () => undefined,
        onOperatorSelectedCaseIdChange: () => undefined,
        onOperatorDisputeReviewStatusDraftChange: () => undefined,
        onOperatorDisputeResolutionDraftChange: () => undefined,
        onRegister: () => undefined,
        onAttest: () => undefined,
        onRenew: () => undefined,
        onRevoke: () => undefined,
        onReview: () => undefined,
        onRefresh: () => undefined,
        onRefreshOffers: () => undefined,
        onRunContentSummarize: () => undefined,
        onRunPaidContentSummarize: () => undefined,
        onPublishReview: () => undefined,
        onPublishDispute: () => undefined,
        onOfferFeedbackTabChange: () => undefined,
        onLoadOperatorDisputes: () => undefined,
        onReviewDispute: () => undefined,
      }),
    );

    expect(text).toContain("Summary Result");
    expect(text).toContain("Review or Dispute");
    expect(text).toContain("Invoice");
    expect(text).toContain("Receipt");
    expect(text).not.toContain("stale unpaid error");
    expect(text).not.toContain("stale paid error");
  });

  it("hides stale local unverified registry entries by default", () => {
    const text = flattenTemplateText(
      renderFederation({
        loading: false,
        error: null,
        message: null,
        directory: [
          {
            handle: "@old-loopback@ff1.fased.app",
            status: "unverified",
            version: "2026.2.15",
            endpoint: "http://127.0.0.1:18789",
            lastSeenAt: "2026-02-16T16:01:42.868Z",
          },
        ] as never,
        handle: "",
        nodeEndpoint: "http://127.0.0.1:18789",
        token: {
          handle: "@fased@example.com",
          trustState: "verified",
          hostedState: "ready",
          expiresAt: "2026-05-01T00:00:00.000Z",
          paidFlowEligible: true,
        } as never,
        status: null,
        managedMode: false,
        adminToken: "",
        reviewReason: "",
        reviewBusyHandle: null,
        localOffers: [],
        localOffersLoading: false,
        localOffersError: null,
        localOffersMessage: null,
        localOfferBusy: false,
        localOfferDraftOpen: false,
        localOfferEditingId: null,
        localOfferEnabledDraft: true,
        localOfferTitleDraft: "",
        localOfferSummaryDraft: "",
        localOfferServiceKindDraft: "",
        localOfferInputShapeDraft: "",
        localOfferDeliveryShapeDraft: "",
        localOfferCapabilitiesDraft: "",
        offersLoading: false,
        offersError: null,
        offers: [],
        offersQuery: "",
        offersServiceKindFilter: "all",
        selectedOfferId: "",
        offerReviewsLoading: false,
        offerReviewsError: null,
        offerReviews: [],
        offerDisputesLoading: false,
        offerDisputesError: null,
        offerDisputes: [],
        offerFeedbackBusy: false,
        offerFeedbackError: null,
        offerFeedbackMessage: null,
        offerFeedbackTab: "review",
        summarizeSourceText: "",
        summarizeStyle: "bullets",
        summarizeMaxSentences: "2",
        summarizeBusy: false,
        summarizeError: null,
        paidSummarizeBusy: false,
        paidSummarizeError: null,
        summarizeResult: null,
        paidQuoteAmountDraft: "1",
        paidQuoteAssetDecimalsDraft: "6",
        paidQuoteCurrencyDraft: "USDC",
        paidQuoteChainDraft: "solana",
        paidQuoteAssetKindDraft: "spl-token",
        paidQuoteAssetAddressDraft: "",
        paidQuotePayeeAddressDraft: "",
        paidQuoteExpiresMinutesDraft: "5",
        reviewRatingDraft: "5",
        reviewOutcomeDraft: "satisfied",
        reviewPaymentStatusDraft: "unpaid",
        reviewInvoiceIdDraft: "",
        reviewReceiptIdDraft: "",
        reviewSummaryDraft: "",
        disputeReasonCodeDraft: "other",
        disputePaymentStatusDraft: "unpaid",
        disputeInvoiceIdDraft: "",
        disputeReceiptIdDraft: "",
        disputeSummaryDraft: "",
        operatorDisputesLoading: false,
        operatorDisputesError: null,
        operatorDisputes: [],
        operatorDisputeProviderFilter: "",
        operatorDisputeOfferIdFilter: "",
        operatorDisputeStatusFilter: "all",
        operatorDisputePaymentStatusFilter: "all",
        operatorSelectedCaseId: "",
        operatorDisputeReviewStatusDraft: "under_review",
        operatorDisputeResolutionDraft: "",
        operatorDisputeReviewBusy: false,
        operatorDisputeReviewError: null,
        operatorDisputeReviewMessage: null,
        walletStatus: null,
        walletNamedWallets,
        defaultWalletId: null,
        miningAttachedWalletId: null,
        miningProfile: null,
        miningReadiness: null,
        miningStatus: null,
        onOpenAdminControl: () => undefined,
        onOpenTaskPayment: () => undefined,
        onOpenMining: () => undefined,
        onOpenFederationReview: () => undefined,
        onHandleChange: () => undefined,
        onNodeEndpointChange: () => undefined,
        onAdminTokenChange: () => undefined,
        onReviewReasonChange: () => undefined,
        onRefreshLocalOffers: () => undefined,
        onStartLocalOfferDraft: () => undefined,
        onCancelLocalOfferDraft: () => undefined,
        onLocalOfferEnabledDraftChange: () => undefined,
        onLocalOfferTitleDraftChange: () => undefined,
        onLocalOfferSummaryDraftChange: () => undefined,
        onLocalOfferServiceKindDraftChange: () => undefined,
        onLocalOfferInputShapeDraftChange: () => undefined,
        onLocalOfferDeliveryShapeDraftChange: () => undefined,
        onLocalOfferCapabilitiesDraftChange: () => undefined,
        onSaveLocalOffer: () => undefined,
        onToggleLocalOffer: () => undefined,
        onDeleteLocalOffer: () => undefined,
        onOffersQueryChange: () => undefined,
        onOffersServiceKindFilterChange: () => undefined,
        onSelectOffer: () => undefined,
        onLoadOfferReputation: () => undefined,
        onSummarizeSourceTextChange: () => undefined,
        onSummarizeStyleChange: () => undefined,
        onSummarizeMaxSentencesChange: () => undefined,
        onPaidQuoteAmountDraftChange: () => undefined,
        onPaidQuoteAssetDecimalsDraftChange: () => undefined,
        onPaidQuoteCurrencyDraftChange: () => undefined,
        onPaidQuoteChainDraftChange: () => undefined,
        onPaidQuoteAssetKindDraftChange: () => undefined,
        onPaidQuoteAssetAddressDraftChange: () => undefined,
        onPaidQuotePayeeAddressDraftChange: () => undefined,
        onPaidQuoteExpiresMinutesDraftChange: () => undefined,
        onReviewRatingDraftChange: () => undefined,
        onReviewOutcomeDraftChange: () => undefined,
        onReviewPaymentStatusDraftChange: () => undefined,
        onReviewInvoiceIdDraftChange: () => undefined,
        onReviewReceiptIdDraftChange: () => undefined,
        onReviewSummaryDraftChange: () => undefined,
        onDisputeReasonCodeDraftChange: () => undefined,
        onDisputePaymentStatusDraftChange: () => undefined,
        onDisputeInvoiceIdDraftChange: () => undefined,
        onDisputeReceiptIdDraftChange: () => undefined,
        onDisputeSummaryDraftChange: () => undefined,
        onOperatorDisputeProviderFilterChange: () => undefined,
        onOperatorDisputeOfferIdFilterChange: () => undefined,
        onOperatorDisputeStatusFilterChange: () => undefined,
        onOperatorDisputePaymentStatusFilterChange: () => undefined,
        onOperatorSelectedCaseIdChange: () => undefined,
        onOperatorDisputeReviewStatusDraftChange: () => undefined,
        onOperatorDisputeResolutionDraftChange: () => undefined,
        onRegister: () => undefined,
        onAttest: () => undefined,
        onRenew: () => undefined,
        onRevoke: () => undefined,
        onReview: () => undefined,
        onRefresh: () => undefined,
        onRefreshOffers: () => undefined,
        onRunContentSummarize: () => undefined,
        onRunPaidContentSummarize: () => undefined,
        onPublishReview: () => undefined,
        onPublishDispute: () => undefined,
        onOfferFeedbackTabChange: () => undefined,
        onLoadOperatorDisputes: () => undefined,
        onReviewDispute: () => undefined,
      }),
    );

    expect(text).not.toContain("@old-loopback@ff1.fased.app");
  });
});
