FROM docker.io/rockylinux/rockylinux:9

ENV container=podman

RUN dnf install -y \
    acl \
    ca-certificates \
    findutils \
    gawk \
    git \
    grep \
    iproute \
    jq \
    openssl \
    procps-ng \
    shadow-utils \
    sudo \
    systemd \
    tar \
    util-linux \
  && dnf clean all \
  && systemctl mask \
    dev-hugepages.mount \
    sys-fs-fuse-connections.mount \
    systemd-remount-fs.service

COPY updater-request.mjs /usr/local/bin/fased-hosting-updater-request
RUN chmod 0755 /usr/local/bin/fased-hosting-updater-request

STOPSIGNAL SIGRTMIN+3
CMD ["/usr/lib/systemd/systemd"]
