import type { LogLevel } from "./types.ts";
import type { CronFormState } from "./ui-types.ts";

export const DEFAULT_LOG_LEVEL_FILTERS: Record<LogLevel, boolean> = {
  trace: true,
  debug: true,
  info: true,
  warn: true,
  error: true,
  fatal: true,
};

export const DEFAULT_CRON_FORM: CronFormState = {
  name: "",
  description: "",
  agentId: "",
  sessionKey: "",
  clearAgent: false,
  enabled: true,
  deleteAfterRun: true,
  scheduleKind: "every",
  scheduleAt: "",
  everyAmount: "30",
  everyUnit: "minutes",
  cronExpr: "0 7 * * *",
  cronTz: "",
  scheduleExact: false,
  staggerAmount: "",
  staggerUnit: "seconds",
  sessionTarget: "isolated",
  wakeMode: "now",
  taskObjective: "",
  taskSuccessCriteria: "",
  executionMode: "auto",
  memoryScope: "session-summary",
  skillScope: "agent-default",
  allowedSkills: "",
  skillToolName: "",
  skillToolInputJson: "",
  plannerStrategy: "",
  modelRole: "",
  policyModel: "",
  escalationModel: "",
  coordinationMode: "none",
  coordinationAgents: "",
  coordinationMaxAgents: "",
  coordinationRequireApproval: true,
  evaluatorEscalateOnSignal: true,
  evaluatorSignalIncludes: "Needs deeper analysis: yes",
  evaluatorMaxEscalations: "1",
  repairAutoRetryReplacement: true,
  repairAutoStopOptionalSources: false,
  repairMaxAutoRepairsPerRun: "1",
  repairRequireApprovalForPrimarySource: true,
  budgetMaxTokensPerRun: "",
  budgetMaxCostUsdPerRun: "",
  budgetMaxRunsPerHour: "",
  stopOnSuccess: false,
  stopTextIncludes: "",
  stopMaxSuccessfulRuns: "",
  stopMaxTotalRuns: "",
  payloadKind: "agentTurn",
  payloadText: "",
  payloadModel: "",
  payloadThinking: "",
  payloadLightContext: false,
  deliveryMode: "announce",
  deliveryChannel: "last",
  deliveryTo: "",
  deliveryAccountId: "",
  deliveryBestEffort: false,
  failureAlertMode: "inherit",
  failureAlertAfter: "2",
  failureAlertCooldownSeconds: "3600",
  failureAlertChannel: "last",
  failureAlertTo: "",
  failureAlertDeliveryMode: "announce",
  failureAlertAccountId: "",
  timeoutSeconds: "",
};
