// Wire values mirrored from token/sat/api/src/instruction.rs and consts.rs.
// Keep all TypeScript protocol consumers on this single contract and run the
// sibling-source drift test whenever the SAT protocol repository is present.
export const SAT_INSTRUCTION_DISCRIMINATORS = {
  bootstrap: 34,
  initializeCycle: 38,
  finalizeEpoch: 43,
  openRound: 44,
  submitValidatorAttestation: 45,
  openDispute: 46,
  claim: 47,
  resolveDispute: 48,
  republishEpochRoots: 49,
  submitParticipation: 52,
  initMinerCapital: 36,
  depositMinerCapital: 37,
  openCycle: 56,
  submitCycle: 57,
  claimCycleRewards: 59,
  retargetUnlock: 60,
  claimCycleRewardsBatch: 62,
  settleCyclePage: 63,
  finalizeCycleSettlement: 64,
  scoreCyclePage: 65,
  distributeCyclePage: 66,
  withdrawMinerCapital: 67,
  setActiveCommit: 68,
  closeResolvedMinerCycleState: 69,
  closeResolvedCycleRegistryPage: 70,
  closeResolvedCycleArtifacts: 71,
  compactPendingCycleRange: 75,
  setProtocolRecipients: 76,
  claimProtocolTreasury: 77,
  openBondPosition: 79,
  increaseBondPosition: 80,
  requestBondUnlock: 81,
  cancelBondUnlock: 82,
  finalizeBondUnlock: 83,
  claimProtocolDistributorSat: 85,
  refillRegistryReserveFromTreasury: 88,
  miningCrank: 33,
} as const;

export const SAT_BOND_INSTRUCTION_DISCRIMINATORS = {
  initTierPolicy: 0,
  updateTierPolicy: 1,
  openBondPosition: 2,
  increaseBondPosition: 3,
  requestBondUnlock: 4,
  cancelBondUnlock: 5,
  finalizeBondUnlock: 6,
  initStakingDistributor: 7,
  syncStakingRewards: 8,
  syncStakingPosition: 9,
  claimStakingRewards: 10,
} as const;

export const SAT_PROTOCOL_CONSTANTS = {
  allocationBuckets: 25,
  cycleSeconds: 300,
  cycleErosionPpm: 83n,
  minimumEntryLamports: 250_000_000,
  registryReserveTargetLamports: 200_000_000n,
} as const;
