import type { TSchema } from "@sinclair/typebox";
import {
  AgentEventSchema,
  AgentIdentityParamsSchema,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  AgentWaitParamsSchema,
  PollParamsSchema,
  SendParamsSchema,
  WakeParamsSchema,
} from "./agent.js";
import {
  AgentSummarySchema,
  AgentsCreateParamsSchema,
  AgentsCreateResultSchema,
  AgentsDeleteParamsSchema,
  AgentsDeleteResultSchema,
  AgentsFileEntrySchema,
  AgentsFilesGetParamsSchema,
  AgentsFilesGetResultSchema,
  AgentsFilesListParamsSchema,
  AgentsFilesListResultSchema,
  AgentsFilesSetParamsSchema,
  AgentsFilesSetResultSchema,
  AgentsListParamsSchema,
  AgentsListResultSchema,
  AgentsUpdateParamsSchema,
  AgentsUpdateResultSchema,
  ModelChoiceSchema,
  ModelsAuthClearParamsSchema,
  ModelsAuthClearResultSchema,
  ModelsAuthConfigureParamsSchema,
  ModelsAuthConfigureResultSchema,
  ModelsAuthInteractiveStartParamsSchema,
  ModelsAuthInteractiveStartResultSchema,
  ModelsAuthStatusEffectiveSchema,
  ModelsAuthStatusParamsSchema,
  ModelsAuthStatusProfileSchema,
  ModelsAuthStatusProviderSchema,
  ModelsAuthStatusResultSchema,
  ModelsAuthStoreModeSchema,
  ModelsAuthStoreParamsSchema,
  ModelsAuthStoreResultSchema,
  ModelsCatalogStatusParamsSchema,
  ModelsCatalogStatusProviderSchema,
  ModelsCatalogStatusResultSchema,
  ModelsListParamsSchema,
  ModelsListResultSchema,
  PluginsMarketplaceInfoParamsSchema,
  PluginsMarketplaceInfoResultSchema,
  PluginsMarketplaceInstallParamsSchema,
  PluginsMarketplaceListParamsSchema,
  PluginsMarketplaceListResultSchema,
  PluginsMarketplaceAdminRpcGrantSetParamsSchema,
  PluginsMarketplaceRestartParamsSchema,
  PluginsMarketplaceRuntimeHelperSetParamsSchema,
  PluginsMarketplaceUninstallParamsSchema,
  PluginsMarketplaceUpdatePreviewParamsSchema,
  PluginsMarketplaceUpdateParamsSchema,
  PluginMarketplaceActionSchema,
  PluginMarketplaceAdminRpcActionGrantStatusSchema,
  PluginMarketplaceAdminRpcActionMethodSchema,
  PluginMarketplaceAdminRpcActionsSchema,
  PluginMarketplaceChannelCatalogMetaSchema,
  PluginMarketplaceDiagnosticSchema,
  PluginMarketplaceEntrySchema,
  PluginMarketplaceInstallChoiceSchema,
  PluginMarketplaceInstallOptionsSchema,
  PluginMarketplaceInstallRecordSchema,
  PluginMarketplacePermissionDiffSchema,
  PluginMarketplaceRuntimeHelpersSchema,
  PluginMarketplaceMutationActionSchema,
  PluginMarketplaceMutationResultSchema,
  PluginMarketplaceSourceTrustSchema,
  PluginMarketplaceUpdatePreviewResultSchema,
  PluginMarketplaceUpdateReviewSchema,
  SkillsBinsParamsSchema,
  SkillsBinsResultSchema,
  SkillsCopyParamsSchema,
  SkillsCopyResultSchema,
  SkillsCreateParamsSchema,
  SkillsCreateResultSchema,
  SkillsDetailParamsSchema,
  SkillsDetailResultSchema,
  SkillsFileGetParamsSchema,
  SkillsFileGetResultSchema,
  SkillsFileSetParamsSchema,
  SkillsFileSetResultSchema,
  SkillsInstallParamsSchema,
  SkillsMarketplaceInstallPreviewParamsSchema,
  SkillsMarketplaceInstallPreviewResultSchema,
  SkillsMarketplaceInstallParamsSchema,
  SkillsMarketplaceInstallResultSchema,
  SkillsMarketplaceUpdateParamsSchema,
  SkillsMarketplaceUpdatePreviewParamsSchema,
  SkillsMarketplaceUpdatePreviewResultSchema,
  SkillsMarketplaceUpdateResultSchema,
  SkillsSearchParamsSchema,
  SkillsSearchResultSchema,
  SkillsStatusParamsSchema,
  SkillsUpdateParamsSchema,
  SkillsWalletGrantClearParamsSchema,
  SkillsWalletGrantClearResultSchema,
  SkillsWalletGrantsParamsSchema,
  SkillsWalletGrantsResultSchema,
  SkillsWalletGrantSetParamsSchema,
  SkillsWalletGrantSetResultSchema,
  ToolCatalogEntrySchema,
  ToolCatalogGroupSchema,
  ToolCatalogProfileSchema,
  ToolEffectiveEntrySchema,
  ToolEffectiveGroupSchema,
  ToolEffectiveSourceSchema,
  ToolsCatalogParamsSchema,
  ToolsCatalogResultSchema,
  ToolsEffectiveParamsSchema,
  ToolsEffectiveResultSchema,
} from "./agents-models-skills.js";
import {
  ChannelsLogoutParamsSchema,
  ChannelsRuntimeControlParamsSchema,
  ChannelsRuntimeControlResultSchema,
  TalkConfigParamsSchema,
  TalkConfigResultSchema,
  ChannelsStatusParamsSchema,
  ChannelsStatusResultSchema,
  TalkModeParamsSchema,
  WebLoginStartParamsSchema,
  WebLoginWaitParamsSchema,
} from "./channels.js";
import {
  CommandArgChoiceSchema,
  CommandArgSchema,
  CommandCategorySchema,
  CommandEntrySchema,
  CommandsListParamsSchema,
  CommandsListResultSchema,
  CommandScopeSchema,
  CommandSourceSchema,
} from "./commands.js";
import {
  ConfigApplyParamsSchema,
  ConfigGetParamsSchema,
  ConfigPatchParamsSchema,
  ConfigSchemaLookupParamsSchema,
  ConfigSchemaLookupResultSchema,
  ConfigSchemaParamsSchema,
  ConfigSchemaResponseSchema,
  ConfigSetParamsSchema,
  UpdateRunParamsSchema,
  UpdateStatusParamsSchema,
} from "./config.js";
import {
  CronAddParamsSchema,
  CronJobSchema,
  CronListParamsSchema,
  CronRepairParamsSchema,
  CronRemoveParamsSchema,
  CronQueueControlParamsSchema,
  CronRunDetailParamsSchema,
  CronRunLogEntrySchema,
  CronRunParamsSchema,
  CronRunsParamsSchema,
  CronSourcesListParamsSchema,
  CronSourcesRemoveParamsSchema,
  CronSourcesUpdateParamsSchema,
  CronStatusParamsSchema,
  CronUpdateParamsSchema,
} from "./cron.js";
import {
  DevicePairApproveParamsSchema,
  DevicePairListParamsSchema,
  DevicePairRemoveParamsSchema,
  DevicePairRejectParamsSchema,
  DevicePairRequestedEventSchema,
  DevicePairResolvedEventSchema,
  DeviceTokenRevokeParamsSchema,
  DeviceTokenRotateParamsSchema,
} from "./devices.js";
import {
  ExecApprovalsGetParamsSchema,
  ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSetParamsSchema,
  ExecApprovalsSnapshotSchema,
  ExecApprovalGetParamsSchema,
  ExecApprovalListParamsSchema,
  ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParamsSchema,
} from "./exec-approvals.js";
import {
  ConnectParamsSchema,
  ErrorShapeSchema,
  EventFrameSchema,
  GatewayFrameSchema,
  HelloOkSchema,
  RequestFrameSchema,
  ResponseFrameSchema,
  ShutdownEventSchema,
  TickEventSchema,
} from "./frames.js";
import {
  ChatAbortParamsSchema,
  ChatEventSchema,
  ChatHistoryParamsSchema,
  ChatInjectParamsSchema,
  ChatSendParamsSchema,
  LogsTailParamsSchema,
  LogsTailResultSchema,
} from "./logs-chat.js";
import {
  NodeDescribeParamsSchema,
  NodeEventParamsSchema,
  NodeInvokeParamsSchema,
  NodeInvokeResultParamsSchema,
  NodeInvokeRequestEventSchema,
  NodeListParamsSchema,
  NodePendingAckParamsSchema,
  NodePendingDrainParamsSchema,
  NodePendingEnqueueParamsSchema,
  NodePendingPullParamsSchema,
  NodePairApproveParamsSchema,
  NodePairListParamsSchema,
  NodePairRejectParamsSchema,
  NodePairRemoveParamsSchema,
  NodePairRequestParamsSchema,
  NodePairVerifyParamsSchema,
  NodeRenameParamsSchema,
} from "./nodes.js";
import { PushTestParamsSchema, PushTestResultSchema } from "./push.js";
import {
  SessionCompactionCheckpointReasonSchema,
  SessionCompactionCheckpointSchema,
  SessionCompactionTranscriptReferenceSchema,
  SessionsCompactParamsSchema,
  SessionsCompactionBranchParamsSchema,
  SessionsCompactionGetParamsSchema,
  SessionsCompactionListParamsSchema,
  SessionsCompactionRestoreParamsSchema,
  SessionsDeleteParamsSchema,
  SessionsListParamsSchema,
  SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPreviewParamsSchema,
  SessionsResetParamsSchema,
  SessionsResolveParamsSchema,
  SessionsUsageParamsSchema,
} from "./sessions.js";
import { PresenceEntrySchema, SnapshotSchema, StateVersionSchema } from "./snapshot.js";
import {
  WizardCancelParamsSchema,
  WizardNextParamsSchema,
  WizardNextResultSchema,
  WizardStartParamsSchema,
  WizardStartResultSchema,
  WizardStatusParamsSchema,
  WizardStatusResultSchema,
  WizardStepSchema,
} from "./wizard.js";

export const ProtocolSchemas: Record<string, TSchema> = {
  ConnectParams: ConnectParamsSchema,
  HelloOk: HelloOkSchema,
  RequestFrame: RequestFrameSchema,
  ResponseFrame: ResponseFrameSchema,
  EventFrame: EventFrameSchema,
  GatewayFrame: GatewayFrameSchema,
  PresenceEntry: PresenceEntrySchema,
  StateVersion: StateVersionSchema,
  Snapshot: SnapshotSchema,
  ErrorShape: ErrorShapeSchema,
  AgentEvent: AgentEventSchema,
  SendParams: SendParamsSchema,
  PollParams: PollParamsSchema,
  AgentParams: AgentParamsSchema,
  AgentIdentityParams: AgentIdentityParamsSchema,
  AgentIdentityResult: AgentIdentityResultSchema,
  AgentWaitParams: AgentWaitParamsSchema,
  WakeParams: WakeParamsSchema,
  NodePairRequestParams: NodePairRequestParamsSchema,
  NodePairListParams: NodePairListParamsSchema,
  NodePairApproveParams: NodePairApproveParamsSchema,
  NodePairRejectParams: NodePairRejectParamsSchema,
  NodePairRemoveParams: NodePairRemoveParamsSchema,
  NodePairVerifyParams: NodePairVerifyParamsSchema,
  NodeRenameParams: NodeRenameParamsSchema,
  NodeListParams: NodeListParamsSchema,
  NodeDescribeParams: NodeDescribeParamsSchema,
  NodePendingDrainParams: NodePendingDrainParamsSchema,
  NodePendingPullParams: NodePendingPullParamsSchema,
  NodePendingAckParams: NodePendingAckParamsSchema,
  NodePendingEnqueueParams: NodePendingEnqueueParamsSchema,
  NodeInvokeParams: NodeInvokeParamsSchema,
  NodeInvokeResultParams: NodeInvokeResultParamsSchema,
  NodeEventParams: NodeEventParamsSchema,
  NodeInvokeRequestEvent: NodeInvokeRequestEventSchema,
  PushTestParams: PushTestParamsSchema,
  PushTestResult: PushTestResultSchema,
  SessionsListParams: SessionsListParamsSchema,
  SessionsMessagesSubscribeParams: SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParams: SessionsMessagesUnsubscribeParamsSchema,
  SessionsPreviewParams: SessionsPreviewParamsSchema,
  SessionsResolveParams: SessionsResolveParamsSchema,
  SessionsPatchParams: SessionsPatchParamsSchema,
  SessionsResetParams: SessionsResetParamsSchema,
  SessionsDeleteParams: SessionsDeleteParamsSchema,
  SessionsCompactParams: SessionsCompactParamsSchema,
  SessionCompactionCheckpointReason: SessionCompactionCheckpointReasonSchema,
  SessionCompactionTranscriptReference: SessionCompactionTranscriptReferenceSchema,
  SessionCompactionCheckpoint: SessionCompactionCheckpointSchema,
  SessionsCompactionListParams: SessionsCompactionListParamsSchema,
  SessionsCompactionGetParams: SessionsCompactionGetParamsSchema,
  SessionsCompactionBranchParams: SessionsCompactionBranchParamsSchema,
  SessionsCompactionRestoreParams: SessionsCompactionRestoreParamsSchema,
  SessionsUsageParams: SessionsUsageParamsSchema,
  ConfigGetParams: ConfigGetParamsSchema,
  ConfigSetParams: ConfigSetParamsSchema,
  ConfigApplyParams: ConfigApplyParamsSchema,
  ConfigPatchParams: ConfigPatchParamsSchema,
  ConfigSchemaParams: ConfigSchemaParamsSchema,
  ConfigSchemaLookupParams: ConfigSchemaLookupParamsSchema,
  ConfigSchemaLookupResult: ConfigSchemaLookupResultSchema,
  ConfigSchemaResponse: ConfigSchemaResponseSchema,
  CommandSource: CommandSourceSchema,
  CommandScope: CommandScopeSchema,
  CommandCategory: CommandCategorySchema,
  CommandArgChoice: CommandArgChoiceSchema,
  CommandArg: CommandArgSchema,
  CommandEntry: CommandEntrySchema,
  CommandsListParams: CommandsListParamsSchema,
  CommandsListResult: CommandsListResultSchema,
  WizardStartParams: WizardStartParamsSchema,
  WizardNextParams: WizardNextParamsSchema,
  WizardCancelParams: WizardCancelParamsSchema,
  WizardStatusParams: WizardStatusParamsSchema,
  WizardStep: WizardStepSchema,
  WizardNextResult: WizardNextResultSchema,
  WizardStartResult: WizardStartResultSchema,
  WizardStatusResult: WizardStatusResultSchema,
  TalkModeParams: TalkModeParamsSchema,
  TalkConfigParams: TalkConfigParamsSchema,
  TalkConfigResult: TalkConfigResultSchema,
  ChannelsStatusParams: ChannelsStatusParamsSchema,
  ChannelsStatusResult: ChannelsStatusResultSchema,
  ChannelsLogoutParams: ChannelsLogoutParamsSchema,
  ChannelsRuntimeControlParams: ChannelsRuntimeControlParamsSchema,
  ChannelsRuntimeControlResult: ChannelsRuntimeControlResultSchema,
  WebLoginStartParams: WebLoginStartParamsSchema,
  WebLoginWaitParams: WebLoginWaitParamsSchema,
  AgentSummary: AgentSummarySchema,
  AgentsCreateParams: AgentsCreateParamsSchema,
  AgentsCreateResult: AgentsCreateResultSchema,
  AgentsUpdateParams: AgentsUpdateParamsSchema,
  AgentsUpdateResult: AgentsUpdateResultSchema,
  AgentsDeleteParams: AgentsDeleteParamsSchema,
  AgentsDeleteResult: AgentsDeleteResultSchema,
  AgentsFileEntry: AgentsFileEntrySchema,
  AgentsFilesListParams: AgentsFilesListParamsSchema,
  AgentsFilesListResult: AgentsFilesListResultSchema,
  AgentsFilesGetParams: AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: AgentsFilesGetResultSchema,
  AgentsFilesSetParams: AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: AgentsFilesSetResultSchema,
  AgentsListParams: AgentsListParamsSchema,
  AgentsListResult: AgentsListResultSchema,
  ModelChoice: ModelChoiceSchema,
  ModelsAuthStoreMode: ModelsAuthStoreModeSchema,
  ModelsAuthStoreParams: ModelsAuthStoreParamsSchema,
  ModelsAuthStoreResult: ModelsAuthStoreResultSchema,
  ModelsAuthConfigureParams: ModelsAuthConfigureParamsSchema,
  ModelsAuthConfigureResult: ModelsAuthConfigureResultSchema,
  ModelsAuthClearParams: ModelsAuthClearParamsSchema,
  ModelsAuthClearResult: ModelsAuthClearResultSchema,
  ModelsAuthInteractiveStartParams: ModelsAuthInteractiveStartParamsSchema,
  ModelsAuthInteractiveStartResult: ModelsAuthInteractiveStartResultSchema,
  ModelsAuthStatusParams: ModelsAuthStatusParamsSchema,
  ModelsAuthStatusResult: ModelsAuthStatusResultSchema,
  ModelsAuthStatusProvider: ModelsAuthStatusProviderSchema,
  ModelsAuthStatusProfile: ModelsAuthStatusProfileSchema,
  ModelsAuthStatusEffective: ModelsAuthStatusEffectiveSchema,
  ModelsCatalogStatusParams: ModelsCatalogStatusParamsSchema,
  ModelsCatalogStatusProvider: ModelsCatalogStatusProviderSchema,
  ModelsCatalogStatusResult: ModelsCatalogStatusResultSchema,
  ModelsListParams: ModelsListParamsSchema,
  ModelsListResult: ModelsListResultSchema,
  PluginMarketplaceAction: PluginMarketplaceActionSchema,
  PluginMarketplaceMutationAction: PluginMarketplaceMutationActionSchema,
  PluginMarketplaceAdminRpcActionMethod: PluginMarketplaceAdminRpcActionMethodSchema,
  PluginMarketplaceAdminRpcActionGrantStatus: PluginMarketplaceAdminRpcActionGrantStatusSchema,
  PluginMarketplaceAdminRpcActions: PluginMarketplaceAdminRpcActionsSchema,
  PluginMarketplaceInstallRecord: PluginMarketplaceInstallRecordSchema,
  PluginMarketplaceInstallChoice: PluginMarketplaceInstallChoiceSchema,
  PluginMarketplaceInstallOptions: PluginMarketplaceInstallOptionsSchema,
  PluginMarketplaceChannelCatalogMeta: PluginMarketplaceChannelCatalogMetaSchema,
  PluginMarketplaceRuntimeHelpers: PluginMarketplaceRuntimeHelpersSchema,
  PluginMarketplaceSourceTrust: PluginMarketplaceSourceTrustSchema,
  PluginMarketplacePermissionDiff: PluginMarketplacePermissionDiffSchema,
  PluginMarketplaceUpdateReview: PluginMarketplaceUpdateReviewSchema,
  PluginMarketplaceDiagnostic: PluginMarketplaceDiagnosticSchema,
  PluginMarketplaceEntry: PluginMarketplaceEntrySchema,
  PluginsMarketplaceListParams: PluginsMarketplaceListParamsSchema,
  PluginsMarketplaceListResult: PluginsMarketplaceListResultSchema,
  PluginsMarketplaceInfoParams: PluginsMarketplaceInfoParamsSchema,
  PluginsMarketplaceInfoResult: PluginsMarketplaceInfoResultSchema,
  PluginsMarketplaceInstallParams: PluginsMarketplaceInstallParamsSchema,
  PluginsMarketplaceAdminRpcGrantSetParams: PluginsMarketplaceAdminRpcGrantSetParamsSchema,
  PluginsMarketplaceRestartParams: PluginsMarketplaceRestartParamsSchema,
  PluginsMarketplaceRuntimeHelperSetParams: PluginsMarketplaceRuntimeHelperSetParamsSchema,
  PluginsMarketplaceUpdateParams: PluginsMarketplaceUpdateParamsSchema,
  PluginsMarketplaceUpdatePreviewParams: PluginsMarketplaceUpdatePreviewParamsSchema,
  PluginsMarketplaceUninstallParams: PluginsMarketplaceUninstallParamsSchema,
  PluginMarketplaceMutationResult: PluginMarketplaceMutationResultSchema,
  PluginMarketplaceUpdatePreviewResult: PluginMarketplaceUpdatePreviewResultSchema,
  SkillsStatusParams: SkillsStatusParamsSchema,
  ToolsCatalogParams: ToolsCatalogParamsSchema,
  ToolCatalogProfile: ToolCatalogProfileSchema,
  ToolCatalogEntry: ToolCatalogEntrySchema,
  ToolCatalogGroup: ToolCatalogGroupSchema,
  ToolsCatalogResult: ToolsCatalogResultSchema,
  ToolsEffectiveParams: ToolsEffectiveParamsSchema,
  ToolEffectiveSource: ToolEffectiveSourceSchema,
  ToolEffectiveEntry: ToolEffectiveEntrySchema,
  ToolEffectiveGroup: ToolEffectiveGroupSchema,
  ToolsEffectiveResult: ToolsEffectiveResultSchema,
  SkillsBinsParams: SkillsBinsParamsSchema,
  SkillsBinsResult: SkillsBinsResultSchema,
  SkillsCopyParams: SkillsCopyParamsSchema,
  SkillsCopyResult: SkillsCopyResultSchema,
  SkillsCreateParams: SkillsCreateParamsSchema,
  SkillsCreateResult: SkillsCreateResultSchema,
  SkillsSearchParams: SkillsSearchParamsSchema,
  SkillsSearchResult: SkillsSearchResultSchema,
  SkillsDetailParams: SkillsDetailParamsSchema,
  SkillsDetailResult: SkillsDetailResultSchema,
  SkillsFileGetParams: SkillsFileGetParamsSchema,
  SkillsFileGetResult: SkillsFileGetResultSchema,
  SkillsFileSetParams: SkillsFileSetParamsSchema,
  SkillsFileSetResult: SkillsFileSetResultSchema,
  SkillsMarketplaceInstallPreviewParams: SkillsMarketplaceInstallPreviewParamsSchema,
  SkillsMarketplaceInstallPreviewResult: SkillsMarketplaceInstallPreviewResultSchema,
  SkillsMarketplaceInstallParams: SkillsMarketplaceInstallParamsSchema,
  SkillsMarketplaceInstallResult: SkillsMarketplaceInstallResultSchema,
  SkillsMarketplaceUpdatePreviewParams: SkillsMarketplaceUpdatePreviewParamsSchema,
  SkillsMarketplaceUpdatePreviewResult: SkillsMarketplaceUpdatePreviewResultSchema,
  SkillsMarketplaceUpdateParams: SkillsMarketplaceUpdateParamsSchema,
  SkillsMarketplaceUpdateResult: SkillsMarketplaceUpdateResultSchema,
  SkillsWalletGrantsParams: SkillsWalletGrantsParamsSchema,
  SkillsWalletGrantsResult: SkillsWalletGrantsResultSchema,
  SkillsWalletGrantSetParams: SkillsWalletGrantSetParamsSchema,
  SkillsWalletGrantSetResult: SkillsWalletGrantSetResultSchema,
  SkillsWalletGrantClearParams: SkillsWalletGrantClearParamsSchema,
  SkillsWalletGrantClearResult: SkillsWalletGrantClearResultSchema,
  SkillsInstallParams: SkillsInstallParamsSchema,
  SkillsUpdateParams: SkillsUpdateParamsSchema,
  CronJob: CronJobSchema,
  CronListParams: CronListParamsSchema,
  CronStatusParams: CronStatusParamsSchema,
  CronAddParams: CronAddParamsSchema,
  CronUpdateParams: CronUpdateParamsSchema,
  CronRepairParams: CronRepairParamsSchema,
  CronRemoveParams: CronRemoveParamsSchema,
  CronQueueControlParams: CronQueueControlParamsSchema,
  CronRunDetailParams: CronRunDetailParamsSchema,
  CronRunParams: CronRunParamsSchema,
  CronRunsParams: CronRunsParamsSchema,
  CronSourcesListParams: CronSourcesListParamsSchema,
  CronSourcesUpdateParams: CronSourcesUpdateParamsSchema,
  CronSourcesRemoveParams: CronSourcesRemoveParamsSchema,
  CronRunLogEntry: CronRunLogEntrySchema,
  LogsTailParams: LogsTailParamsSchema,
  LogsTailResult: LogsTailResultSchema,
  ExecApprovalsGetParams: ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParams: ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: ExecApprovalsSnapshotSchema,
  ExecApprovalGetParams: ExecApprovalGetParamsSchema,
  ExecApprovalListParams: ExecApprovalListParamsSchema,
  ExecApprovalRequestParams: ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParams: ExecApprovalResolveParamsSchema,
  DevicePairListParams: DevicePairListParamsSchema,
  DevicePairApproveParams: DevicePairApproveParamsSchema,
  DevicePairRejectParams: DevicePairRejectParamsSchema,
  DevicePairRemoveParams: DevicePairRemoveParamsSchema,
  DeviceTokenRotateParams: DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: DeviceTokenRevokeParamsSchema,
  DevicePairRequestedEvent: DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: DevicePairResolvedEventSchema,
  ChatHistoryParams: ChatHistoryParamsSchema,
  ChatSendParams: ChatSendParamsSchema,
  ChatAbortParams: ChatAbortParamsSchema,
  ChatInjectParams: ChatInjectParamsSchema,
  ChatEvent: ChatEventSchema,
  UpdateRunParams: UpdateRunParamsSchema,
  UpdateStatusParams: UpdateStatusParamsSchema,
  TickEvent: TickEventSchema,
  ShutdownEvent: ShutdownEventSchema,
};

export const PROTOCOL_VERSION = 3 as const;
