packages:
  - .
  - ui
  - extensions/*

autoInstallPeers: false
injectWorkspacePackages: true
forceLegacyDeploy: true

onlyBuiltDependencies:
  - "@discordjs/opus"
  - "@lydell/node-pty"
  - "@matrix-org/matrix-sdk-crypto-nodejs"
  - "@napi-rs/canvas"
  - "@whiskeysockets/baileys"
  - authenticate-pam
  - bufferutil
  - esbuild
  - node-llama-cpp
  - protobufjs
  - sharp
  - utf-8-validate
