import { defineConfig } from "vitest/config";
import baseConfig from "./vitest.config.ts";

const base = baseConfig as unknown as Record<string, unknown>;
const baseTest = (baseConfig as { test?: { include?: string[]; exclude?: string[] } }).test ?? {};
const fastGateSuites = [
  "src/auto-reply/reply/channel-command-control-flow.test.ts",
  "src/auto-reply/skill-commands.test.ts",
  "src/channels/channel-config.test.ts",
  "src/channels/plugins/catalog.test.ts",
  "src/channels/plugins/config-schema.test.ts",
  "src/channels/plugins/onboarding/*.test.ts",
  "src/channels/plugins/plugins-channel.test.ts",
  "src/channels/plugins/plugins-core.test.ts",
  "src/channels/plugins/status-issues/*.test.ts",
  "src/commands/agent/*.test.ts",
  "src/commands/agents.add.test.ts",
  "src/commands/agents.bind.commands.test.ts",
  "src/commands/agents.identity.test.ts",
  "src/commands/channels.add.test.ts",
  "src/commands/channels.adds-non-default-telegram-account.test.ts",
  "src/commands/channels/capabilities.test.ts",
  "src/commands/models.set.test.ts",
  "src/commands/models/list.auth-overview.test.ts",
  "src/commands/models/list.probe.test.ts",
  "src/commands/onboard-channels.test.ts",
  "src/commands/onboard-hooks.test.ts",
  "src/commands/onboard-skills.test.ts",
  "src/agents/skills-install.test.ts",
  "src/agents/skills-install.download.test.ts",
  "src/agents/skills.buildworkspaceskillstatus.test.ts",
  "src/config/config.agent-concurrency-defaults.test.ts",
  "src/config/config.skills-entries-config.test.ts",
  "src/config/config.web-search-provider.test.ts",
  "src/config/io.plugin-allowlist-repair.test.ts",
  "src/config/schema.hints.test.ts",
  "src/config/schema.test.ts",
  "src/cron/deterministic-result-adapters.test.ts",
  "src/cron/isolated-agent/run.skill-filter.test.ts",
  "src/cron/run-detail-format.test.ts",
  "src/cron/run-log.test.ts",
  "src/cron/service.evaluator.test.ts",
  "src/cron/service.needs-access.test.ts",
  "src/cron/service.persists-delivered-status.test.ts",
  "src/cron/task-adaptive-routing.test.ts",
  "src/cron/task-model-roles.test.ts",
  "src/flows/search-setup.test.ts",
  "src/hooks/bundled/session-memory/handler.test.ts",
  "src/hooks/install.test.ts",
  "src/hooks/loader.test.ts",
  "src/memory/internal.test.ts",
  "src/memory/qmd-manager.test.ts",
  "src/memory/session-files.test.ts",
  "src/plugins/enable.test.ts",
  "src/plugins/install.test.ts",
  "src/plugins/registry.web-search.test.ts",
  "src/plugins/uninstall.test.ts",
  "src/plugins/web-search-providers.runtime.test.ts",
  "src/providers/refresh.test.ts",
  "src/providers/registry.test.ts",
  "src/security/audit.test.ts",
  "src/tasks/*.test.ts",
  "src/web-search/runtime.test.ts",
  "src/wallet/chat-command.test.ts",
  "src/wallet/trade-chat-command.test.ts",
  "src/wallet/wallet-agent-selection.test.ts",
  "src/wallet/wallet-provider-resolver.test.ts",
  "src/wallet/wallet-status.test.ts",
];

const include = fastGateSuites;
const exclude = baseTest.exclude ?? [];
const loopbackEnabled = process.env.FASED_TEST_LOOPBACK === "1";

const loopbackOrSocketSuites = [
  "src/browser/cdp.test.ts",
  "src/browser/server*.test.ts",
  "src/canvas-host/server.test.ts",
  "src/infra/ports.test.ts",
  "src/media/server.test.ts",
  "src/wallet/local-socket-signer-broker.test.ts",
  "src/agents/pi-bundle-mcp-tools.materialize.test.ts",
  "src/agents/pi-bundle-mcp-runtime.test.ts",
];

const deferredAgentSyncSuites = [
  "src/agents/acp-spawn*.test.ts",
  "src/agents/apply-patch.test.ts",
  "src/agents/bash-tools.exec-approval-followup.test.ts",
  "src/agents/bash-tools.exec-host-shared.test.ts",
  "src/agents/bash-tools.exec.approval-id.test.ts",
  "src/agents/context.test.ts",
  "src/agents/fast-mode.test.ts",
  "src/agents/fased-tools.subagents*.test.ts",
  "src/agents/google-transport-stream.test.ts",
  "src/agents/live-model-switch.test.ts",
  "src/agents/memory-search.test.ts",
  "src/agents/minimax-docs.test.ts",
  "src/agents/model-compat.test.ts",
  "src/agents/ollama-stream.test.ts",
  "src/agents/openai-transport-stream.test.ts",
  "src/agents/openai-ws-stream.test.ts",
  "src/agents/fased-tools.camera.test.ts",
  "src/agents/fased-tools.session-status.test.ts",
  "src/agents/fased-tools.subagents*.test.ts",
];

export default defineConfig({
  ...base,
  test: {
    ...baseTest,
    include,
    exclude: [
      ...exclude,
      "src/gateway/**",
      "extensions/**",
      ...deferredAgentSyncSuites,
      ...(loopbackEnabled ? [] : loopbackOrSocketSuites),
    ],
  },
});
