// Code generated by scripts/generate-signer-protocol-v2.mjs; DO NOT EDIT.

package main

// signerNativeFeeReservationV2 is the signer-owned upper bound for network
// fees and explicitly validated rent paid by a signer-built transaction.
const signerNativeFeeReservationV2 = uint64(6500000)

var signerV2Capabilities = signerCapabilitiesV2{
	Protocol:                     signerProtocolRangeV2{Current: 2, Min: 2, Max: 2},
	NativeFeeReservationLamports: signerNativeFeeReservationV2,
	IntentTypes: []string{
		"solana.nativeTransfer",
		"solana.splTransferChecked",
		"solana.jupiter.swap",
		"solana.jupiter.trigger.create",
		"solana.jupiter.trigger.cancel",
	},
	OperationStates: []string{
		"reserved",
		"broadcast",
		"confirmed",
		"failed",
		"unknown",
	},
	Features: []string{
		"failClosedPolicies",
		"policyHashes",
		"applicationPolicyTightening",
		"vaultReviewedOnly",
		"durableCaps",
		"atomicMultiAssetCaps",
		"signerControlledNativeFeeCaps",
		"atomicIdempotency",
		"ambiguousBroadcastReconciliation",
		"signerOwnedKeys",
		"liveWalletReadiness",
		"signerOwnedSuccessorRotation",
		"permanentRetiredWalletPolicies",
		"signerOwnedRPC",
		"applicationNetworkBootstrap",
		"signerOwnedRPCProfiles",
		"signerOwnedEncryptedRecovery",
		"signerOwnedRawExport",
		"restrictedOperatorLifecycle",
		"typedSolanaTransactions",
		"typedA2aPaymentMemos",
		"typedA2aRefundMemos",
		"idempotentAssociatedTokenCreation",
		"signerOwnedWebAuthn",
		"signerOwnedWebAuthnCredentialRevocation",
		"singleUseReviewedAuthorization",
		"typedJupiterSemantics",
		"signerOwnedReviewPrepareExecute",
		"exactPreparedTransactions",
		"legacyOnlyJupiterTransactions",
		"preSignedEphemeralPositionMint",
		"signerOwnedStateRecheck",
		"durableReviewAuthorization",
		"signerOwnedJupiterTriggerV2",
		"signerOwnedJupiterTriggerHistory",
		"jupiterTriggerSecretsNeverCrossSocket",
		"jupiterTriggerDurablePhases",
	},
}
