package main

// Code generated from extensions/sat-mining/signer-codec-schema.v1.json.
// Run `pnpm sat:signer-codecs:generate`; DO NOT EDIT.

type signerSATCodecV2 struct {
	Action        string
	Discriminator byte
	DataLength    int
	Family        string
	ContractKey   string
	AccountShape  string
	Variable      string
}

const (
	satFamilyMain = "main"
	satFamilyBond = "bond"
)

const satAccountOrderContractSHA256 = "920119a87256c4f306a744dd6bce64fd0bbb6be2f18a325a5499ac361ef71ddd" // pragma: allowlist secret

var satUnboundLegacyActions = map[string]struct{}{
	"initializeCycle":      {},
	"openDispute":          {},
	"republishEpochRoots":  {},
	"resolveDispute":       {},
	"validatorAttestation": {},
}

var signerSATCodecsV2 = map[string]signerSATCodecV2{
	"initializeCycle": {
		Action:        "initializeCycle",
		Discriminator: 38,
		DataLength:    105,
		Family:        satFamilyMain,
		ContractKey:   "initializeCycle",
		AccountShape:  "SW,-W,-W,--",
		Variable:      "",
	},
	"validatorAttestation": {
		Action:        "validatorAttestation",
		Discriminator: 45,
		DataLength:    161,
		Family:        satFamilyMain,
		ContractKey:   "submitValidatorAttestation",
		AccountShape:  "SW,-W,-W,-W,--",
		Variable:      "",
	},
	"openDispute": {
		Action:        "openDispute",
		Discriminator: 46,
		DataLength:    89,
		Family:        satFamilyMain,
		ContractKey:   "openDispute",
		AccountShape:  "SW,-W,-W,-W,--",
		Variable:      "",
	},
	"resolveDispute": {
		Action:        "resolveDispute",
		Discriminator: 48,
		DataLength:    57,
		Family:        satFamilyMain,
		ContractKey:   "resolveDispute",
		AccountShape:  "SW,--,-W,-W",
		Variable:      "",
	},
	"republishEpochRoots": {
		Action:        "republishEpochRoots",
		Discriminator: 49,
		DataLength:    105,
		Family:        satFamilyMain,
		ContractKey:   "republishEpochRoots",
		AccountShape:  "SW,--,-W",
		Variable:      "",
	},
	"topUpRegistryReserve": {
		Action:        "topUpRegistryReserve",
		Discriminator: 84,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "topUpRegistryReserve",
		AccountShape:  "SW,-W,--",
		Variable:      "",
	},
	"openCycle": {
		Action:        "openCycle",
		Discriminator: 56,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "openCycle",
		AccountShape:  "SW,-W,-W,-W,-W,-W,--,-W",
		Variable:      "",
	},
	"initMinerCapital": {
		Action:        "initMinerCapital",
		Discriminator: 36,
		DataLength:    33,
		Family:        satFamilyMain,
		ContractKey:   "initMinerCapital",
		AccountShape:  "SW,-W,--",
		Variable:      "",
	},
	"depositMinerCapital": {
		Action:        "depositMinerCapital",
		Discriminator: 37,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "depositMinerCapital",
		AccountShape:  "SW,-W,--",
		Variable:      "",
	},
	"withdrawMinerCapital": {
		Action:        "withdrawMinerCapital",
		Discriminator: 67,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "withdrawMinerCapital",
		AccountShape:  "SW,-W,--",
		Variable:      "",
	},
	"setActiveCommit": {
		Action:        "setActiveCommit",
		Discriminator: 68,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "setActiveCommit",
		AccountShape:  "S-,-W",
		Variable:      "",
	},
	"commitCycle": {
		Action:        "commitCycle",
		Discriminator: 89,
		DataLength:    41,
		Family:        satFamilyMain,
		ContractKey:   "commitCycle",
		AccountShape:  "SW,-W,-W,-W,--",
		Variable:      "",
	},
	"closeCommitPhase": {
		Action:        "closeCommitPhase",
		Discriminator: 90,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "closeCommitPhase",
		AccountShape:  "S-,-W",
		Variable:      "",
	},
	"sealCycleEntropy": {
		Action:        "sealCycleEntropy",
		Discriminator: 91,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "sealCycleEntropy",
		AccountShape:  "S-,-W,-W,--",
		Variable:      "",
	},
	"releaseUnrevealedCommit": {
		Action:        "releaseUnrevealedCommit",
		Discriminator: 93,
		DataLength:    41,
		Family:        satFamilyMain,
		ContractKey:   "releaseUnrevealedCommit",
		AccountShape:  "S-,-W,-W,-W,-W,-W",
		Variable:      "",
	},
	"abortEmptyCycle": {
		Action:        "abortEmptyCycle",
		Discriminator: 94,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "abortEmptyCycle",
		AccountShape:  "S-,-W,-W",
		Variable:      "",
	},
	"revealCycle": {
		Action:        "revealCycle",
		Discriminator: 92,
		DataLength:    145,
		Family:        satFamilyMain,
		ContractKey:   "revealCycle",
		AccountShape:  "SW,-W,-W,-W,-W,-W,-W,-W,-W,--",
		Variable:      "",
	},
	"settleCyclePage": {
		Action:        "settleCyclePage",
		Discriminator: 63,
		DataLength:    25,
		Family:        satFamilyMain,
		ContractKey:   "settleCyclePage",
		AccountShape:  "SW,--,-W,--,--,-W,-W,-W,--,--,-W,-W",
		Variable:      "minerCycles",
	},
	"finalizeCycleSettlement": {
		Action:        "finalizeCycleSettlement",
		Discriminator: 64,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "finalizeCycleSettlement",
		AccountShape:  "SW,-W,-W,-W,-W,-W,--,-W,-W",
		Variable:      "registryPages",
	},
	"scoreCyclePage": {
		Action:        "scoreCyclePage",
		Discriminator: 65,
		DataLength:    25,
		Family:        satFamilyMain,
		ContractKey:   "scoreCyclePage",
		AccountShape:  "SW,--,--,--,-W,-W,--,-W,-W",
		Variable:      "minerCycles",
	},
	"distributeCyclePage": {
		Action:        "distributeCyclePage",
		Discriminator: 66,
		DataLength:    25,
		Family:        satFamilyMain,
		ContractKey:   "distributeCyclePage",
		AccountShape:  "SW,-W,-W,-W,--,-W,--,-W,-W,-W",
		Variable:      "minerCyclePairs",
	},
	"claimCycleRewards": {
		Action:        "claimCycleRewards",
		Discriminator: 59,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "claimCycleRewards",
		AccountShape:  "SW,-W,-W,-W,-W,-W,-W,-W,-W,-W,--,--,--,--,-W",
		Variable:      "",
	},
	"claimCycleRewardsBatch": {
		Action:        "claimCycleRewardsBatch",
		Discriminator: 62,
		DataLength:    -1,
		Family:        satFamilyMain,
		ContractKey:   "claimCycleRewardsBatch",
		AccountShape:  "SW,-W,-W,-W,-W,-W,-W,-W",
		Variable:      "claimBatch",
	},
	"claimProtocolTreasury": {
		Action:        "claimProtocolTreasury",
		Discriminator: 77,
		DataLength:    1,
		Family:        satFamilyMain,
		ContractKey:   "claimProtocolTreasury",
		AccountShape:  "SW,--,--,-W,-W,-W,-W,-W,-W,-W,--,--,--,--",
		Variable:      "",
	},
	"refillRegistryReserveFromTreasury": {
		Action:        "refillRegistryReserveFromTreasury",
		Discriminator: 88,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "refillRegistryReserveFromTreasury",
		AccountShape:  "SW,-W,-W,-W,--",
		Variable:      "",
	},
	"claimProtocolDistributorSat": {
		Action:        "claimProtocolDistributorSat",
		Discriminator: 85,
		DataLength:    1,
		Family:        satFamilyMain,
		ContractKey:   "claimProtocolDistributorSat",
		AccountShape:  "SW,--,--,-W,-W,-W,-W,-W,--,--,--,--,--",
		Variable:      "",
	},
	"retargetUnlock": {
		Action:        "retargetUnlock",
		Discriminator: 60,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "retargetUnlock",
		AccountShape:  "S-,-W,--,-W",
		Variable:      "",
	},
	"closeResolvedMinerCycleState": {
		Action:        "closeResolvedMinerCycleState",
		Discriminator: 69,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "closeResolvedMinerCycleState",
		AccountShape:  "SW,-W,-W,-W,-W,-W",
		Variable:      "",
	},
	"closeResolvedCycleRegistryPage": {
		Action:        "closeResolvedCycleRegistryPage",
		Discriminator: 70,
		DataLength:    17,
		Family:        satFamilyMain,
		ContractKey:   "closeResolvedCycleRegistryPage",
		AccountShape:  "SW,-W,-W,-W,-W",
		Variable:      "",
	},
	"closeResolvedCycleArtifacts": {
		Action:        "closeResolvedCycleArtifacts",
		Discriminator: 71,
		DataLength:    9,
		Family:        satFamilyMain,
		ContractKey:   "closeResolvedCycleArtifacts",
		AccountShape:  "SW,-W,-W,-W,-W",
		Variable:      "",
	},
	"compactPendingCycleRange": {
		Action:        "compactPendingCycleRange",
		Discriminator: 75,
		DataLength:    25,
		Family:        satFamilyMain,
		ContractKey:   "compactPendingCycleRange",
		AccountShape:  "SW,-W",
		Variable:      "compactCycles",
	},
	"updateBondTierPolicy": {
		Action:        "updateBondTierPolicy",
		Discriminator: 1,
		DataLength:    65,
		Family:        satFamilyBond,
		ContractKey:   "updateTierPolicy",
		AccountShape:  "SW,-W",
		Variable:      "",
	},
	"openBondPosition": {
		Action:        "openBondPosition",
		Discriminator: 2,
		DataLength:    9,
		Family:        satFamilyBond,
		ContractKey:   "openBondPosition",
		AccountShape:  "SW,--,-W,-W,-W,--,--,--,--",
		Variable:      "",
	},
	"increaseBondPosition": {
		Action:        "increaseBondPosition",
		Discriminator: 3,
		DataLength:    9,
		Family:        satFamilyBond,
		ContractKey:   "increaseBondPosition",
		AccountShape:  "SW,--,-W,-W,-W,--,--,--,--",
		Variable:      "",
	},
	"requestBondUnlock": {
		Action:        "requestBondUnlock",
		Discriminator: 4,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "requestBondUnlock",
		AccountShape:  "SW,--,-W,-W,-W",
		Variable:      "",
	},
	"cancelBondUnlock": {
		Action:        "cancelBondUnlock",
		Discriminator: 5,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "cancelBondUnlock",
		AccountShape:  "SW,--,-W,-W,-W",
		Variable:      "",
	},
	"finalizeBondUnlock": {
		Action:        "finalizeBondUnlock",
		Discriminator: 6,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "finalizeBondUnlock",
		AccountShape:  "SW,--,-W,-W,-W,-W,-W,--,--,--,--",
		Variable:      "",
	},
	"syncBondStakingRewards": {
		Action:        "syncBondStakingRewards",
		Discriminator: 8,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "syncStakingRewards",
		AccountShape:  "-W,--,--",
		Variable:      "",
	},
	"syncBondStakingPosition": {
		Action:        "syncBondStakingPosition",
		Discriminator: 9,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "syncStakingPosition",
		AccountShape:  "SW,--,-W,-W,--,--",
		Variable:      "",
	},
	"claimBondStakingRewards": {
		Action:        "claimBondStakingRewards",
		Discriminator: 10,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "claimStakingRewards",
		AccountShape:  "SW,--,-W,-W,--,-W,-W,--,--,--,--",
		Variable:      "",
	},
	"claimUnallocatedStakingRewards": {
		Action:        "claimUnallocatedStakingRewards",
		Discriminator: 11,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "claimUnallocatedStakingRewards",
		AccountShape:  "SW,-W,-W,-W,--,--,--,--,--",
		Variable:      "",
	},
	"registerBondEpochPositionV3": {
		Action:        "registerBondEpochPositionV3",
		Discriminator: 15,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "registerEpochPositionV3",
		AccountShape:  "SW,--,-W,-W,-W,--,--",
		Variable:      "",
	},
	"increaseBondPositionV3": {
		Action:        "increaseBondPositionV3",
		Discriminator: 16,
		DataLength:    9,
		Family:        satFamilyBond,
		ContractKey:   "increaseBondPositionV3",
		AccountShape:  "S-,--,-W,-W,-W,--,-W,-W,--,--,--,--",
		Variable:      "",
	},
	"requestBondUnlockV3": {
		Action:        "requestBondUnlockV3",
		Discriminator: 17,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "requestBondUnlockV3",
		AccountShape:  "S-,--,-W,-W,-W,--",
		Variable:      "",
	},
	"cancelBondUnlockV3": {
		Action:        "cancelBondUnlockV3",
		Discriminator: 18,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "cancelBondUnlockV3",
		AccountShape:  "S-,--,-W,-W,-W",
		Variable:      "",
	},
	"finalizeBondUnlockV3": {
		Action:        "finalizeBondUnlockV3",
		Discriminator: 19,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "finalizeBondUnlockV3",
		AccountShape:  "S-,--,-W,-W,-W,-W,-W,--,--,--,--",
		Variable:      "",
	},
	"claimBondEpochRewardsV3": {
		Action:        "claimBondEpochRewardsV3",
		Discriminator: 20,
		DataLength:    1,
		Family:        satFamilyBond,
		ContractKey:   "claimEpochRewardsV3",
		AccountShape:  "S-,--,-W,-W,--,--,-W,-W,--,--,--,--",
		Variable:      "",
	},
}
