import type { ModelCapabilityConfig } from "../config/types.models.js";

export type RefreshedModelCapability = {
  input?: Array<"text" | "image">;
  reasoning?: boolean;
  capabilities?: ModelCapabilityConfig;
  contextWindow?: number;
  maxTokens?: number;
  source?: string;
  refreshedAt?: string;
};

export const REFRESHED_MODEL_CAPABILITIES: Record<string, RefreshedModelCapability> = {
  "chutes/deepseek-ai/deepseek-v3.2-tee": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 131072,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "chutes/google/gemma-4-31b-turbo-tee": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    contextWindow: 131072,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "chutes/moonshotai/kimi-k2.6-tee": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      video: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "moonshot-thinking",
      reasoningBudgetSupported: false,
    },
    contextWindow: 262144,
    maxTokens: 65535,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "chutes/qwen/qwen3-235b-a22b-thinking-2507-tee": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "qwen-thinking",
      reasoningBudgetSupported: true,
    },
    contextWindow: 262144,
    maxTokens: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "chutes/qwen/qwen3-32b-tee": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "qwen-thinking",
      reasoningBudgetSupported: true,
    },
    contextWindow: 40960,
    maxTokens: 40960,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "chutes/qwen/qwen3.5-397b-a17b-tee": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "qwen-thinking",
      reasoningBudgetSupported: true,
    },
    contextWindow: 262144,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "chutes/qwen/qwen3.6-27b-tee": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "qwen-thinking",
      reasoningBudgetSupported: true,
    },
    contextWindow: 262144,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "chutes/zai-org/glm-5-tee": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "low"],
      defaultThinkingLevel: "low",
      thinkingMode: "zai-binary",
      reasoningBudgetSupported: false,
    },
    contextWindow: 202752,
    maxTokens: 65535,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "chutes/zai-org/glm-5.1-tee": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "low"],
      defaultThinkingLevel: "low",
      thinkingMode: "zai-binary",
      reasoningBudgetSupported: false,
    },
    contextWindow: 202752,
    maxTokens: 65535,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "chutes/zai-org/glm-5.2-tee": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "low"],
      defaultThinkingLevel: "low",
      thinkingMode: "zai-binary",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1048576,
    maxTokens: 65535,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/deepseek-ai/deepseek-r1": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 64000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/deepseek-ai/deepseek-v3.2": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 163840,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/deepseek-ai/deepseek-v4-flash": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 1048576,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/deepseek-ai/deepseek-v4-pro": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 1048576,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/google/gemma-3n-e4b-it": {
    input: ["text", "image"],
    capabilities: { tools: false, json: true },
    contextWindow: 32768,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/google/gemma-4-26b-a4b-it": {
    input: ["text", "image"],
    capabilities: { tools: true, json: true },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/google/gemma-4-31b-it": {
    input: ["text", "image"],
    capabilities: { tools: true, json: true },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/inclusionai/ling-2.6-1t": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/meta-llama/llama-3.3-70b-instruct": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 131072,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/minimaxai/minimax-m2.7": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 204800,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/moonshotai/kimi-k2.6": {
    input: ["text", "image"],
    capabilities: { tools: true, json: true },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/openai/gpt-oss-120b": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 131072,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/openai/gpt-oss-20b": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 131072,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/qwen/qwen3-235b-a22b-instruct-2507": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/qwen/qwen3-coder-480b-a35b-instruct": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "qwen-thinking",
      reasoningBudgetSupported: true,
    },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/qwen/qwen3-coder-next": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: false,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "qwen-thinking",
      reasoningBudgetSupported: true,
    },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/qwen/qwen3-vl-235b-a22b-instruct": {
    input: ["text", "image"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "qwen-thinking",
      reasoningBudgetSupported: true,
    },
    contextWindow: 131072,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/qwen/qwen3.5-397b-a17b": {
    input: ["text", "image"],
    capabilities: { tools: true, json: true },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/qwen/qwen3.6-35b-a3b": {
    input: ["text", "image"],
    capabilities: { tools: true, json: true },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "huggingface/zai-org/glm-5.1": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 202752,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openai/gpt-5.4": {
    capabilities: {
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openai/gpt-5.4-mini": {
    capabilities: {
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openai/gpt-5.4-nano": {
    capabilities: {
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openai/gpt-5.5": {
    capabilities: {
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openai/gpt-5.6": {
    capabilities: {
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openai/gpt-5.6-luna": {
    capabilities: {
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openai/gpt-5.6-terra": {
    capabilities: {
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/claude-fable-5": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-adaptive",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/claude-haiku-4-5": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-thinking-budget",
      reasoningBudgetSupported: true,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/claude-opus-4-8": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-adaptive",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/claude-sonnet-5": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-adaptive",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/gemini-3-flash": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/gemini-3.1-pro": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/gemini-3.5-flash": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/glm-5.2": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "low"],
      defaultThinkingLevel: "low",
      thinkingMode: "zai-binary",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/gpt-5.3-codex-spark": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/gpt-5.4": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/gpt-5.4-mini": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/gpt-5.4-nano": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/gpt-5.5": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/kimi-k2.6": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "moonshot-thinking",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "opencode/minimax-m2.7": {
    input: ["text"],
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/anthropic/claude-fable-5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-adaptive",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/anthropic/claude-haiku-4.5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-thinking-budget",
      reasoningBudgetSupported: true,
    },
    contextWindow: 200000,
    maxTokens: 64000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/anthropic/claude-opus-4.8": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-adaptive",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/anthropic/claude-sonnet-5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-adaptive",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/deepseek/deepseek-v4-flash": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1048576,
    maxTokens: 384000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/deepseek/deepseek-v4-pro": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1048576,
    maxTokens: 384000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/google/gemini-3-flash-preview": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: true,
      video: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    contextWindow: 1048576,
    maxTokens: 65535,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/google/gemini-3.1-flash-lite": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: true,
      video: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    contextWindow: 1048576,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/google/gemini-3.1-pro-preview": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: true,
      video: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    contextWindow: 1048576,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/google/gemini-3.5-flash": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: true,
      video: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    contextWindow: 1048576,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/minimax/minimax-m2.7": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "off",
      thinkingMode: "anthropic-thinking-budget",
      reasoningBudgetSupported: false,
    },
    contextWindow: 204800,
    maxTokens: 196608,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/mistralai/devstral-2512": {
    input: ["text"],
    capabilities: { tools: true, json: true },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/mistralai/mistral-large-2512": {
    input: ["text", "image"],
    capabilities: { tools: true, json: true },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/mistralai/mistral-medium-3-5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "high"],
      defaultThinkingLevel: "high",
      thinkingMode: "mistral-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/mistralai/mistral-small-2603": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "high"],
      defaultThinkingLevel: "high",
      thinkingMode: "mistral-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/moonshotai/kimi-k2.6": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "moonshot-thinking",
      reasoningBudgetSupported: false,
    },
    contextWindow: 262144,
    maxTokens: 262144,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/openai/gpt-5.4": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1050000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/openai/gpt-5.4-mini": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/openai/gpt-5.4-nano": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/openai/gpt-5.5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1050000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/openai/gpt-5.6-luna": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1050000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/openai/gpt-5.6-sol": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1050000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/openai/gpt-5.6-terra": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1050000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/qwen/qwen3.6-flash": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      video: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "qwen-thinking",
      reasoningBudgetSupported: true,
    },
    contextWindow: 1000000,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/qwen/qwen3.7-max": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      video: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "qwen-thinking",
      reasoningBudgetSupported: true,
    },
    contextWindow: 1000000,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/qwen/qwen3.7-plus": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      video: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "qwen-thinking",
      reasoningBudgetSupported: true,
    },
    contextWindow: 1000000,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/x-ai/grok-4.3": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "xai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/x-ai/grok-4.5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "xai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 500000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/x-ai/grok-build-0.1": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 256000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "openrouter/z-ai/glm-5.2": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "low"],
      defaultThinkingLevel: "low",
      thinkingMode: "zai-binary",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1048576,
    maxTokens: 131072,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "synthetic/hf:nvidia/nvidia-nemotron-3-super-120b-a12b-nvfp4": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 262144,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "synthetic/hf:openai/gpt-oss-120b": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 131072,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "synthetic/hf:zai-org/glm-4.7-flash": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      thinkingLevels: ["off", "low"],
      defaultThinkingLevel: "low",
      thinkingMode: "zai-binary",
      reasoningBudgetSupported: false,
    },
    contextWindow: 196608,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/claude-opus-4-7": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/claude-sonnet-4-6": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 64000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/deepseek-v4-flash": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 32768,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/deepseek-v4-pro": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 32768,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/gemini-3-1-pro-preview": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: true,
      video: true,
      thinkingLevels: ["low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 32768,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/google-gemma-4-31b-it": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: true,
      thinkingLevels: ["off", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 256000,
    maxTokens: 8192,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/grok-4-20": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      reasoningBudgetSupported: false,
    },
    contextWindow: 2000000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/kimi-k2-6": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      thinkingLevels: ["off", "low", "medium", "high"],
      defaultThinkingLevel: "high",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 256000,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/minimax-m27": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: false,
      audio: false,
      video: false,
      thinkingLevels: ["off", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 198000,
    maxTokens: 32768,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/mistral-small-2603": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      thinkingLevels: ["off", "high"],
      defaultThinkingLevel: "high",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 256000,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/openai-gpt-54": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "high",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 131072,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/openai-gpt-54-mini": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "high",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/openai-gpt-55": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      thinkingLevels: ["off", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "high",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 131072,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/openai-gpt-55-pro": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      thinkingLevels: ["medium", "high", "xhigh"],
      defaultThinkingLevel: "medium",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/openai-gpt-oss-120b": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: false,
      audio: false,
      video: false,
      thinkingLevels: ["off", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 128000,
    maxTokens: 16384,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/qwen-3-6-plus": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: true,
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/qwen3-235b-a22b-thinking-2507": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      thinkingLevels: ["low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 128000,
    maxTokens: 16384,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/qwen3-5-397b-a17b": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: true,
      thinkingLevels: ["off", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/qwen3-coder-480b-a35b-instruct-turbo": {
    input: ["text"],
    reasoning: false,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      reasoningBudgetSupported: false,
    },
    contextWindow: 256000,
    maxTokens: 65536,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/qwen3-vl-235b-a22b": {
    input: ["text", "image"],
    reasoning: false,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      reasoningBudgetSupported: false,
    },
    contextWindow: 128000,
    maxTokens: 16384,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/venice-uncensored-1-2": {
    input: ["text", "image"],
    reasoning: false,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      reasoningBudgetSupported: false,
    },
    contextWindow: 128000,
    maxTokens: 8192,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "venice/zai-org-glm-5-1": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      json: true,
      audio: false,
      video: false,
      thinkingLevels: ["off", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 200000,
    maxTokens: 80000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/anthropic/claude-fable-5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-adaptive",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/anthropic/claude-haiku-4.5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-thinking-budget",
      reasoningBudgetSupported: true,
    },
    contextWindow: 200000,
    maxTokens: 64000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/anthropic/claude-opus-4.8": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-adaptive",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/anthropic/claude-sonnet-5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "anthropic-adaptive",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/google/gemini-3.1-flash-lite": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    contextWindow: 1000000,
    maxTokens: 65000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/google/gemini-3.1-pro-preview": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    contextWindow: 1000000,
    maxTokens: 64000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/google/gemini-3.5-flash": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "google-thinking-budget",
      reasoningBudgetSupported: true,
    },
    contextWindow: 1000000,
    maxTokens: 64000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/minimax/minimax-m2.7": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 204800,
    maxTokens: 131000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/minimax/minimax-m2.7-highspeed": {
    input: ["text"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 204800,
    maxTokens: 131100,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/mistral/mistral-medium-3.5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 256000,
    maxTokens: 256000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/moonshotai/kimi-k2.6": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "moonshot-thinking",
      reasoningBudgetSupported: false,
    },
    contextWindow: 262000,
    maxTokens: 262000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/openai/gpt-5.4": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1050000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/openai/gpt-5.4-mini": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/openai/gpt-5.4-nano": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/openai/gpt-5.5": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh"],
      defaultThinkingLevel: "low",
      thinkingMode: "openai-reasoning-effort",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/xai/grok-4.3": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 1000000,
    maxTokens: 1000000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
  "vercel-ai-gateway/xai/grok-build-0.1": {
    input: ["text", "image"],
    reasoning: true,
    capabilities: {
      tools: true,
      thinkingLevels: ["off", "minimal", "low", "medium", "high"],
      defaultThinkingLevel: "low",
      thinkingMode: "generic-reasoning",
      reasoningBudgetSupported: false,
    },
    contextWindow: 256000,
    maxTokens: 256000,
    source: "catalog",
    refreshedAt: "2026-07-12T05:03:49.877Z",
  },
};

export function lookupRefreshedModelCapability(
  provider: string,
  model: string,
): RefreshedModelCapability | undefined {
  const key = `${provider.trim()}/${model.trim()}`.toLowerCase();
  return REFRESHED_MODEL_CAPABILITIES[key];
}
