export const browserCoreExamples = [
  "fased browser status",
  "fased browser start",
  "fased browser stop",
  "fased browser tabs",
  "fased browser open https://example.com",
  "fased browser focus abcd1234",
  "fased browser close abcd1234",
  "fased browser screenshot",
  "fased browser screenshot --full-page",
  "fased browser screenshot --ref 12",
  "fased browser snapshot",
  "fased browser snapshot --format aria --limit 200",
  "fased browser snapshot --efficient",
  "fased browser snapshot --labels",
];

export const browserActionExamples = [
  "fased browser navigate https://example.com",
  "fased browser resize 1280 720",
  "fased browser click 12 --double",
  'fased browser type 23 "hello" --submit',
  "fased browser press Enter",
  "fased browser hover 44",
  "fased browser drag 10 11",
  "fased browser select 9 OptionA OptionB",
  "fased browser upload /tmp/fased/uploads/file.pdf",
  'fased browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "fased browser dialog --accept",
  'fased browser wait --text "Done"',
  "fased browser evaluate --fn '(el) => el.textContent' --ref 7",
  "fased browser console --level error",
  "fased browser pdf",
];
