#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${FASED_INSTALL_E2E_IMAGE:-${FASED_INSTALL_E2E_IMAGE:-fased-install-e2e:local}}"
INSTALL_URL="${FASED_INSTALL_URL:-${FASED_INSTALL_URL:-https://fased.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
FASED_E2E_MODELS="${FASED_E2E_MODELS:-${FASED_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e FASED_INSTALL_URL="$INSTALL_URL" \
  -e FASED_INSTALL_TAG="${FASED_INSTALL_TAG:-${FASED_INSTALL_TAG:-latest}}" \
  -e FASED_E2E_MODELS="$FASED_E2E_MODELS" \
  -e FASED_INSTALL_E2E_PREVIOUS="${FASED_INSTALL_E2E_PREVIOUS:-${FASED_INSTALL_E2E_PREVIOUS:-}}" \
  -e FASED_INSTALL_E2E_SKIP_PREVIOUS="${FASED_INSTALL_E2E_SKIP_PREVIOUS:-${FASED_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
