/* oxlint-disable */
// Code generated by scripts/generate-money-foundation.mjs; DO NOT EDIT.

export const FASED_SAT_SOL_MONEY_FOUNDATION_CONTRACT = {
  $schema: "fased.sat-sol-money-foundation-contract.v1",
  contractId: "fased.sat-sol-money-foundation.v1",
  contractGeneration: 1,
  initialState: "DISABLED_UNFUNDED",
  supportedVenues: ["METEORA_DAMM_V2_LAUNCH"],
  canonicalPair: {
    base: "SAT",
    quote: "WSOL",
  },
  leadingCanary: {
    satRaw: "200000000000000",
    solLamports: "10000000000",
    authorized: false,
  },
  enums: {
    MarketLifecycle: ["DISABLED", "ENABLED", "PAUSED", "RETIRED"],
    VenueKind: ["METEORA_DAMM_V2_LAUNCH"],
    WithdrawalMode: ["EMERGENCY_TIMELOCK_ONLY"],
    MarketAction: ["ENTER", "EXIT", "ADD_POL", "EMERGENCY_UNWIND"],
    ReviewDecision: ["APPROVED", "REJECTED"],
    SourceClass: ["RETAIL_WALLET", "OWNER_SEED", "PROTOCOL_SURPLUS", "EMERGENCY_TREASURY"],
  },
  objects: {
    SatSolMarketPolicyV1: {
      schema: "fased.sat-sol-market-policy.v1",
      required: [
        "contractGeneration",
        "policyGeneration",
        "clusterGenesisHash",
        "lifecycle",
        "satMint",
        "satTokenProgram",
        "wrappedSolMint",
        "venue",
        "venueProgram",
        "liquidityTreasury",
        "emergencyAuthority",
        "initialSatRaw",
        "initialSolLamports",
        "maxSlippageBps",
        "maxPriceImpactBps",
        "maxCombinedFeeBps",
        "publicEntryEnabled",
        "fundingAuthorized",
        "withdrawalMode",
        "sourceDescriptorSha256",
      ],
    },
    SatSolMarketBindingV1: {
      schema: "fased.sat-sol-market-binding.v1",
      required: [
        "contractGeneration",
        "policyGeneration",
        "policyDigestSha256",
        "lifecycle",
        "pool",
        "poolConfig",
        "poolProgram",
        "positionMint",
        "positionTokenAccount",
        "satVault",
        "solVault",
        "liquidityTreasury",
        "emergencyAuthority",
        "finalizedSlot",
        "satReserveRaw",
        "solReserveLamports",
        "immutableConfig",
        "custodyVerified",
        "publicEntryEnabled",
      ],
    },
    SatSolTransactionReviewV1: {
      schema: "fased.sat-sol-transaction-review.v1",
      required: [
        "contractGeneration",
        "policyGeneration",
        "policyDigestSha256",
        "action",
        "decision",
        "sourceClass",
        "sourceOwner",
        "destinationOwner",
        "pool",
        "satMint",
        "wrappedSolMint",
        "inputRaw",
        "minimumOutputRaw",
        "maxSlippageBps",
        "simulationSlot",
        "expiresSlot",
        "fixedDestination",
        "protectedCapitalReachable",
      ],
    },
    SatSolPolCustodyV1: {
      schema: "fased.sat-sol-pol-custody.v1",
      required: [
        "contractGeneration",
        "policyGeneration",
        "policyDigestSha256",
        "pool",
        "positionMint",
        "positionTokenAccount",
        "positionOwner",
        "withdrawalMode",
        "emergencyAuthority",
        "miningVaultPrincipalReachable",
        "bondPrincipalReachable",
        "keeperReserveReachable",
        "pendingClaimsReachable",
        "protectedAgentReserveReachable",
        "ownerHotWalletCanWithdraw",
      ],
    },
    SatSolEmergencyUnwindReceiptV1: {
      schema: "fased.sat-sol-emergency-unwind-receipt.v1",
      required: [
        "contractGeneration",
        "policyGeneration",
        "policyDigestSha256",
        "pool",
        "positionMint",
        "finalizedSlot",
        "satBeforeRaw",
        "solBeforeLamports",
        "satRecoveredRaw",
        "solRecoveredLamports",
        "satDestination",
        "solDestination",
        "positionClosed",
        "remainingPositionRaw",
        "allProtectedLiabilitiesUnchanged",
      ],
    },
  },
  invariants: [
    "Genesis is disabled, unfunded and does not authorize pool creation or public entry",
    "Every configured instance binds exact SAT mint, token program, WSOL mint, venue program, pool, vault and position identities",
    "An approved transaction review expires and fixes source, destination, pool, amount bounds and slippage",
    "Mining Vault principal, Bond principal, keeper reserves, pending claims and protected Agent reserves are unreachable from POL custody",
    "Only a timelocked emergency path may remove the canonical position",
    "Entrance, exit and unwind evidence use finalized balances and conserve SAT and SOL independently",
    "No contract record claims that source validation or local simulation is a live market",
  ],
} as const;

export const FASED_SAT_SOL_MONEY_FOUNDATION_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "fased.sat-sol-money-foundation.v1",
  title: "Fased SAT/SOL money foundation records",
  oneOf: [
    {
      $ref: "#/$defs/SatSolMarketPolicyV1",
    },
    {
      $ref: "#/$defs/SatSolMarketBindingV1",
    },
    {
      $ref: "#/$defs/SatSolTransactionReviewV1",
    },
    {
      $ref: "#/$defs/SatSolPolCustodyV1",
    },
    {
      $ref: "#/$defs/SatSolEmergencyUnwindReceiptV1",
    },
  ],
  $defs: {
    SatSolMarketPolicyV1: {
      type: "object",
      additionalProperties: false,
      properties: {
        schema: {
          const: "fased.sat-sol-market-policy.v1",
        },
        contractGeneration: {
          const: 1,
        },
        policyGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        clusterGenesisHash: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        lifecycle: {
          enum: ["DISABLED", "ENABLED", "PAUSED", "RETIRED"],
        },
        satMint: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        satTokenProgram: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        wrappedSolMint: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        venue: {
          enum: ["METEORA_DAMM_V2_LAUNCH"],
        },
        venueProgram: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        liquidityTreasury: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        emergencyAuthority: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        initialSatRaw: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        initialSolLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        maxSlippageBps: {
          type: "integer",
          minimum: 0,
          maximum: 10000,
        },
        maxPriceImpactBps: {
          type: "integer",
          minimum: 0,
          maximum: 10000,
        },
        maxCombinedFeeBps: {
          type: "integer",
          minimum: 0,
          maximum: 10000,
        },
        publicEntryEnabled: {
          type: "boolean",
        },
        fundingAuthorized: {
          type: "boolean",
        },
        withdrawalMode: {
          enum: ["EMERGENCY_TIMELOCK_ONLY"],
        },
        sourceDescriptorSha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
      },
      required: [
        "schema",
        "contractGeneration",
        "policyGeneration",
        "clusterGenesisHash",
        "lifecycle",
        "satMint",
        "satTokenProgram",
        "wrappedSolMint",
        "venue",
        "venueProgram",
        "liquidityTreasury",
        "emergencyAuthority",
        "initialSatRaw",
        "initialSolLamports",
        "maxSlippageBps",
        "maxPriceImpactBps",
        "maxCombinedFeeBps",
        "publicEntryEnabled",
        "fundingAuthorized",
        "withdrawalMode",
        "sourceDescriptorSha256",
      ],
    },
    SatSolMarketBindingV1: {
      type: "object",
      additionalProperties: false,
      properties: {
        schema: {
          const: "fased.sat-sol-market-binding.v1",
        },
        contractGeneration: {
          const: 1,
        },
        policyGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        policyDigestSha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        lifecycle: {
          enum: ["DISABLED", "ENABLED", "PAUSED", "RETIRED"],
        },
        pool: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        poolConfig: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        poolProgram: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        positionMint: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        positionTokenAccount: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        satVault: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        solVault: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        liquidityTreasury: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        emergencyAuthority: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        finalizedSlot: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        satReserveRaw: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        solReserveLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        immutableConfig: {
          type: "boolean",
        },
        custodyVerified: {
          type: "boolean",
        },
        publicEntryEnabled: {
          type: "boolean",
        },
      },
      required: [
        "schema",
        "contractGeneration",
        "policyGeneration",
        "policyDigestSha256",
        "lifecycle",
        "pool",
        "poolConfig",
        "poolProgram",
        "positionMint",
        "positionTokenAccount",
        "satVault",
        "solVault",
        "liquidityTreasury",
        "emergencyAuthority",
        "finalizedSlot",
        "satReserveRaw",
        "solReserveLamports",
        "immutableConfig",
        "custodyVerified",
        "publicEntryEnabled",
      ],
    },
    SatSolTransactionReviewV1: {
      type: "object",
      additionalProperties: false,
      properties: {
        schema: {
          const: "fased.sat-sol-transaction-review.v1",
        },
        contractGeneration: {
          const: 1,
        },
        policyGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        policyDigestSha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        action: {
          enum: ["ENTER", "EXIT", "ADD_POL", "EMERGENCY_UNWIND"],
        },
        decision: {
          enum: ["APPROVED", "REJECTED"],
        },
        sourceClass: {
          enum: ["RETAIL_WALLET", "OWNER_SEED", "PROTOCOL_SURPLUS", "EMERGENCY_TREASURY"],
        },
        sourceOwner: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        destinationOwner: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        pool: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        satMint: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        wrappedSolMint: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        inputRaw: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        minimumOutputRaw: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        maxSlippageBps: {
          type: "integer",
          minimum: 0,
          maximum: 10000,
        },
        simulationSlot: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        expiresSlot: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        fixedDestination: {
          type: "boolean",
        },
        protectedCapitalReachable: {
          type: "boolean",
        },
      },
      required: [
        "schema",
        "contractGeneration",
        "policyGeneration",
        "policyDigestSha256",
        "action",
        "decision",
        "sourceClass",
        "sourceOwner",
        "destinationOwner",
        "pool",
        "satMint",
        "wrappedSolMint",
        "inputRaw",
        "minimumOutputRaw",
        "maxSlippageBps",
        "simulationSlot",
        "expiresSlot",
        "fixedDestination",
        "protectedCapitalReachable",
      ],
    },
    SatSolPolCustodyV1: {
      type: "object",
      additionalProperties: false,
      properties: {
        schema: {
          const: "fased.sat-sol-pol-custody.v1",
        },
        contractGeneration: {
          const: 1,
        },
        policyGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        policyDigestSha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        pool: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        positionMint: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        positionTokenAccount: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        positionOwner: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        withdrawalMode: {
          enum: ["EMERGENCY_TIMELOCK_ONLY"],
        },
        emergencyAuthority: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        miningVaultPrincipalReachable: {
          const: false,
        },
        bondPrincipalReachable: {
          const: false,
        },
        keeperReserveReachable: {
          const: false,
        },
        pendingClaimsReachable: {
          const: false,
        },
        protectedAgentReserveReachable: {
          const: false,
        },
        ownerHotWalletCanWithdraw: {
          const: false,
        },
      },
      required: [
        "schema",
        "contractGeneration",
        "policyGeneration",
        "policyDigestSha256",
        "pool",
        "positionMint",
        "positionTokenAccount",
        "positionOwner",
        "withdrawalMode",
        "emergencyAuthority",
        "miningVaultPrincipalReachable",
        "bondPrincipalReachable",
        "keeperReserveReachable",
        "pendingClaimsReachable",
        "protectedAgentReserveReachable",
        "ownerHotWalletCanWithdraw",
      ],
    },
    SatSolEmergencyUnwindReceiptV1: {
      type: "object",
      additionalProperties: false,
      properties: {
        schema: {
          const: "fased.sat-sol-emergency-unwind-receipt.v1",
        },
        contractGeneration: {
          const: 1,
        },
        policyGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        policyDigestSha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        pool: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        positionMint: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        finalizedSlot: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        satBeforeRaw: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        solBeforeLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        satRecoveredRaw: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        solRecoveredLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        satDestination: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        solDestination: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        positionClosed: {
          type: "boolean",
        },
        remainingPositionRaw: {
          type: "string",
          pattern: "^(0|[1-9][0-9]{0,19})$",
        },
        allProtectedLiabilitiesUnchanged: {
          const: true,
        },
      },
      required: [
        "schema",
        "contractGeneration",
        "policyGeneration",
        "policyDigestSha256",
        "pool",
        "positionMint",
        "finalizedSlot",
        "satBeforeRaw",
        "solBeforeLamports",
        "satRecoveredRaw",
        "solRecoveredLamports",
        "satDestination",
        "solDestination",
        "positionClosed",
        "remainingPositionRaw",
        "allProtectedLiabilitiesUnchanged",
      ],
    },
  },
} as const;

export type MarketLifecycle = "DISABLED" | "ENABLED" | "PAUSED" | "RETIRED";
export type VenueKind = "METEORA_DAMM_V2_LAUNCH";
export type WithdrawalMode = "EMERGENCY_TIMELOCK_ONLY";
export type MarketAction = "ENTER" | "EXIT" | "ADD_POL" | "EMERGENCY_UNWIND";
export type ReviewDecision = "APPROVED" | "REJECTED";
export type SourceClass =
  | "RETAIL_WALLET"
  | "OWNER_SEED"
  | "PROTOCOL_SURPLUS"
  | "EMERGENCY_TREASURY";

export interface SatSolMarketPolicyV1 {
  schema: "fased.sat-sol-market-policy.v1";
  contractGeneration: 1;
  policyGeneration: string;
  clusterGenesisHash: string;
  lifecycle: MarketLifecycle;
  satMint: string;
  satTokenProgram: string;
  wrappedSolMint: string;
  venue: VenueKind;
  venueProgram: string;
  liquidityTreasury: string;
  emergencyAuthority: string;
  initialSatRaw: string;
  initialSolLamports: string;
  maxSlippageBps: number;
  maxPriceImpactBps: number;
  maxCombinedFeeBps: number;
  publicEntryEnabled: boolean;
  fundingAuthorized: boolean;
  withdrawalMode: WithdrawalMode;
  sourceDescriptorSha256: string;
}

export interface SatSolMarketBindingV1 {
  schema: "fased.sat-sol-market-binding.v1";
  contractGeneration: 1;
  policyGeneration: string;
  policyDigestSha256: string;
  lifecycle: MarketLifecycle;
  pool: string;
  poolConfig: string;
  poolProgram: string;
  positionMint: string;
  positionTokenAccount: string;
  satVault: string;
  solVault: string;
  liquidityTreasury: string;
  emergencyAuthority: string;
  finalizedSlot: string;
  satReserveRaw: string;
  solReserveLamports: string;
  immutableConfig: boolean;
  custodyVerified: boolean;
  publicEntryEnabled: boolean;
}

export interface SatSolTransactionReviewV1 {
  schema: "fased.sat-sol-transaction-review.v1";
  contractGeneration: 1;
  policyGeneration: string;
  policyDigestSha256: string;
  action: MarketAction;
  decision: ReviewDecision;
  sourceClass: SourceClass;
  sourceOwner: string;
  destinationOwner: string;
  pool: string;
  satMint: string;
  wrappedSolMint: string;
  inputRaw: string;
  minimumOutputRaw: string;
  maxSlippageBps: number;
  simulationSlot: string;
  expiresSlot: string;
  fixedDestination: boolean;
  protectedCapitalReachable: boolean;
}

export interface SatSolPolCustodyV1 {
  schema: "fased.sat-sol-pol-custody.v1";
  contractGeneration: 1;
  policyGeneration: string;
  policyDigestSha256: string;
  pool: string;
  positionMint: string;
  positionTokenAccount: string;
  positionOwner: string;
  withdrawalMode: WithdrawalMode;
  emergencyAuthority: string;
  miningVaultPrincipalReachable: false;
  bondPrincipalReachable: false;
  keeperReserveReachable: false;
  pendingClaimsReachable: false;
  protectedAgentReserveReachable: false;
  ownerHotWalletCanWithdraw: false;
}

export interface SatSolEmergencyUnwindReceiptV1 {
  schema: "fased.sat-sol-emergency-unwind-receipt.v1";
  contractGeneration: 1;
  policyGeneration: string;
  policyDigestSha256: string;
  pool: string;
  positionMint: string;
  finalizedSlot: string;
  satBeforeRaw: string;
  solBeforeLamports: string;
  satRecoveredRaw: string;
  solRecoveredLamports: string;
  satDestination: string;
  solDestination: string;
  positionClosed: boolean;
  remainingPositionRaw: string;
  allProtectedLiabilitiesUnchanged: true;
}

export type SatSolMoneyFoundationRecord =
  | SatSolMarketPolicyV1
  | SatSolMarketBindingV1
  | SatSolTransactionReviewV1
  | SatSolPolCustodyV1
  | SatSolEmergencyUnwindReceiptV1;
