/* oxlint-disable */
// Code generated by scripts/generate-public-views.mjs; DO NOT EDIT.

export const FASED_PUBLIC_AGENT_VIEW_CONTRACT = {
  $schema: "fased.public-agent-view-contract.v1",
  contractId: "fased.public-agent-views.v1",
  laterPhaseFields: [
    "agentCapital",
    "agentMarket",
    "agentService",
    "agentStrategy",
    "agentTokenMint",
    "capitalOffer",
    "folio",
    "marketPrice",
    "serviceRevenue",
    "strategyPnl",
  ],
  enums: {
    EvidenceSource: [
      "agent_identity_program",
      "satcoin_program",
      "fased_network",
      "fased_runtime",
      "owner_declaration",
    ],
    EvidenceTrust: ["finalized", "signed", "declared"],
    ViewFreshness: ["fresh", "stale"],
    ViewIntegrity: ["verified", "conflict"],
    AgentLifecycle: ["network_only", "active", "retired"],
    RuntimeState: ["current", "stale", "absent"],
    MiningLifecycle: ["active", "retired"],
    MiningEntryState: ["enabled", "paused", "draining", "drained"],
    KeeperState: ["healthy", "degraded", "offline", "unknown"],
    BroadcastState: ["eligible", "ineligible", "disabled", "unknown"],
    QualificationPurpose: ["public_identity", "mining_ready"],
    QualificationStatus: ["pass", "fail", "pending", "conflict"],
  },
  objects: {
    AgentEvidenceRef: {
      fields: {
        schema: {
          const: "fased.agent-evidence-ref.v1",
        },
        evidenceId: {
          type: "identifier",
        },
        source: {
          enum: "EvidenceSource",
        },
        trust: {
          enum: "EvidenceTrust",
        },
        observedAt: {
          type: "timestamp",
        },
        authority: {
          type: "identifier",
          optional: true,
        },
        slot: {
          type: "uintString",
          optional: true,
        },
        transactionSignature: {
          type: "identifier",
          optional: true,
        },
        digestSha256: {
          type: "sha256",
          optional: true,
        },
        expiresAt: {
          type: "timestamp",
          optional: true,
        },
      },
    },
    AgentViewConflict: {
      fields: {
        code: {
          type: "identifier",
        },
        message: {
          type: "text",
        },
        evidenceIds: {
          array: "identifier",
        },
      },
    },
    AgentNamespaceView: {
      fields: {
        binding: {
          type: "solanaAddress",
        },
        networkAgentId: {
          type: "hex32",
        },
        name: {
          type: "agentName",
        },
        handle: {
          type: "agentHandle",
        },
        ticker: {
          type: "agentTicker",
        },
        boundSlot: {
          type: "uintString",
        },
        recordAuthorityGeneration: {
          type: "uintString",
        },
      },
    },
    AgentRuntimeView: {
      fields: {
        state: {
          enum: "RuntimeState",
        },
        nodeId: {
          type: "identifier",
          optional: true,
        },
        runtimeVersion: {
          type: "identifier",
          optional: true,
        },
        coreHash: {
          type: "sha256",
          optional: true,
        },
        attestedAt: {
          type: "timestamp",
          optional: true,
        },
        expiresAt: {
          type: "timestamp",
          optional: true,
        },
      },
      variants: [
        {
          when: {
            field: "state",
            equals: "absent",
          },
          forbidden: ["nodeId", "runtimeVersion", "coreHash", "attestedAt", "expiresAt"],
        },
        {
          when: {
            field: "state",
            equals: "current",
          },
          required: ["nodeId", "runtimeVersion", "coreHash", "attestedAt", "expiresAt"],
        },
        {
          when: {
            field: "state",
            equals: "stale",
          },
          required: ["nodeId", "runtimeVersion", "coreHash", "attestedAt", "expiresAt"],
        },
      ],
    },
    AgentMiningBindingView: {
      fields: {
        binding: {
          type: "solanaAddress",
        },
        satAgentRecord: {
          type: "solanaAddress",
        },
        satcoinProgramId: {
          type: "solanaAddress",
        },
        permanentMiningId: {
          type: "solanaAddress",
        },
        boundSlot: {
          type: "uintString",
        },
      },
    },
    AgentIdentityView: {
      fields: {
        schema: {
          const: "fased.agent-identity-view.v1",
        },
        viewId: {
          type: "sha256",
        },
        observedAt: {
          type: "timestamp",
        },
        freshness: {
          enum: "ViewFreshness",
        },
        integrity: {
          enum: "ViewIntegrity",
        },
        lifecycle: {
          enum: "AgentLifecycle",
        },
        fasedAgentRecord: {
          type: "solanaAddress",
          optional: true,
        },
        networkAgentId: {
          type: "hex32",
          optional: true,
        },
        controller: {
          type: "solanaAddress",
          optional: true,
        },
        recoveryAuthority: {
          type: "solanaAddress",
          optional: true,
        },
        authorityGeneration: {
          type: "uintString",
          optional: true,
        },
        createdSlot: {
          type: "uintString",
          optional: true,
        },
        createdUnixTimestamp: {
          type: "intString",
          optional: true,
        },
        namespace: {
          ref: "AgentNamespaceView",
          optional: true,
        },
        miningBinding: {
          ref: "AgentMiningBindingView",
          optional: true,
        },
        runtime: {
          ref: "AgentRuntimeView",
          optional: true,
        },
        conflicts: {
          arrayRef: "AgentViewConflict",
        },
        evidence: {
          arrayRef: "AgentEvidenceRef",
        },
      },
      variants: [
        {
          when: {
            field: "lifecycle",
            equals: "network_only",
          },
          required: ["networkAgentId", "runtime"],
          forbidden: [
            "fasedAgentRecord",
            "controller",
            "recoveryAuthority",
            "authorityGeneration",
            "createdSlot",
            "createdUnixTimestamp",
            "namespace",
            "miningBinding",
          ],
        },
        {
          when: {
            field: "lifecycle",
            equals: "active",
          },
          required: [
            "fasedAgentRecord",
            "controller",
            "recoveryAuthority",
            "authorityGeneration",
            "createdSlot",
            "createdUnixTimestamp",
          ],
        },
        {
          when: {
            field: "lifecycle",
            equals: "retired",
          },
          required: [
            "fasedAgentRecord",
            "controller",
            "recoveryAuthority",
            "authorityGeneration",
            "createdSlot",
            "createdUnixTimestamp",
          ],
        },
        {
          when: {
            field: "integrity",
            equals: "verified",
          },
          maxItems: {
            field: "conflicts",
            value: 0,
          },
        },
        {
          when: {
            field: "integrity",
            equals: "conflict",
          },
          minItems: {
            field: "conflicts",
            value: 1,
          },
        },
      ],
    },
    AgentComponentGenerations: {
      fields: {
        tupleFormat: {
          type: "uintString",
        },
        schema: {
          type: "uintString",
        },
        protocol: {
          type: "uintString",
        },
        cycle: {
          type: "uintString",
        },
        economics: {
          type: "uintString",
        },
        penalty: {
          type: "uintString",
        },
        bond: {
          type: "uintString",
        },
        keeper: {
          type: "uintString",
        },
        receipt: {
          type: "uintString",
        },
        signerCapability: {
          type: "uintString",
        },
      },
    },
    AgentMiningCounters: {
      fields: {
        entered: {
          type: "uintString",
        },
        valid: {
          type: "uintString",
        },
        missed: {
          type: "uintString",
        },
        penalized: {
          type: "uintString",
        },
        protocolFault: {
          type: "uintString",
        },
      },
    },
    AgentMiningRewards: {
      fields: {
        baseSatRaw: {
          type: "uintString",
        },
        performanceSatRaw: {
          type: "uintString",
        },
        deterministicSolLamports: {
          type: "uintString",
        },
        performanceSolLamports: {
          type: "intString",
        },
        treasurySolLamports: {
          type: "uintString",
        },
        penaltySolLamports: {
          type: "uintString",
        },
        keeperCostLamports: {
          type: "uintString",
        },
      },
    },
    AgentMiningCapitalView: {
      fields: {
        activeCapitalLamports: {
          type: "uintString",
        },
        committedCapitalLamports: {
          type: "uintString",
        },
        operatingReserveLamports: {
          type: "uintString",
        },
        capitalTimeLamportCycles: {
          type: "uintString",
        },
      },
    },
    AgentMiningOperationsView: {
      fields: {
        pendingCommitCount: {
          type: "uintString",
        },
        pendingClaimCount: {
          type: "uintString",
        },
        unresolvedCycleCount: {
          type: "uintString",
        },
        keeperMonitor: {
          enum: "KeeperState",
        },
        keeperBroadcast: {
          enum: "BroadcastState",
        },
      },
    },
    AgentMiningReceiptView: {
      fields: {
        lastRecordedCycleId: {
          type: "uintString",
        },
        receiptSequence: {
          type: "uintString",
        },
        currentEconomicEpochId: {
          type: "uintString",
        },
        currentEconomicEpochReceiptRoot: {
          type: "sha256",
        },
        closedEconomicEpochsRoot: {
          type: "sha256",
        },
      },
    },
    AgentMiningStrikeView: {
      fields: {
        rollingStrikeCount: {
          type: "uintString",
        },
        cleanActiveDays: {
          type: "uintString",
        },
      },
    },
    AgentMiningView: {
      fields: {
        schema: {
          const: "fased.agent-mining-view.v1",
        },
        viewId: {
          type: "sha256",
        },
        observedAt: {
          type: "timestamp",
        },
        freshness: {
          enum: "ViewFreshness",
        },
        integrity: {
          enum: "ViewIntegrity",
        },
        lifecycle: {
          enum: "MiningLifecycle",
        },
        entryState: {
          enum: "MiningEntryState",
        },
        satAgentRecord: {
          type: "solanaAddress",
        },
        satcoinProgramId: {
          type: "solanaAddress",
        },
        permanentMiningId: {
          type: "solanaAddress",
        },
        controller: {
          type: "solanaAddress",
        },
        activeMinerAuthority: {
          type: "solanaAddress",
        },
        runtimeExecutor: {
          type: "solanaAddress",
        },
        keeperFeePayer: {
          type: "solanaAddress",
        },
        authorityGeneration: {
          type: "uintString",
        },
        runtimeGeneration: {
          type: "uintString",
        },
        policyGeneration: {
          type: "uintString",
        },
        componentGenerations: {
          ref: "AgentComponentGenerations",
        },
        lifetimeCounters: {
          ref: "AgentMiningCounters",
        },
        currentEconomicEpochCounters: {
          ref: "AgentMiningCounters",
        },
        lifetimeRewards: {
          ref: "AgentMiningRewards",
        },
        currentEconomicEpochRewards: {
          ref: "AgentMiningRewards",
        },
        capital: {
          ref: "AgentMiningCapitalView",
        },
        operations: {
          ref: "AgentMiningOperationsView",
        },
        receipts: {
          ref: "AgentMiningReceiptView",
        },
        strikes: {
          ref: "AgentMiningStrikeView",
        },
        conflicts: {
          arrayRef: "AgentViewConflict",
        },
        evidence: {
          arrayRef: "AgentEvidenceRef",
        },
      },
      variants: [
        {
          when: {
            field: "integrity",
            equals: "verified",
          },
          maxItems: {
            field: "conflicts",
            value: 0,
          },
        },
        {
          when: {
            field: "integrity",
            equals: "conflict",
          },
          minItems: {
            field: "conflicts",
            value: 1,
          },
        },
        {
          when: {
            field: "entryState",
            equals: "drained",
          },
          equals: [
            {
              field: "capital.activeCapitalLamports",
              value: "0",
            },
            {
              field: "capital.committedCapitalLamports",
              value: "0",
            },
            {
              field: "operations.unresolvedCycleCount",
              value: "0",
            },
          ],
        },
      ],
    },
    AgentQualificationSubject: {
      fields: {
        fasedAgentRecord: {
          type: "solanaAddress",
          optional: true,
        },
        satAgentRecord: {
          type: "solanaAddress",
          optional: true,
        },
      },
    },
    AgentQualificationGate: {
      fields: {
        gate: {
          type: "identifier",
        },
        status: {
          enum: "QualificationStatus",
        },
        observed: {
          type: "text",
          optional: true,
        },
        required: {
          type: "text",
          optional: true,
        },
        evidenceIds: {
          array: "identifier",
        },
      },
    },
    AgentQualificationView: {
      fields: {
        schema: {
          const: "fased.agent-qualification-view.v1",
        },
        viewId: {
          type: "sha256",
        },
        evaluatedAt: {
          type: "timestamp",
        },
        purpose: {
          enum: "QualificationPurpose",
        },
        status: {
          enum: "QualificationStatus",
        },
        policyId: {
          type: "identifier",
        },
        policyGeneration: {
          type: "uintString",
        },
        policyDigestSha256: {
          type: "sha256",
        },
        subject: {
          ref: "AgentQualificationSubject",
        },
        gates: {
          arrayRef: "AgentQualificationGate",
          minItems: 1,
        },
        conflicts: {
          arrayRef: "AgentViewConflict",
        },
        evidence: {
          arrayRef: "AgentEvidenceRef",
        },
      },
      variants: [
        {
          when: {
            field: "purpose",
            equals: "public_identity",
          },
          requiredPath: ["subject.fasedAgentRecord"],
        },
        {
          when: {
            field: "purpose",
            equals: "mining_ready",
          },
          requiredPath: ["subject.satAgentRecord"],
        },
        {
          when: {
            field: "status",
            equals: "conflict",
          },
          minItems: {
            field: "conflicts",
            value: 1,
          },
        },
      ],
    },
  },
  publicViews: [
    "AgentEvidenceRef",
    "AgentIdentityView",
    "AgentMiningView",
    "AgentQualificationView",
  ],
} as const;

export const FASED_PUBLIC_AGENT_VIEW_JSON_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "fased.public-agent-views.v1",
  title: "Fased public Agent views v1",
  oneOf: [
    {
      $ref: "#/$defs/AgentEvidenceRef",
    },
    {
      $ref: "#/$defs/AgentIdentityView",
    },
    {
      $ref: "#/$defs/AgentMiningView",
    },
    {
      $ref: "#/$defs/AgentQualificationView",
    },
  ],
  $defs: {
    AgentEvidenceRef: {
      type: "object",
      additionalProperties: false,
      properties: {
        schema: {
          type: "string",
          const: "fased.agent-evidence-ref.v1",
        },
        evidenceId: {
          type: "string",
          pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
        },
        source: {
          type: "string",
          enum: [
            "agent_identity_program",
            "satcoin_program",
            "fased_network",
            "fased_runtime",
            "owner_declaration",
          ],
        },
        trust: {
          type: "string",
          enum: ["finalized", "signed", "declared"],
        },
        observedAt: {
          type: "string",
          format: "date-time",
        },
        authority: {
          type: "string",
          pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
        },
        slot: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        transactionSignature: {
          type: "string",
          pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
        },
        digestSha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        expiresAt: {
          type: "string",
          format: "date-time",
        },
      },
      required: ["schema", "evidenceId", "source", "trust", "observedAt"],
    },
    AgentViewConflict: {
      type: "object",
      additionalProperties: false,
      properties: {
        code: {
          type: "string",
          pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
        },
        message: {
          type: "string",
          minLength: 1,
          maxLength: 500,
        },
        evidenceIds: {
          type: "array",
          items: {
            type: "string",
            pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
          },
        },
      },
      required: ["code", "message", "evidenceIds"],
    },
    AgentNamespaceView: {
      type: "object",
      additionalProperties: false,
      properties: {
        binding: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        networkAgentId: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        name: {
          type: "string",
          pattern: "^[A-Za-z][A-Za-z0-9]{1,19}$",
        },
        handle: {
          type: "string",
          pattern: "^@[a-z][a-z0-9-]{1,19}$",
        },
        ticker: {
          type: "string",
          pattern: "^[A-Z][A-Z0-9]{1,5}$",
        },
        boundSlot: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        recordAuthorityGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
      },
      required: [
        "binding",
        "networkAgentId",
        "name",
        "handle",
        "ticker",
        "boundSlot",
        "recordAuthorityGeneration",
      ],
    },
    AgentRuntimeView: {
      type: "object",
      additionalProperties: false,
      properties: {
        state: {
          type: "string",
          enum: ["current", "stale", "absent"],
        },
        nodeId: {
          type: "string",
          pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
        },
        runtimeVersion: {
          type: "string",
          pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
        },
        coreHash: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        attestedAt: {
          type: "string",
          format: "date-time",
        },
        expiresAt: {
          type: "string",
          format: "date-time",
        },
      },
      required: ["state"],
      allOf: [
        {
          if: {
            required: ["state"],
            properties: {
              state: {
                const: "absent",
              },
            },
          },
          then: {
            allOf: [
              {
                not: {
                  required: ["nodeId"],
                },
              },
              {
                not: {
                  required: ["runtimeVersion"],
                },
              },
              {
                not: {
                  required: ["coreHash"],
                },
              },
              {
                not: {
                  required: ["attestedAt"],
                },
              },
              {
                not: {
                  required: ["expiresAt"],
                },
              },
            ],
          },
        },
        {
          if: {
            required: ["state"],
            properties: {
              state: {
                const: "current",
              },
            },
          },
          then: {
            required: ["nodeId", "runtimeVersion", "coreHash", "attestedAt", "expiresAt"],
          },
        },
        {
          if: {
            required: ["state"],
            properties: {
              state: {
                const: "stale",
              },
            },
          },
          then: {
            required: ["nodeId", "runtimeVersion", "coreHash", "attestedAt", "expiresAt"],
          },
        },
      ],
    },
    AgentMiningBindingView: {
      type: "object",
      additionalProperties: false,
      properties: {
        binding: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        satAgentRecord: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        satcoinProgramId: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        permanentMiningId: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        boundSlot: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
      },
      required: ["binding", "satAgentRecord", "satcoinProgramId", "permanentMiningId", "boundSlot"],
    },
    AgentIdentityView: {
      type: "object",
      additionalProperties: false,
      properties: {
        schema: {
          type: "string",
          const: "fased.agent-identity-view.v1",
        },
        viewId: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        observedAt: {
          type: "string",
          format: "date-time",
        },
        freshness: {
          type: "string",
          enum: ["fresh", "stale"],
        },
        integrity: {
          type: "string",
          enum: ["verified", "conflict"],
        },
        lifecycle: {
          type: "string",
          enum: ["network_only", "active", "retired"],
        },
        fasedAgentRecord: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        networkAgentId: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        controller: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        recoveryAuthority: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        authorityGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        createdSlot: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        createdUnixTimestamp: {
          type: "string",
          pattern: "^(0|-?[1-9][0-9]*)$",
        },
        namespace: {
          $ref: "#/$defs/AgentNamespaceView",
        },
        miningBinding: {
          $ref: "#/$defs/AgentMiningBindingView",
        },
        runtime: {
          $ref: "#/$defs/AgentRuntimeView",
        },
        conflicts: {
          type: "array",
          items: {
            $ref: "#/$defs/AgentViewConflict",
          },
        },
        evidence: {
          type: "array",
          items: {
            $ref: "#/$defs/AgentEvidenceRef",
          },
        },
      },
      required: [
        "schema",
        "viewId",
        "observedAt",
        "freshness",
        "integrity",
        "lifecycle",
        "conflicts",
        "evidence",
      ],
      allOf: [
        {
          if: {
            required: ["lifecycle"],
            properties: {
              lifecycle: {
                const: "network_only",
              },
            },
          },
          then: {
            allOf: [
              {
                required: ["networkAgentId", "runtime"],
              },
              {
                not: {
                  required: ["fasedAgentRecord"],
                },
              },
              {
                not: {
                  required: ["controller"],
                },
              },
              {
                not: {
                  required: ["recoveryAuthority"],
                },
              },
              {
                not: {
                  required: ["authorityGeneration"],
                },
              },
              {
                not: {
                  required: ["createdSlot"],
                },
              },
              {
                not: {
                  required: ["createdUnixTimestamp"],
                },
              },
              {
                not: {
                  required: ["namespace"],
                },
              },
              {
                not: {
                  required: ["miningBinding"],
                },
              },
            ],
          },
        },
        {
          if: {
            required: ["lifecycle"],
            properties: {
              lifecycle: {
                const: "active",
              },
            },
          },
          then: {
            required: [
              "fasedAgentRecord",
              "controller",
              "recoveryAuthority",
              "authorityGeneration",
              "createdSlot",
              "createdUnixTimestamp",
            ],
          },
        },
        {
          if: {
            required: ["lifecycle"],
            properties: {
              lifecycle: {
                const: "retired",
              },
            },
          },
          then: {
            required: [
              "fasedAgentRecord",
              "controller",
              "recoveryAuthority",
              "authorityGeneration",
              "createdSlot",
              "createdUnixTimestamp",
            ],
          },
        },
        {
          if: {
            required: ["integrity"],
            properties: {
              integrity: {
                const: "verified",
              },
            },
          },
          then: {
            required: ["conflicts"],
            properties: {
              conflicts: {
                type: "array",
                maxItems: 0,
              },
            },
          },
        },
        {
          if: {
            required: ["integrity"],
            properties: {
              integrity: {
                const: "conflict",
              },
            },
          },
          then: {
            required: ["conflicts"],
            properties: {
              conflicts: {
                type: "array",
                minItems: 1,
              },
            },
          },
        },
      ],
    },
    AgentComponentGenerations: {
      type: "object",
      additionalProperties: false,
      properties: {
        tupleFormat: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        schema: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        protocol: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        cycle: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        economics: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        penalty: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        bond: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        keeper: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        receipt: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        signerCapability: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
      },
      required: [
        "tupleFormat",
        "schema",
        "protocol",
        "cycle",
        "economics",
        "penalty",
        "bond",
        "keeper",
        "receipt",
        "signerCapability",
      ],
    },
    AgentMiningCounters: {
      type: "object",
      additionalProperties: false,
      properties: {
        entered: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        valid: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        missed: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        penalized: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        protocolFault: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
      },
      required: ["entered", "valid", "missed", "penalized", "protocolFault"],
    },
    AgentMiningRewards: {
      type: "object",
      additionalProperties: false,
      properties: {
        baseSatRaw: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        performanceSatRaw: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        deterministicSolLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        performanceSolLamports: {
          type: "string",
          pattern: "^(0|-?[1-9][0-9]*)$",
        },
        treasurySolLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        penaltySolLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        keeperCostLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
      },
      required: [
        "baseSatRaw",
        "performanceSatRaw",
        "deterministicSolLamports",
        "performanceSolLamports",
        "treasurySolLamports",
        "penaltySolLamports",
        "keeperCostLamports",
      ],
    },
    AgentMiningCapitalView: {
      type: "object",
      additionalProperties: false,
      properties: {
        activeCapitalLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        committedCapitalLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        operatingReserveLamports: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        capitalTimeLamportCycles: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
      },
      required: [
        "activeCapitalLamports",
        "committedCapitalLamports",
        "operatingReserveLamports",
        "capitalTimeLamportCycles",
      ],
    },
    AgentMiningOperationsView: {
      type: "object",
      additionalProperties: false,
      properties: {
        pendingCommitCount: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        pendingClaimCount: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        unresolvedCycleCount: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        keeperMonitor: {
          type: "string",
          enum: ["healthy", "degraded", "offline", "unknown"],
        },
        keeperBroadcast: {
          type: "string",
          enum: ["eligible", "ineligible", "disabled", "unknown"],
        },
      },
      required: [
        "pendingCommitCount",
        "pendingClaimCount",
        "unresolvedCycleCount",
        "keeperMonitor",
        "keeperBroadcast",
      ],
    },
    AgentMiningReceiptView: {
      type: "object",
      additionalProperties: false,
      properties: {
        lastRecordedCycleId: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        receiptSequence: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        currentEconomicEpochId: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        currentEconomicEpochReceiptRoot: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        closedEconomicEpochsRoot: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
      },
      required: [
        "lastRecordedCycleId",
        "receiptSequence",
        "currentEconomicEpochId",
        "currentEconomicEpochReceiptRoot",
        "closedEconomicEpochsRoot",
      ],
    },
    AgentMiningStrikeView: {
      type: "object",
      additionalProperties: false,
      properties: {
        rollingStrikeCount: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        cleanActiveDays: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
      },
      required: ["rollingStrikeCount", "cleanActiveDays"],
    },
    AgentMiningView: {
      type: "object",
      additionalProperties: false,
      properties: {
        schema: {
          type: "string",
          const: "fased.agent-mining-view.v1",
        },
        viewId: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        observedAt: {
          type: "string",
          format: "date-time",
        },
        freshness: {
          type: "string",
          enum: ["fresh", "stale"],
        },
        integrity: {
          type: "string",
          enum: ["verified", "conflict"],
        },
        lifecycle: {
          type: "string",
          enum: ["active", "retired"],
        },
        entryState: {
          type: "string",
          enum: ["enabled", "paused", "draining", "drained"],
        },
        satAgentRecord: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        satcoinProgramId: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        permanentMiningId: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        controller: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        activeMinerAuthority: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        runtimeExecutor: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        keeperFeePayer: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        authorityGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        runtimeGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        policyGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        componentGenerations: {
          $ref: "#/$defs/AgentComponentGenerations",
        },
        lifetimeCounters: {
          $ref: "#/$defs/AgentMiningCounters",
        },
        currentEconomicEpochCounters: {
          $ref: "#/$defs/AgentMiningCounters",
        },
        lifetimeRewards: {
          $ref: "#/$defs/AgentMiningRewards",
        },
        currentEconomicEpochRewards: {
          $ref: "#/$defs/AgentMiningRewards",
        },
        capital: {
          $ref: "#/$defs/AgentMiningCapitalView",
        },
        operations: {
          $ref: "#/$defs/AgentMiningOperationsView",
        },
        receipts: {
          $ref: "#/$defs/AgentMiningReceiptView",
        },
        strikes: {
          $ref: "#/$defs/AgentMiningStrikeView",
        },
        conflicts: {
          type: "array",
          items: {
            $ref: "#/$defs/AgentViewConflict",
          },
        },
        evidence: {
          type: "array",
          items: {
            $ref: "#/$defs/AgentEvidenceRef",
          },
        },
      },
      required: [
        "schema",
        "viewId",
        "observedAt",
        "freshness",
        "integrity",
        "lifecycle",
        "entryState",
        "satAgentRecord",
        "satcoinProgramId",
        "permanentMiningId",
        "controller",
        "activeMinerAuthority",
        "runtimeExecutor",
        "keeperFeePayer",
        "authorityGeneration",
        "runtimeGeneration",
        "policyGeneration",
        "componentGenerations",
        "lifetimeCounters",
        "currentEconomicEpochCounters",
        "lifetimeRewards",
        "currentEconomicEpochRewards",
        "capital",
        "operations",
        "receipts",
        "strikes",
        "conflicts",
        "evidence",
      ],
      allOf: [
        {
          if: {
            required: ["integrity"],
            properties: {
              integrity: {
                const: "verified",
              },
            },
          },
          then: {
            required: ["conflicts"],
            properties: {
              conflicts: {
                type: "array",
                maxItems: 0,
              },
            },
          },
        },
        {
          if: {
            required: ["integrity"],
            properties: {
              integrity: {
                const: "conflict",
              },
            },
          },
          then: {
            required: ["conflicts"],
            properties: {
              conflicts: {
                type: "array",
                minItems: 1,
              },
            },
          },
        },
        {
          if: {
            required: ["entryState"],
            properties: {
              entryState: {
                const: "drained",
              },
            },
          },
          then: {
            allOf: [
              {
                required: ["capital"],
                properties: {
                  capital: {
                    type: "object",
                    required: ["activeCapitalLamports"],
                    properties: {
                      activeCapitalLamports: {
                        const: "0",
                      },
                    },
                  },
                },
              },
              {
                required: ["capital"],
                properties: {
                  capital: {
                    type: "object",
                    required: ["committedCapitalLamports"],
                    properties: {
                      committedCapitalLamports: {
                        const: "0",
                      },
                    },
                  },
                },
              },
              {
                required: ["operations"],
                properties: {
                  operations: {
                    type: "object",
                    required: ["unresolvedCycleCount"],
                    properties: {
                      unresolvedCycleCount: {
                        const: "0",
                      },
                    },
                  },
                },
              },
            ],
          },
        },
      ],
    },
    AgentQualificationSubject: {
      type: "object",
      additionalProperties: false,
      properties: {
        fasedAgentRecord: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
        satAgentRecord: {
          type: "string",
          pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
        },
      },
      required: [],
    },
    AgentQualificationGate: {
      type: "object",
      additionalProperties: false,
      properties: {
        gate: {
          type: "string",
          pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
        },
        status: {
          type: "string",
          enum: ["pass", "fail", "pending", "conflict"],
        },
        observed: {
          type: "string",
          minLength: 1,
          maxLength: 500,
        },
        required: {
          type: "string",
          minLength: 1,
          maxLength: 500,
        },
        evidenceIds: {
          type: "array",
          items: {
            type: "string",
            pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
          },
        },
      },
      required: ["gate", "status", "evidenceIds"],
    },
    AgentQualificationView: {
      type: "object",
      additionalProperties: false,
      properties: {
        schema: {
          type: "string",
          const: "fased.agent-qualification-view.v1",
        },
        viewId: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        evaluatedAt: {
          type: "string",
          format: "date-time",
        },
        purpose: {
          type: "string",
          enum: ["public_identity", "mining_ready"],
        },
        status: {
          type: "string",
          enum: ["pass", "fail", "pending", "conflict"],
        },
        policyId: {
          type: "string",
          pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
        },
        policyGeneration: {
          type: "string",
          pattern: "^(0|[1-9][0-9]*)$",
        },
        policyDigestSha256: {
          type: "string",
          pattern: "^[0-9a-f]{64}$",
        },
        subject: {
          $ref: "#/$defs/AgentQualificationSubject",
        },
        gates: {
          type: "array",
          items: {
            $ref: "#/$defs/AgentQualificationGate",
          },
          minItems: 1,
        },
        conflicts: {
          type: "array",
          items: {
            $ref: "#/$defs/AgentViewConflict",
          },
        },
        evidence: {
          type: "array",
          items: {
            $ref: "#/$defs/AgentEvidenceRef",
          },
        },
      },
      required: [
        "schema",
        "viewId",
        "evaluatedAt",
        "purpose",
        "status",
        "policyId",
        "policyGeneration",
        "policyDigestSha256",
        "subject",
        "gates",
        "conflicts",
        "evidence",
      ],
      allOf: [
        {
          if: {
            required: ["purpose"],
            properties: {
              purpose: {
                const: "public_identity",
              },
            },
          },
          then: {
            required: ["subject"],
            properties: {
              subject: {
                type: "object",
                required: ["fasedAgentRecord"],
                properties: {
                  fasedAgentRecord: {},
                },
              },
            },
          },
        },
        {
          if: {
            required: ["purpose"],
            properties: {
              purpose: {
                const: "mining_ready",
              },
            },
          },
          then: {
            required: ["subject"],
            properties: {
              subject: {
                type: "object",
                required: ["satAgentRecord"],
                properties: {
                  satAgentRecord: {},
                },
              },
            },
          },
        },
        {
          if: {
            required: ["status"],
            properties: {
              status: {
                const: "conflict",
              },
            },
          },
          then: {
            required: ["conflicts"],
            properties: {
              conflicts: {
                type: "array",
                minItems: 1,
              },
            },
          },
        },
      ],
    },
  },
} as const;

export type EvidenceSource =
  | "agent_identity_program"
  | "satcoin_program"
  | "fased_network"
  | "fased_runtime"
  | "owner_declaration";

export type EvidenceTrust = "finalized" | "signed" | "declared";

export type ViewFreshness = "fresh" | "stale";

export type ViewIntegrity = "verified" | "conflict";

export type AgentLifecycle = "network_only" | "active" | "retired";

export type RuntimeState = "current" | "stale" | "absent";

export type MiningLifecycle = "active" | "retired";

export type MiningEntryState = "enabled" | "paused" | "draining" | "drained";

export type KeeperState = "healthy" | "degraded" | "offline" | "unknown";

export type BroadcastState = "eligible" | "ineligible" | "disabled" | "unknown";

export type QualificationPurpose = "public_identity" | "mining_ready";

export type QualificationStatus = "pass" | "fail" | "pending" | "conflict";

export type AgentEvidenceRef = {
  schema: "fased.agent-evidence-ref.v1";

  evidenceId: string;

  source: EvidenceSource;

  trust: EvidenceTrust;

  observedAt: string;

  authority?: string;

  slot?: string;

  transactionSignature?: string;

  digestSha256?: string;

  expiresAt?: string;
};

export type AgentViewConflict = {
  code: string;

  message: string;

  evidenceIds: string[];
};

export type AgentNamespaceView = {
  binding: string;

  networkAgentId: string;

  name: string;

  handle: string;

  ticker: string;

  boundSlot: string;

  recordAuthorityGeneration: string;
};

export type AgentRuntimeView = {
  state: RuntimeState;

  nodeId?: string;

  runtimeVersion?: string;

  coreHash?: string;

  attestedAt?: string;

  expiresAt?: string;
};

export type AgentMiningBindingView = {
  binding: string;

  satAgentRecord: string;

  satcoinProgramId: string;

  permanentMiningId: string;

  boundSlot: string;
};

export type AgentIdentityView = {
  schema: "fased.agent-identity-view.v1";

  viewId: string;

  observedAt: string;

  freshness: ViewFreshness;

  integrity: ViewIntegrity;

  lifecycle: AgentLifecycle;

  fasedAgentRecord?: string;

  networkAgentId?: string;

  controller?: string;

  recoveryAuthority?: string;

  authorityGeneration?: string;

  createdSlot?: string;

  createdUnixTimestamp?: string;

  namespace?: AgentNamespaceView;

  miningBinding?: AgentMiningBindingView;

  runtime?: AgentRuntimeView;

  conflicts: AgentViewConflict[];

  evidence: AgentEvidenceRef[];
};

export type AgentComponentGenerations = {
  tupleFormat: string;

  schema: string;

  protocol: string;

  cycle: string;

  economics: string;

  penalty: string;

  bond: string;

  keeper: string;

  receipt: string;

  signerCapability: string;
};

export type AgentMiningCounters = {
  entered: string;

  valid: string;

  missed: string;

  penalized: string;

  protocolFault: string;
};

export type AgentMiningRewards = {
  baseSatRaw: string;

  performanceSatRaw: string;

  deterministicSolLamports: string;

  performanceSolLamports: string;

  treasurySolLamports: string;

  penaltySolLamports: string;

  keeperCostLamports: string;
};

export type AgentMiningCapitalView = {
  activeCapitalLamports: string;

  committedCapitalLamports: string;

  operatingReserveLamports: string;

  capitalTimeLamportCycles: string;
};

export type AgentMiningOperationsView = {
  pendingCommitCount: string;

  pendingClaimCount: string;

  unresolvedCycleCount: string;

  keeperMonitor: KeeperState;

  keeperBroadcast: BroadcastState;
};

export type AgentMiningReceiptView = {
  lastRecordedCycleId: string;

  receiptSequence: string;

  currentEconomicEpochId: string;

  currentEconomicEpochReceiptRoot: string;

  closedEconomicEpochsRoot: string;
};

export type AgentMiningStrikeView = {
  rollingStrikeCount: string;

  cleanActiveDays: string;
};

export type AgentMiningView = {
  schema: "fased.agent-mining-view.v1";

  viewId: string;

  observedAt: string;

  freshness: ViewFreshness;

  integrity: ViewIntegrity;

  lifecycle: MiningLifecycle;

  entryState: MiningEntryState;

  satAgentRecord: string;

  satcoinProgramId: string;

  permanentMiningId: string;

  controller: string;

  activeMinerAuthority: string;

  runtimeExecutor: string;

  keeperFeePayer: string;

  authorityGeneration: string;

  runtimeGeneration: string;

  policyGeneration: string;

  componentGenerations: AgentComponentGenerations;

  lifetimeCounters: AgentMiningCounters;

  currentEconomicEpochCounters: AgentMiningCounters;

  lifetimeRewards: AgentMiningRewards;

  currentEconomicEpochRewards: AgentMiningRewards;

  capital: AgentMiningCapitalView;

  operations: AgentMiningOperationsView;

  receipts: AgentMiningReceiptView;

  strikes: AgentMiningStrikeView;

  conflicts: AgentViewConflict[];

  evidence: AgentEvidenceRef[];
};

export type AgentQualificationSubject = {
  fasedAgentRecord?: string;

  satAgentRecord?: string;
};

export type AgentQualificationGate = {
  gate: string;

  status: QualificationStatus;

  observed?: string;

  required?: string;

  evidenceIds: string[];
};

export type AgentQualificationView = {
  schema: "fased.agent-qualification-view.v1";

  viewId: string;

  evaluatedAt: string;

  purpose: QualificationPurpose;

  status: QualificationStatus;

  policyId: string;

  policyGeneration: string;

  policyDigestSha256: string;

  subject: AgentQualificationSubject;

  gates: AgentQualificationGate[];

  conflicts: AgentViewConflict[];

  evidence: AgentEvidenceRef[];
};

export type AgentPublicView =
  | AgentEvidenceRef
  | AgentIdentityView
  | AgentMiningView
  | AgentQualificationView;

export type AgentPublicViewValidation =
  | { ok: true; value: AgentPublicView }
  | { ok: false; errors: string[] };

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function readPath(value: unknown, path: string): unknown {
  let current: unknown = value;
  for (const segment of path.split(".")) {
    if (!isRecord(current)) return undefined;
    current = current[segment];
  }
  return current;
}

function validPrimitive(name: string, value: unknown): boolean {
  if (typeof value !== "string") return false;
  const primitives = {
    string: {
      type: "string",
      minLength: 1,
      maxLength: 160,
    },
    identifier: {
      type: "string",
      pattern: "^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,159}$",
    },
    text: {
      type: "string",
      minLength: 1,
      maxLength: 500,
    },
    timestamp: {
      type: "string",
      format: "date-time",
    },
    uintString: {
      type: "string",
      pattern: "^(0|[1-9][0-9]*)$",
    },
    intString: {
      type: "string",
      pattern: "^(0|-?[1-9][0-9]*)$",
    },
    sha256: {
      type: "string",
      pattern: "^[0-9a-f]{64}$",
    },
    hex32: {
      type: "string",
      pattern: "^[0-9a-f]{64}$",
    },
    solanaAddress: {
      type: "string",
      pattern: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
    },
    agentName: {
      type: "string",
      pattern: "^[A-Za-z][A-Za-z0-9]{1,19}$",
    },
    agentHandle: {
      type: "string",
      pattern: "^@[a-z][a-z0-9-]{1,19}$",
    },
    agentTicker: {
      type: "string",
      pattern: "^[A-Z][A-Z0-9]{1,5}$",
    },
  } as Record<
    string,
    { minLength?: number; maxLength?: number; pattern?: string; format?: string }
  >;
  const primitive = primitives[name];
  if (!primitive) return false;
  if (primitive.minLength !== undefined && value.length < primitive.minLength) return false;
  if (primitive.maxLength !== undefined && value.length > primitive.maxLength) return false;
  if (primitive.pattern && !new RegExp(primitive.pattern, "u").test(value)) return false;
  if (primitive.format === "date-time" && !Number.isFinite(Date.parse(value))) return false;
  return true;
}

function validateObject(name: string, value: unknown, path: string, errors: string[]): void {
  if (!isRecord(value)) {
    errors.push(`${path} must be an object`);
    return;
  }
  const objects = FASED_PUBLIC_AGENT_VIEW_CONTRACT.objects as Record<
    string,
    { fields: Record<string, any>; variants?: readonly any[] }
  >;
  const object = objects[name];
  if (!object) {
    errors.push(`${path} references unknown object ${name}`);
    return;
  }
  for (const key of Object.keys(value)) {
    if (!(key in object.fields)) errors.push(`${path}.${key} is not allowed`);
  }
  for (const [field, descriptor] of Object.entries(object.fields)) {
    const child = value[field];
    if (child === undefined) {
      if (!descriptor.optional) errors.push(`${path}.${field} is required`);
      continue;
    }
    const childPath = `${path}.${field}`;
    if (descriptor.const !== undefined) {
      if (child !== descriptor.const) errors.push(`${childPath} must equal ${descriptor.const}`);
    } else if (descriptor.enum) {
      const values = FASED_PUBLIC_AGENT_VIEW_CONTRACT.enums[
        descriptor.enum as keyof typeof FASED_PUBLIC_AGENT_VIEW_CONTRACT.enums
      ] as readonly string[];
      if (typeof child !== "string" || !values.includes(child))
        errors.push(`${childPath} is not in ${descriptor.enum}`);
    } else if (descriptor.ref) validateObject(descriptor.ref, child, childPath, errors);
    else if (descriptor.array || descriptor.arrayRef) {
      if (!Array.isArray(child)) errors.push(`${childPath} must be an array`);
      else {
        if (descriptor.minItems !== undefined && child.length < descriptor.minItems)
          errors.push(`${childPath} requires at least ${descriptor.minItems} items`);
        child.forEach((entry, index) =>
          descriptor.arrayRef
            ? validateObject(descriptor.arrayRef, entry, `${childPath}[${index}]`, errors)
            : !validPrimitive(descriptor.array, entry) &&
              errors.push(`${childPath}[${index}] is invalid`),
        );
      }
    } else if (!validPrimitive(descriptor.type, child)) errors.push(`${childPath} is invalid`);
  }
  for (const variant of object.variants ?? []) {
    if (value[variant.when.field] !== variant.when.equals) continue;
    for (const field of variant.required ?? [])
      if (value[field] === undefined)
        errors.push(`${path}.${field} is required for ${variant.when.equals}`);
    for (const field of variant.forbidden ?? [])
      if (value[field] !== undefined)
        errors.push(`${path}.${field} is forbidden for ${variant.when.equals}`);
    for (const requiredPath of variant.requiredPath ?? [])
      if (readPath(value, requiredPath) === undefined)
        errors.push(`${path}.${requiredPath} is required for ${variant.when.equals}`);
    if (variant.minItems) {
      const items = readPath(value, variant.minItems.field);
      if (!Array.isArray(items) || items.length < variant.minItems.value)
        errors.push(
          `${path}.${variant.minItems.field} requires at least ${variant.minItems.value} items`,
        );
    }
    if (variant.maxItems) {
      const items = readPath(value, variant.maxItems.field);
      if (!Array.isArray(items) || items.length > variant.maxItems.value)
        errors.push(
          `${path}.${variant.maxItems.field} allows at most ${variant.maxItems.value} items`,
        );
    }
    for (const expected of variant.equals ?? [])
      if (readPath(value, expected.field) !== expected.value)
        errors.push(`${path}.${expected.field} must equal ${expected.value}`);
  }
}

export function validateAgentPublicView(value: unknown): AgentPublicViewValidation {
  if (!isRecord(value) || typeof value.schema !== "string")
    return { ok: false, errors: ["$.schema is required"] };
  const bySchema: Record<string, string> = {
    "fased.agent-evidence-ref.v1": "AgentEvidenceRef",
    "fased.agent-identity-view.v1": "AgentIdentityView",
    "fased.agent-mining-view.v1": "AgentMiningView",
    "fased.agent-qualification-view.v1": "AgentQualificationView",
  };
  const name = bySchema[value.schema];
  if (!name) return { ok: false, errors: [`unsupported public Agent view schema ${value.schema}`] };
  const errors: string[] = [];
  validateObject(name, value, "$", errors);
  return errors.length === 0
    ? { ok: true, value: value as AgentPublicView }
    : { ok: false, errors };
}
